-- Add the quality How to Research shelf additions to Supabase.
-- Run this in the Supabase SQL Editor for the project backing the public site.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'chapman-how-to-do-research-at-mit-ai-lab',
  'How to Do Research at the MIT AI Lab',
  'David Chapman edited this 1988 working paper in which MIT AI Lab graduate students pool first-hand advice on reading, writing, programming, choosing problems, and managing advisors and emotions. It treats research as an apprenticeship built from explicit, learnable skills rather than innate talent. The tooling and lab culture it describes are firmly 1980s MIT, so some logistics are dated even where the craft advice holds.',
  'David Chapman (ed.)',
  'https://www.google.com/s2/favicons?domain=dspace.mit.edu&sz=128',
  'How to Research',
  array['Research Apprenticeship','Reading Papers','Advisor Relationships','Graduate School'],
  '75 min read',
  '1988-09-01',
  'MIT AI Lab',
  'https://dspace.mit.edu/bitstream/handle/1721.1/41487/AI_WP_316.pdf',
  'assets/img/covers/real/chapman-how-to-do-research-at-mit-ai-lab.png',
  'First page of the MIT AI Lab working paper How to Do Research',
  'cover',
  'published',
  false
),
(
  'jacob-steinhardt-film-study-for-research',
  'Film Study for Research',
  'Jacob Steinhardt borrows the athlete''s habit of film study and shows how researchers can train deliberately by replaying successful work: re-deriving proofs, reconstructing experiments, and annotating strong papers. He gives concrete drills and repetition schedules that work outside live projects. The examples skew toward machine learning and statistics, his own fields.',
  'Jacob Steinhardt',
  'https://www.google.com/s2/favicons?domain=jsteinhardt.stat.berkeley.edu&sz=128',
  'How to Research',
  array['Deliberate Practice','Research Training','Skill Acquisition','Mentorship'],
  '10 min read',
  '2021-06-28',
  'Jacob Steinhardt',
  'https://jsteinhardt.stat.berkeley.edu/blog/film-study',
  'assets/img/covers/real/jacob-steinhardt-film-study-for-research.png',
  'Film Study for Research essay page',
  'cover',
  'published',
  false
),
(
  'hamming-you-and-your-research',
  'You and Your Research',
  'Richard Hamming''s 1986 Bellcore colloquium argues that doing important work comes from deliberate choices: working on important problems, keeping your door open, and letting courage and effort compound like interest. He backs every claim with Bell Labs cases from Shannon to himself. The examples come from mid-century industrial physics and mathematics, and some career mechanics predate today''s job market.',
  'Richard Hamming',
  'https://www.google.com/s2/favicons?domain=cs.virginia.edu&sz=128',
  'How to Research',
  array['Important Problems','Career Strategy','Compound Effort','Bell Labs'],
  '45 min read',
  '1986-03-07',
  'University of Virginia CS',
  'https://www.cs.virginia.edu/~robins/YouAndYourResearch.html',
  'assets/img/covers/real/hamming-you-and-your-research.png',
  'You and Your Research transcript page',
  'cover',
  'published',
  false
),
(
  'michael-nielsen-principles-of-effective-research',
  'Principles of Effective Research',
  'Michael Nielsen''s 2004 essay splits effective research into self-development and creative work, and argues both must be aimed proactively rather than drifted into. He offers concrete principles: clarify a research vision, balance being a problem-creator versus a problem-solver, and take responsibility for your own trajectory. It was written from theoretical physics and quantum computing, before today''s large-lab AI environment.',
  'Michael Nielsen',
  'https://www.google.com/s2/favicons?domain=michaelnielsen.org&sz=128',
  'How to Research',
  array['Self-Development','Proactive Research','Problem Selection','Research Vision'],
  '30 min read',
  '2004-07-01',
  'Michael Nielsen',
  'https://michaelnielsen.org/blog/principles-of-effective-research/',
  'assets/img/covers/real/michael-nielsen-principles-of-effective-research.png',
  'Principles of Effective Research essay page',
  'cover',
  'published',
  false
),
(
  'keshav-how-to-read-a-paper',
  'How to Read a Paper',
  'S. Keshav''s two-page CCR note teaches the three-pass method: a five-minute scan for the gist, an hour-long pass for the evidence, and a full virtual re-implementation for depth, plus a recipe for literature surveys. Written in 2007 for networking students, its pointers to further reading have aged even though the method itself is field-agnostic.',
  'S. Keshav',
  'https://www.google.com/s2/favicons?domain=cl.cam.ac.uk&sz=128',
  'How to Research',
  array['Three-Pass Method','Paper Reading','Literature Surveys','Research Skills'],
  '8 min read',
  '2007-07-01',
  'ACM SIGCOMM CCR',
  'https://svr-sk818-web.cl.cam.ac.uk/keshav/papers/07/paper-reading.pdf',
  'assets/img/covers/real/keshav-how-to-read-a-paper.png',
  'First page of How to Read a Paper',
  'cover',
  'published',
  false
),
(
  'stearns-some-modest-advice-for-graduate-students',
  'Some Modest Advice for Graduate Students',
  'Stephen Stearns tells graduate students to assume nobody will save them: prepare a thesis plan early, treat committee meetings as leverage, and psychologically insure risky projects with backup routes. The advice is blunt, first-person, and grew out of 1980s evolutionary biology at Yale, so its picture of advisor relationships is more adversarial than many modern programs.',
  'Stephen C. Stearns',
  'https://www.google.com/s2/favicons?domain=stearnslab.yale.edu&sz=128',
  'How to Research',
  array['Graduate School','Risk Management','Advisor Relationships','Thesis Planning'],
  '12 min read',
  '1987-01-01',
  'Stearns Lab, Yale',
  'https://stearnslab.yale.edu/modest-advice',
  'assets/img/covers/real/stearns-some-modest-advice-for-graduate-students.png',
  'Some Modest Advice for Graduate Students essay page',
  'cover',
  'published',
  false
),
(
  'terence-tao-learn-and-relearn-your-field',
  'Learn and Relearn Your Field',
  'Terence Tao advises repeatedly re-learning your own field: ask dumb questions, find alternative proofs of known results, and stress-test standard assumptions until the failure modes become intuitive. He treats even celebrated theorems as objects to interrogate rather than cite. The advice is written for research mathematicians, though the habit transfers to any proof- or model-heavy discipline.',
  'Terence Tao',
  'https://www.google.com/s2/favicons?domain=terrytao.wordpress.com&sz=128',
  'How to Research',
  array['Field Mastery','Re-deriving Results','Mathematical Maturity','Career Advice'],
  '4 min read',
  '2007-01-01',
  'Terence Tao',
  'https://terrytao.wordpress.com/career-advice/learn-and-relearn-your-field/',
  'assets/img/covers/real/terence-tao-learn-and-relearn-your-field.png',
  'Learn and Relearn Your Field career advice page',
  'cover',
  'published',
  false
),
(
  'terence-tao-on-the-importance-of-partial-progress',
  'On the Importance of Partial Progress',
  'Terence Tao argues that failed attacks and toy-case solutions are not wasted work: writing up partial progress isolates the true obstruction and often becomes the germ of the eventual solution. He recommends deliberately banking special cases, weakened statements, and counterexamples. His evidence is drawn from mathematical problem solving, where partial results are unusually well-defined.',
  'Terence Tao',
  'https://www.google.com/s2/favicons?domain=terrytao.wordpress.com&sz=128',
  'How to Research',
  array['Partial Results','Toy Problems','Failed Approaches','Problem Solving'],
  '5 min read',
  '2012-07-17',
  'Terence Tao',
  'https://terrytao.wordpress.com/career-advice/on-the-importance-of-partial-progress/',
  'assets/img/covers/real/terence-tao-on-the-importance-of-partial-progress.png',
  'On the Importance of Partial Progress career advice page',
  'cover',
  'published',
  false
),
(
  'azuma-so-long-and-thanks-for-the-phd',
  'So Long, and Thanks for the Ph.D.!',
  'Ronald Azuma''s graduate-school survival guide, begun in 1997 and revised through 2019, catalogs what CS PhD students learn too late: initiative, daily tangible progress, and managing your advisor matter more than raw brilliance. Each section mixes stories from his UNC years with concrete checklists. The framing is distinctly American computer science, including its funding and job-market particulars.',
  'Ronald T. Azuma',
  'https://www.google.com/s2/favicons?domain=cs.unc.edu&sz=128',
  'How to Research',
  array['PhD Survival','Initiative','Advisor Management','Career Paths'],
  '60 min read',
  '1997-01-01',
  'UNC Computer Science',
  'https://www.cs.unc.edu/~azuma/hitch4.html',
  'assets/img/covers/real/azuma-so-long-and-thanks-for-the-phd.png',
  'So Long and Thanks for the PhD survival guide page',
  'cover',
  'published',
  false
),
(
  'matt-might-illustrated-guide-to-a-phd',
  'The Illustrated Guide to a Ph.D.',
  'Matt Might compresses the meaning of a doctorate into a sequence of circles: human knowledge as a disk, a PhD as a tiny dent pushed into its boundary. The picture is a corrective to grandiosity and a reminder to keep pushing. It is deliberately a three-minute parable rather than practical guidance, written for incoming CS students around 2010.',
  'Matt Might',
  'https://www.google.com/s2/favicons?domain=matt.might.net&sz=128',
  'How to Research',
  array['PhD Perspective','Research Frontier','Specialization','Visual Explanation'],
  '3 min read',
  '2010-01-01',
  'matt.might.net',
  'https://matt.might.net/articles/phd-school-in-pictures/',
  'assets/img/covers/real/matt-might-illustrated-guide-to-a-phd.jpg',
  'Illustrated Guide to a PhD knowledge circle diagram',
  'cover',
  'published',
  false
),
(
  'chris-olah-research-taste-exercises',
  'Research Taste Exercises',
  'Chris Olah proposes concrete exercises for developing research taste: predict which papers will matter, write imaginary abstracts, and keep a journal of ideas to audit later against reality. He frames taste as a trainable predictive model of what will succeed rather than a mystique. The note is explicitly rough, and its examples reflect his interpretability and deep-learning vantage point.',
  'Chris Olah',
  'https://www.google.com/s2/favicons?domain=colah.github.io&sz=128',
  'How to Research',
  array['Research Taste','Deliberate Practice','Problem Selection','Interpretability'],
  '8 min read',
  '2021-01-09',
  'colah''s blog',
  'https://colah.github.io/notes/taste/',
  'assets/img/covers/real/chris-olah-research-taste-exercises.png',
  'Research Taste Exercises note page',
  'cover',
  'published',
  false
),
(
  'nick-feamster-cultivating-your-research-taste',
  'Cultivating Your Research Taste',
  'Nick Feamster describes how researchers develop taste in problems the way people develop taste in music or food: exposure, imitation, feedback, and eventually a personal aesthetic. He offers concrete practices, from reading outside your subfield to dissecting why specific papers feel important and apprenticing with people whose taste you admire. The perspective draws on his networking-research career inside US academia.',
  'Nick Feamster',
  'https://www.google.com/s2/favicons?domain=practicespace.substack.com&sz=128',
  'How to Research',
  array['Research Taste','Problem Selection','Mentorship','Research Career'],
  '9 min read',
  '2025-10-29',
  'Practice Space',
  'https://practicespace.substack.com/p/cultivating-your-research-taste-fbd',
  'assets/img/covers/real/nick-feamster-cultivating-your-research-taste.jpg',
  'Cultivating Your Research Taste article cover',
  'cover',
  'published',
  false
),
(
  'john-regehr-picking-a-research-topic-in-computer-systems',
  'Picking a Research Topic in Computer Systems',
  'John Regehr collects heuristics for picking systems research topics: ride externally imposed technology trends, mine the gaps between communities, and be honest about the difference between problems that are important and problems that are merely fundable. He is explicit that this is one systems professor''s view from 2010, when multicore and embedded devices were the live examples.',
  'John Regehr',
  'https://www.google.com/s2/favicons?domain=blog.regehr.org&sz=128',
  'How to Research',
  array['Topic Selection','Computer Systems','Technology Trends','Research Strategy'],
  '10 min read',
  '2010-03-21',
  'Embedded in Academia',
  'https://blog.regehr.org/archives/46',
  'assets/img/covers/real/john-regehr-picking-a-research-topic-in-computer-systems.png',
  'Picking a Research Topic in Computer Systems blog page',
  'cover',
  'published',
  false
),
(
  'jason-eisner-how-to-find-research-problems',
  'How to Find Research Problems',
  'Jason Eisner, then a Penn graduate student writing for new CS PhD students in 1997, explains where research problems actually come from: nagging anomalies, tool-domain mismatches, and questions that survive being written down and attacked from several directions. He urges students to keep an ideas file and treat dissatisfaction with existing methods as raw material. Examples lean on 1990s natural language processing.',
  'Jason Eisner',
  'https://www.google.com/s2/favicons?domain=cs.jhu.edu&sz=128',
  'How to Research',
  array['Problem Discovery','Research Questions','NLP','Graduate School'],
  '7 min read',
  '1997-01-01',
  'Johns Hopkins CS',
  'https://www.cs.jhu.edu/~jason/advice/how-to-find-research-problems.html',
  'assets/img/covers/real/jason-eisner-how-to-find-research-problems.png',
  'How to Find Research Problems essay page',
  'cover',
  'published',
  false
),
(
  'noah-smith-grad-school-advice',
  'Some Grad School Advice',
  'Noah A. Smith distills the grad-school decision to one question: who will your advisor be? He advises applicants to weight advisor fit over institutional ranking, to talk with current students, and to remember that a PhD is a paid research job rather than a continuation of coursework. The advice targets US computer-science doctoral programs specifically.',
  'Noah A. Smith',
  'https://www.google.com/s2/favicons?domain=cs.cmu.edu&sz=128',
  'How to Research',
  array['Choosing an Advisor','PhD Applications','Graduate School','Mentorship'],
  '5 min read',
  '2007-01-01',
  'Noah A. Smith',
  'https://www.cs.cmu.edu/~nasmith/advice.html',
  'assets/img/covers/real/noah-smith-grad-school-advice.png',
  'Noah Smith grad school advice page',
  'cover',
  'published',
  false
),
(
  'simon-peyton-jones-how-to-write-a-great-research-proposal',
  'How to Write a Great Research Proposal',
  'Simon Peyton Jones''s slide essay on research proposals insists the reader must learn three things fast: what the problem is, why it matters, and why now is the moment it can be cracked. He dissects how bored, overloaded reviewers actually read and structures the proposal around their attention. The framing reflects UK-style funding panels, though the craft carries over to other systems.',
  'Simon Peyton Jones',
  'https://www.google.com/s2/favicons?domain=simon.peytonjones.org&sz=128',
  'How to Research',
  array['Research Proposals','Grant Writing','Problem Framing','Research Communication'],
  '12 min read',
  '2016-07-27',
  'Simon Peyton Jones',
  'https://simon.peytonjones.org/assets/pdfs/great-research-proposal.pdf',
  'assets/img/covers/real/simon-peyton-jones-how-to-write-a-great-research-proposal.png',
  'First slide of How to Write a Great Research Proposal',
  'cover',
  'published',
  false
),
(
  'simon-peyton-jones-how-to-give-a-good-research-talk',
  'How to Give a Good Research Talk',
  'Simon Peyton Jones, John Hughes, and John Launchbury give practical rules for the 25-minute conference talk: say one thing, get to an example within minutes, keep slides sparse, and rehearse the opening. First published in SIGPLAN Notices in 1993, its overhead-projector mechanics are dated but its structural advice remains standard reading in programming-languages circles.',
  'Simon Peyton Jones, John Hughes, and John Launchbury',
  'https://www.google.com/s2/favicons?domain=simon.peytonjones.org&sz=128',
  'How to Research',
  array['Research Talks','Presentation Skills','Conference Speaking','Research Communication'],
  '10 min read',
  '1993-11-01',
  'Simon Peyton Jones',
  'https://simon.peytonjones.org/assets/pdfs/giving-a-talk.pdf',
  'assets/img/covers/real/simon-peyton-jones-how-to-give-a-good-research-talk.png',
  'First page of How to Give a Good Research Talk',
  'cover',
  'published',
  false
),
(
  'cs-grad-job-and-interview-guide',
  'Computer Science Graduate Job and Interview Guide',
  'This community guide, assembled by CS faculty and researchers, walks graduate students through the research job hunt end to end: finding openings, preparing application packages, interviewing, negotiating, and deciding, with real materials from successful candidates. Accounts cover research universities, liberal arts colleges, and industrial labs. It is US-centric and its market snapshots date from around 2020.',
  'CS Guides Community',
  'https://www.google.com/s2/favicons?domain=csguides.github.io&sz=128',
  'How to Research',
  array['Academic Job Market','Industry Research Jobs','Application Materials','Interviewing'],
  '45 min read',
  '2020-01-01',
  'CS Guides',
  'https://csguides.github.io/grad-job-guide/',
  'assets/img/covers/real/cs-grad-job-and-interview-guide.png',
  'CS Graduate Job and Interview Guide landing page',
  'cover',
  'published',
  false
),
(
  'visionbook-how-to-do-research',
  'How to Do Research (Foundations of Computer Vision)',
  'Antonio Torralba, Phillip Isola, and William Freeman close their computer-vision textbook with a chapter on doing research itself: choosing problems by expected surprise, alternating exploration and exploitation, and structuring collaborations honestly. The advice generalizes beyond vision but is calibrated to empirical, publication-driven machine learning in MIT-style labs.',
  'Antonio Torralba, Phillip Isola, and William Freeman',
  'https://www.google.com/s2/favicons?domain=visionbook.mit.edu&sz=128',
  'How to Research',
  array['Research Process','Problem Selection','Computer Vision','Scientific Method'],
  '25 min read',
  '2024-04-16',
  'Foundations of Computer Vision',
  'https://visionbook.mit.edu/how_to_do_research.html',
  'assets/img/covers/real/visionbook-how-to-do-research.jpg',
  'How to Do Research chapter illustration',
  'cover',
  'published',
  false
),
(
  'visionbook-how-to-write-papers',
  'How to Write Papers (Foundations of Computer Vision)',
  'In the writing chapter of Foundations of Computer Vision, Torralba, Isola, and Freeman prescribe a paper-building workflow: nail the one-sentence contribution, design figure-first drafts, and revise for the skimming reviewer before the careful one. Their templates and examples are tuned to CVPR/NeurIPS-style empirical papers rather than journal or theory formats.',
  'Antonio Torralba, Phillip Isola, and William Freeman',
  'https://www.google.com/s2/favicons?domain=visionbook.mit.edu&sz=128',
  'How to Research',
  array['Paper Writing','Scientific Writing','Figures','Peer Review'],
  '30 min read',
  '2024-04-16',
  'Foundations of Computer Vision',
  'https://visionbook.mit.edu/how_to_write_papers.html',
  'assets/img/covers/real/visionbook-how-to-write-papers.jpg',
  'How to Write Papers chapter illustration',
  'cover',
  'published',
  false
),
(
  'visionbook-how-to-give-talks',
  'How to Give Talks (Foundations of Computer Vision)',
  'The talks chapter from Torralba, Isola, and Freeman''s textbook treats a research talk as narrative design: one idea per slide, visual explanations over bullet lists, and rehearsing transitions instead of sentences, with concrete slide makeovers. The guidance is aimed at ML and vision conference talks, where figures carry most of the argument.',
  'Antonio Torralba, Phillip Isola, and William Freeman',
  'https://www.google.com/s2/favicons?domain=visionbook.mit.edu&sz=128',
  'How to Research',
  array['Research Talks','Presentation Design','Storytelling','Conference Speaking'],
  '25 min read',
  '2024-04-16',
  'Foundations of Computer Vision',
  'https://visionbook.mit.edu/how_to_give_talks.html',
  'assets/img/covers/real/visionbook-how-to-give-talks.jpg',
  'How to Give Talks chapter illustration',
  'cover',
  'published',
  false
),
(
  'stanford-cs-phd-advising-guide',
  'Stanford CS PhD Advising Guide',
  'Stanford''s CS department wrote this guide to make the advisor-student relationship legible: what advising is for, how rotations and alignment work, and what students and faculty owe each other in meetings, feedback, and funding. It is unusually explicit about mutual expectations. Some mechanics, like the rotation system, are Stanford-specific.',
  'Stanford Computer Science Department',
  'https://www.google.com/s2/favicons?domain=cs.stanford.edu&sz=128',
  'How to Research',
  array['PhD Advising','Advisor Relationships','Rotations','Expectations Setting'],
  '10 min read',
  '2023-01-01',
  'Stanford Computer Science',
  'https://www.cs.stanford.edu/phd-milestones-progress-guidelines/phd-advising-guide',
  'assets/img/covers/real/stanford-cs-phd-advising-guide.png',
  'Stanford CS PhD Advising Guide page',
  'cover',
  'published',
  false
),
(
  'mor-harchol-balter-applying-to-phd-programs-in-cs',
  'Applying to Ph.D. Programs in Computer Science',
  'Mor Harchol-Balter demystifies CS PhD admissions from the committee''s side: what research experience signals, how recommendation letters are actually read, and how funding decisions work. The document doubles as advice on deciding whether a PhD is right at all. Last revised in 2014, its numbers and school lists reflect that era of US admissions.',
  'Mor Harchol-Balter',
  'https://www.google.com/s2/favicons?domain=cs.cmu.edu&sz=128',
  'How to Research',
  array['PhD Applications','Statement of Purpose','Recommendation Letters','Admissions'],
  '35 min read',
  '2014-04-03',
  'Carnegie Mellon University',
  'https://www.cs.cmu.edu/~harchol/gradschooltalk.pdf',
  'assets/img/covers/real/mor-harchol-balter-applying-to-phd-programs-in-cs.png',
  'First page of Applying to PhD Programs in Computer Science',
  'cover',
  'published',
  false
),
(
  'umd-choosing-a-research-advisor',
  'Choosing a Research Advisor',
  'Udaya Shankar''s short note for Maryland CS students argues that picking an advisor is about two axes: whether the professor''s area excites you and whether their working style — team size, depth versus breadth, implementation versus theory — fits how you work. He tells students to read recent papers and interview current group members before committing. It is a brief departmental note rather than a full essay.',
  'Udaya Shankar',
  'https://www.google.com/s2/favicons?domain=cs.umd.edu&sz=128',
  'How to Research',
  array['Choosing an Advisor','Research Style','Graduate School','Mentorship'],
  '3 min read',
  '2010-01-01',
  'UMD Computer Science',
  'https://www.cs.umd.edu/grad/choosing-your-advisor',
  'assets/img/covers/real/umd-choosing-a-research-advisor.png',
  'Choosing a Research Advisor page',
  'cover',
  'published',
  false
),
(
  'jason-wei-practicing-ai-research',
  'Practicing AI Research',
  'Jason Wei frames AI research as a trainable loop of idea generation, ruthless prioritization, fast experiments, and clear writing, and lists the habits he watched top researchers at Google Brain practice daily. He is candid that he writes as a junior researcher describing peers, and the advice presumes the compute-rich industrial-lab setting of large language model work.',
  'Jason Wei',
  'https://www.google.com/s2/favicons?domain=jasonwei.net&sz=128',
  'How to Research',
  array['AI Research','Deliberate Practice','Fast Iteration','Paper Writing'],
  '8 min read',
  '2023-02-07',
  'Jason Wei',
  'https://www.jasonwei.net/blog/practicing-ai-research',
  'assets/img/covers/real/jason-wei-practicing-ai-research.png',
  'Practicing AI Research blog page',
  'cover',
  'published',
  false
),
(
  'neel-guha-templates-for-ml-research-papers',
  'Templates for Machine Learning Research Papers',
  'Neel Guha gives students literal templates for machine-learning papers: reusable skeletons for intros, method sections, and experiment narratives, keyed to the claim types ML venues expect. The point is to separate the craft of argument from the novelty of the idea. Templates are tuned to current ML conference conventions and will age with them.',
  'Neel Guha',
  'https://www.google.com/s2/favicons?domain=neelguha.github.io&sz=128',
  'How to Research',
  array['Paper Writing','ML Papers','Argument Structure','Research Communication'],
  '12 min read',
  '2026-03-24',
  'Neel Guha',
  'https://neelguha.github.io/blog/2026/templates/',
  'assets/img/covers/real/neel-guha-templates-for-ml-research-papers.png',
  'Templates for Machine Learning Research Papers blog page',
  'cover',
  'published',
  false
),
(
  'google-brain-approach-to-research',
  'The Google Brain Team''s Approach to Research',
  'Jeff Dean explains how Google Brain balanced a portfolio spanning basic research, applied collaborations, and infrastructure like TensorFlow, and why the team published openly while embedding in products. It is a window into industrial-lab research strategy circa 2017 — before the LLM era reorganized priorities — and an institutional statement as much as personal advice.',
  'Jeff Dean',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'How to Research',
  array['Industrial Research','Research Portfolio','Long-term Research','Google Brain'],
  '9 min read',
  '2017-09-13',
  'Google Research',
  'https://research.google/blog/the-google-brain-teams-approach-to-research/',
  'assets/img/covers/real/google-brain-approach-to-research.jpg',
  'Google Brain approach to research article cover',
  'cover',
  'published',
  false
),
(
  'msr-first-accomplishment-in-nlp',
  'How to Make a First Accomplishment in the NLP Field',
  'Ming Zhou of Microsoft Research Asia maps how a newcomer earns a first real result in NLP: master the task taxonomy, reproduce a strong baseline, then find the delta a top venue will accept, while building relationships in the research community. Written in 2017, its landscape is statistical-plus-early-neural NLP, before large language models rearranged the field.',
  'Ming Zhou',
  'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
  'How to Research',
  array['NLP','Early Career','Baselines','Research Community'],
  '10 min read',
  '2017-12-04',
  'Microsoft Research Asia',
  'https://www.microsoft.com/en-us/research/articles/make-first-accomplishment-nlp-field/',
  'assets/img/covers/real/msr-first-accomplishment-in-nlp.jpg',
  'How to Make a First Accomplishment in the NLP Field article cover',
  'cover',
  'published',
  false
),
(
  'distill-research-debt',
  'Research Debt',
  'Chris Olah and Shan Carter name the phenomenon that makes fields harder to enter every year: research debt, the accumulated poor exposition, undigested ideas, and noise each new reader must repay. They argue distillation is real research and deserves careers, which Distill itself tried to institutionalize — a bet that, as the journal''s later hiatus showed, remains unfinished.',
  'Chris Olah and Shan Carter',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'How to Research',
  array['Research Distillation','Exposition','Interpretive Labor','Scientific Communication'],
  '11 min read',
  '2017-03-22',
  'Distill',
  'https://distill.pub/2017/research-debt/',
  'assets/img/covers/real/distill-research-debt.jpg',
  'Research Debt article cover',
  'cover',
  'published',
  false
),
(
  'distill-communicating-with-interactive-articles',
  'Communicating with Interactive Articles',
  'Fred Hohman and coauthors synthesize what interactive articles can do that static papers cannot: engage readers through play, expose models for direct manipulation, and layer explanations for multiple audiences. They ground each claim in examples from journalism, education, and visualization research. Building such artifacts remains costly, which the authors acknowledge as the central adoption barrier.',
  'Fred Hohman, Matthew Conlen, Jeffrey Heer, and Duen Horng Chau',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'How to Research',
  array['Interactive Articles','Scientific Communication','Visualization','Explorable Explanations'],
  '35 min read',
  '2020-09-11',
  'Distill',
  'https://distill.pub/2020/communicating-with-interactive-articles/',
  'assets/img/covers/real/distill-communicating-with-interactive-articles.jpg',
  'Communicating with Interactive Articles cover',
  'cover',
  'published',
  false
),
(
  'karpathy-survival-guide-to-a-phd',
  'A Survival Guide to a PhD',
  'Andrej Karpathy''s survival guide covers the full PhD arc: whether to enroll at all, picking problems with room to compound, structuring papers, giving talks, and managing the psychological middle years. It is grounded in his Stanford vision and ML experience in 2016, so its industry-versus-academia calculus predates today''s frontier-lab hiring market.',
  'Andrej Karpathy',
  'https://www.google.com/s2/favicons?domain=karpathy.github.io&sz=128',
  'How to Research',
  array['PhD Survival','Topic Selection','Paper Writing','Academic Career'],
  '35 min read',
  '2016-09-07',
  'Andrej Karpathy',
  'https://karpathy.github.io/2016/09/07/phd/',
  'assets/img/covers/real/karpathy-survival-guide-to-a-phd.png',
  'A Survival Guide to a PhD blog page',
  'cover',
  'published',
  false
),
(
  'john-schulman-opinionated-guide-to-ml-research',
  'An Opinionated Guide to ML Research',
  'John Schulman divides ML research into idea-driven and goal-driven modes and argues most people should pick ambitious goals, then continually reassess the gap. He prescribes reimplementing important papers, keeping a research notebook, and budgeting time between exploration and execution. It was written from his OpenAI reinforcement-learning vantage point for the 2017 Fellows program.',
  'John Schulman',
  'https://www.google.com/s2/favicons?domain=joschu.net&sz=128',
  'How to Research',
  array['ML Research','Goal-driven Research','Research Taste','Reimplementation'],
  '18 min read',
  '2020-01-24',
  'John Schulman',
  'http://joschu.net/blog/opinionated-guide-ml-research.html',
  'assets/img/covers/real/john-schulman-opinionated-guide-to-ml-research.png',
  'An Opinionated Guide to ML Research blog page',
  'cover',
  'published',
  false
),
(
  'markus-heinonen-advice-for-ml-phd-students',
  'Advice for Machine Learning PhD Students',
  'Markus Heinonen reduces the ML PhD to three trainable fundamentals — understanding, expressing, and implementing ideas — and builds concrete weekly practices around each: simplify the problem until it fits in one plot, iterate small, and write constantly. The advice reflects supervising doctoral students at Aalto in a European, methods-focused ML tradition.',
  'Markus Heinonen',
  'https://www.google.com/s2/favicons?domain=markusheinonen.github.io&sz=128',
  'How to Research',
  array['ML PhD','Fundamentals','Simplification','Research Cadence'],
  '12 min read',
  '2025-01-01',
  'Markus Heinonen',
  'https://markusheinonen.github.io/advice.html',
  'assets/img/covers/real/markus-heinonen-advice-for-ml-phd-students.png',
  'Advice for Machine Learning PhD Students page',
  'cover',
  'published',
  false
),
(
  'stanford-engineering-pick-and-solve-next-great-problem',
  'How to Pick — and Solve — the Next Great Problem',
  'Stanford''s Michael Fischbach teaches problem selection as an explicit skill: work backward from what would matter if true, use decision trees to expose hidden assumptions, and kill projects whose best case is boring. This is a university article distilling his course rather than a first-person essay, and its examples come from bioengineering.',
  'Stanford Engineering (on Michael Fischbach)',
  'https://www.google.com/s2/favicons?domain=engineering.stanford.edu&sz=128',
  'How to Research',
  array['Problem Selection','Decision Trees','Research Ambition','Bioengineering'],
  '6 min read',
  '2024-10-23',
  'Stanford Engineering',
  'https://engineering.stanford.edu/news/how-pick-and-solve-next-great-problem',
  'assets/img/covers/real/stanford-engineering-pick-and-solve-next-great-problem.jpg',
  'How to Pick and Solve the Next Great Problem article cover',
  'cover',
  'published',
  false
),
(
  'eugene-yan-choosing-problems-in-ds-ml',
  'Choosing Problems in Data Science and Machine Learning',
  'Eugene Yan turns problem selection in industry data science into an explicit rubric: score candidate projects on reach, severity, cost-benefit, fit with team capability, and learning value, then sequence them as a portfolio. The frame is applied ML inside product organizations — closer to prioritizing roadmaps than to open-ended academic inquiry.',
  'Eugene Yan',
  'https://www.google.com/s2/favicons?domain=eugeneyan.com&sz=128',
  'How to Research',
  array['Problem Prioritization','Applied ML','Impact Estimation','Industry Data Science'],
  '12 min read',
  '2021-03-21',
  'Eugene Yan',
  'https://eugeneyan.com/writing/how-to-choose-problems/',
  'assets/img/covers/real/eugene-yan-choosing-problems-in-ds-ml.jpg',
  'Choosing Problems in Data Science and Machine Learning article cover',
  'cover',
  'published',
  false
),
(
  'david-patterson-how-to-have-a-bad-career',
  'How to Have a Bad Career in Research/Academia',
  'David Patterson''s famous talk inverts career advice: to have a bad career, let complexity be your guide, never be proven wrong, and avoid feedback — then flips to the real recommendations on picking projects with impact and moving ideas into practice. The slides target new systems faculty at US research universities, and this version dates from 2001.',
  'David Patterson',
  'https://www.google.com/s2/favicons?domain=eecs.berkeley.edu&sz=128',
  'How to Research',
  array['Career Anti-patterns','Technology Transfer','Academic Career','Computer Systems'],
  '15 min read',
  '2001-12-10',
  'UC Berkeley EECS',
  'https://people.eecs.berkeley.edu/~pattrsn/talks/BadCareer.pdf',
  'assets/img/covers/real/david-patterson-how-to-have-a-bad-career.png',
  'First slide of How to Have a Bad Career in Research/Academia',
  'cover',
  'published',
  false
),
(
  'matt-might-phd-thesis-proposal-is-a-contract',
  'A Ph.D. Thesis Proposal Is a Contract',
  'Matt Might reframes the thesis proposal as a contract: a falsifiable claim plus the evidence the committee agrees will validate it, so the defense becomes checking terms instead of relitigating scope. He gives a template thesis statement and warns against proposals that promise systems instead of claims. The advice assumes CS programs with US-style committees.',
  'Matt Might',
  'https://www.google.com/s2/favicons?domain=matt.might.net&sz=128',
  'How to Research',
  array['Thesis Proposal','Committee Management','PhD Milestones','Dissertation'],
  '6 min read',
  '2010-01-01',
  'matt.might.net',
  'https://matt.might.net/articles/advice-for-phd-thesis-proposals/',
  'assets/img/covers/real/matt-might-phd-thesis-proposal-is-a-contract.png',
  'A PhD Thesis Proposal Is a Contract article page',
  'cover',
  'published',
  false
),
(
  'terence-tao-take-the-initiative',
  'Take the Initiative',
  'Terence Tao urges researchers to stop waiting for assigned problems: read beyond the syllabus, ask questions of the literature, and manufacture your own projects from gaps you notice. Initiative, he argues, is what converts training into a research career. As with his other career-advice pages, the examples assume academic mathematics.',
  'Terence Tao',
  'https://www.google.com/s2/favicons?domain=terrytao.wordpress.com&sz=128',
  'How to Research',
  array['Research Initiative','Self-Direction','Career Development','Mathematics'],
  '5 min read',
  '2007-01-01',
  'Terence Tao',
  'https://terrytao.wordpress.com/career-advice/take-the-initiative/',
  'assets/img/covers/real/terence-tao-take-the-initiative.png',
  'Take the Initiative career advice page',
  'cover',
  'published',
  false
),
(
  'patrick-kidger-just-know-stuff',
  'Just Know Stuff',
  'Patrick Kidger''s thesis from a fast Oxford maths PhD is that ML research success mostly means just knowing stuff, and he provides the literal checklist: autodiff internals, numerical methods, software engineering, statistics, and the craft of writing libraries people use. The list is opinionated, calibrated to 2023 ML tooling, and assumes a mathematically strong reader.',
  'Patrick Kidger',
  'https://www.google.com/s2/favicons?domain=kidger.site&sz=128',
  'How to Research',
  array['ML PhD','Technical Fundamentals','Software Craft','Skill Checklist'],
  '15 min read',
  '2023-01-26',
  'Patrick Kidger',
  'https://kidger.site/thoughts/just-know-stuff/',
  'assets/img/covers/real/patrick-kidger-just-know-stuff.png',
  'Just Know Stuff essay page',
  'cover',
  'published',
  false
),
(
  'jacob-steinhardt-advice-for-authors',
  'Advice for Authors',
  'Distilled from reviewing batches of ICML submissions, Steinhardt''s advice concentrates on local writing style: be precise to maximize information content, prefer concrete claims over vague ones, and treat sentence-level clarity as more important than global structure. It is a compact reviewer''s checklist rather than a full guide to composing a research paper.',
  'Jacob Steinhardt',
  'https://www.google.com/s2/favicons?domain=jsteinhardt.stat.berkeley.edu&sz=128',
  'How to Research',
  array['Paper Writing','Scientific Writing','Peer Review','Machine Learning'],
  '8 min read',
  '2017-02-28',
  'Jacob Steinhardt',
  'https://jsteinhardt.stat.berkeley.edu/blog/advice-for-authors',
  'assets/img/covers/cover-research-adjudication.svg',
  'Thematic research writing and review cover',
  'cover',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;

select id, title, category, publish_date, status
from public.blogs
where id in (
  'chapman-how-to-do-research-at-mit-ai-lab',
  'jacob-steinhardt-film-study-for-research',
  'hamming-you-and-your-research',
  'michael-nielsen-principles-of-effective-research',
  'keshav-how-to-read-a-paper',
  'stearns-some-modest-advice-for-graduate-students',
  'terence-tao-learn-and-relearn-your-field',
  'terence-tao-on-the-importance-of-partial-progress',
  'azuma-so-long-and-thanks-for-the-phd',
  'matt-might-illustrated-guide-to-a-phd',
  'chris-olah-research-taste-exercises',
  'nick-feamster-cultivating-your-research-taste',
  'john-regehr-picking-a-research-topic-in-computer-systems',
  'jason-eisner-how-to-find-research-problems',
  'noah-smith-grad-school-advice',
  'simon-peyton-jones-how-to-write-a-great-research-proposal',
  'simon-peyton-jones-how-to-give-a-good-research-talk',
  'cs-grad-job-and-interview-guide',
  'visionbook-how-to-do-research',
  'visionbook-how-to-write-papers',
  'visionbook-how-to-give-talks',
  'stanford-cs-phd-advising-guide',
  'mor-harchol-balter-applying-to-phd-programs-in-cs',
  'umd-choosing-a-research-advisor',
  'jason-wei-practicing-ai-research',
  'neel-guha-templates-for-ml-research-papers',
  'google-brain-approach-to-research',
  'msr-first-accomplishment-in-nlp',
  'distill-research-debt',
  'distill-communicating-with-interactive-articles',
  'karpathy-survival-guide-to-a-phd',
  'john-schulman-opinionated-guide-to-ml-research',
  'markus-heinonen-advice-for-ml-phd-students',
  'stanford-engineering-pick-and-solve-next-great-problem',
  'eugene-yan-choosing-problems-in-ds-ml',
  'david-patterson-how-to-have-a-bad-career',
  'matt-might-phd-thesis-proposal-is-a-contract',
  'terence-tao-take-the-initiative',
  'patrick-kidger-just-know-stuff',
  'jacob-steinhardt-advice-for-authors'
)
order by publish_date desc, id asc;
