-- Add the 2026-08-25 round-2 Efficient AI, Trustworthy AI, and Frontier blog additions to Supabase.
-- Mirrors the static corpus entries added to getRound2EffTrustFrontierBlogs() in site/assets/js/app.js.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('epoch-ai-how-much-does-it-cost-to-train-frontier-ai-models', 'How Much Does It Cost to Train Frontier AI Models?', 'Epoch AI estimates the amortized hardware and energy cost of frontier training runs, finding it has grown around 2.4x per year since 2016 and projecting billion-dollar runs if the trend holds. The figures are reconstructions from chip counts, run durations, and power draw, with wide uncertainty bands, and they deliberately exclude staff and the experiments behind each flagship run.', 'Ben Cottier, Robi Rahman, et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Training Costs','Compute Trends','Frontier Models','Forecasting'], '14 min read', '2024-06-03', 'Epoch AI', 'https://epoch.ai/publications/how-much-does-it-cost-to-train-frontier-ai-models', 'assets/img/covers/real/epoch-ai-how-much-does-it-cost-to-train-frontier-ai-models.png', 'Epoch AI frontier training cost report banner chart', 'cover', 'published', false),
('epoch-ai-algorithmic-progress-in-language-models', 'Algorithmic Progress in Language Models', 'Analyzing over 200 language-model evaluations from 2012 to 2023, Epoch AI estimates that the compute needed to reach a fixed performance level halves roughly every eight months — faster than Moore’s law — while most realized capability gains still came from scaling compute itself. The estimate covers pre-training perplexity benchmarks only, so post-training advances like RLHF and tool use sit outside it.', 'Anson Ho, Tamay Besiroglu, Ege Erdil, et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Algorithmic Progress','Scaling','Compute Efficiency','Trends'], '12 min read', '2024-03-12', 'Epoch AI', 'https://epoch.ai/publications/algorithmic-progress-in-language-models', 'assets/img/covers/real/epoch-ai-algorithmic-progress-in-language-models.png', 'Epoch AI algorithmic progress report banner chart', 'cover', 'published', false),
('epoch-ai-will-we-run-out-of-data', 'Will We Run Out of Data? Limits of LLM Scaling Based on Human-Generated Data', 'Epoch AI sizes the effective stock of public human-generated text at roughly 300 trillion tokens and projects that frontier training could fully utilize it sometime between 2026 and 2032, depending on overtraining and multi-epoch practices. The bottleneck analysis is deliberately narrow: synthetic data, multimodal corpora, and private data could each loosen the constraint substantially.', 'Pablo Villalobos, Anson Ho, Jaime Sevilla, et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Data Scaling','Training Data','Scaling Limits','Forecasting'], '15 min read', '2024-06-06', 'Epoch AI', 'https://epoch.ai/publications/will-we-run-out-of-data-limits-of-llm-scaling-based-on-human-generated-data', 'assets/img/covers/real/epoch-ai-will-we-run-out-of-data.png', 'Epoch AI data stock projection banner chart', 'cover', 'published', false),
('metr-early-2025-ai-developer-productivity-rct', 'Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity', 'METR ran a randomized controlled trial with 16 experienced open-source developers across 246 real tasks and found that allowing early-2025 AI tools made developers 19% slower — even as the developers themselves believed the AI had sped them up by about 20%. The authors are explicit that the setting is unusually unfavorable to AI (mature repositories the developers know deeply), so the result bounds a specific regime rather than condemning AI coding tools in general.', 'Joel Becker, Nate Rush, Beth Barnes, David Rein', 'https://www.google.com/s2/favicons?domain=metr.org&sz=128', 'Frontier', array['RCT','Developer Productivity','AI Coding Tools','Measurement'], '18 min read', '2025-07-10', 'METR Blog', 'https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/', 'assets/img/covers/real/metr-early-2025-ai-developer-productivity-rct.png', 'METR forecasted versus observed speedup chart from the developer productivity RCT', 'cover', 'published', false),
('deepmind-ai-solves-imo-problems-at-silver-medal-level', 'AI Achieves Silver-Medal Standard Solving International Mathematical Olympiad Problems', 'DeepMind’s AlphaProof, a reinforcement-learning system that writes formal proofs in Lean, and AlphaGeometry 2 together solved four of the six 2024 IMO problems for 28 of 42 points — the first AI result at silver-medal standard. Two important asterisks: humans first translated the problems into formal language, and some solutions took days of compute rather than the contest’s two 4.5-hour sessions.', 'AlphaProof and AlphaGeometry teams', 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128', 'Frontier', array['AlphaProof','Formal Reasoning','Mathematics','Lean'], '10 min read', '2024-07-25', 'Google DeepMind Blog', 'https://deepmind.google/blog/ai-solves-imo-problems-at-silver-medal-level/', 'assets/img/covers/real/deepmind-ai-solves-imo-problems-at-silver-medal-level.webp', 'DeepMind IMO silver medal announcement cover art', 'cover', 'published', false),
('uk-aisi-predeployment-evaluation-claude-3-5-sonnet', 'Pre-Deployment Evaluation of Anthropic’s Upgraded Claude 3.5 Sonnet', 'The first joint pre-deployment evaluation by the UK and US AI Safety Institutes tested the upgraded Claude 3.5 Sonnet on cyber, biological, and software capabilities and on safeguard robustness, finding that built-in refusal safeguards could be routinely circumvented. The institutes stress the exercise’s limits — a short evaluation window and a narrow capability slice — and frame it as evidence-gathering, not a safety certification.', 'UK AISI and US AISI', 'https://www.google.com/s2/favicons?domain=aisi.gov.uk&sz=128', 'Frontier', array['Pre-Deployment Evaluation','Frontier Models','Safeguards','Government Evals'], '11 min read', '2024-11-19', 'UK AISI Blog', 'https://www.aisi.gov.uk/blog/pre-deployment-evaluation-of-anthropics-upgraded-claude-3-5-sonnet', 'assets/img/covers/real/uk-aisi-predeployment-evaluation-claude-3-5-sonnet.png', 'UK AISI pre-deployment evaluation article cover', 'cover', 'published', false),
('deepmind-chinchilla-compute-optimal-training', 'An Empirical Analysis of Compute-Optimal Large Language Model Training', 'The Chinchilla study trained over 400 models to show that parameters and training tokens should scale in roughly equal proportion, and that a 70B model trained on 4x more data outperforms the 4x-larger Gopher across benchmarks. Its prescription targets pre-training loss per unit of training compute; once inference costs dominate, over-training smaller models past the Chinchilla point is often the economically better choice.', 'Jordan Hoffmann, Sebastian Borgeaud, et al.', 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128', 'Efficient AI', array['Chinchilla','Scaling Laws','Compute-Optimal Training','LLM Training'], '9 min read', '2022-04-12', 'Google DeepMind Blog', 'https://deepmind.google/blog/an-empirical-analysis-of-compute-optimal-large-language-model-training/', 'assets/img/covers/real/deepmind-chinchilla-compute-optimal-training.webp', 'DeepMind compute-optimal training blog cover art', 'cover', 'published', false),
('tim-dettmers-llm-int8-emergent-features', 'LLM.int8() and Emergent Features', 'Tim Dettmers explains LLM.int8(): vector-wise 8-bit quantization plus a mixed-precision path for the outlier features that emerge systematically around the 6.7B-parameter scale, enabling degradation-free inference of 175B models on consumer-accessible hardware. The emergent-outlier analysis outlived the specific kernels — the post predates today’s 4-bit methods, and its speed numbers no longer reflect current implementations.', 'Tim Dettmers', 'https://www.google.com/s2/favicons?domain=timdettmers.com&sz=128', 'Efficient AI', array['Quantization','int8','Outlier Features','Inference'], '16 min read', '2022-08-17', 'timdettmers.com', 'https://timdettmers.com/2022/08/17/llm-int8-and-emergent-features/', 'assets/img/covers/real/tim-dettmers-llm-int8-emergent-features.png', 'LLM.int8() zero-shot accuracy versus scale chart', 'cover', 'published', false),
('character-ai-optimizing-inference', 'Optimizing AI Inference at Character.AI', 'Character.AI details how multi-query attention, hybrid local-global attention layers, and cross-layer KV sharing shrink the KV cache by more than 20x, and how int8 quantization-aware training and a 95%-hit-rate session cache support serving over 20,000 queries per second. The reported 33x cost reduction is self-measured and specific to their consumer chat workload, where long persistent conversations make cache reuse unusually effective.', 'Character.AI', 'https://www.google.com/s2/favicons?domain=character.ai&sz=128', 'Efficient AI', array['Inference Serving','KV Cache','Multi-Query Attention','Quantization'], '9 min read', '2024-06-20', 'Character.AI Blog', 'https://blog.character.ai/optimizing-ai-inference-at-character-ai/', 'assets/img/covers/real/character-ai-optimizing-inference.png', 'Character.AI inference optimization blog cover', 'cover', 'published', false),
('anthropic-towards-monosemanticity', 'Towards Monosemanticity: Decomposing Language Models With Dictionary Learning', 'Anthropic uses sparse autoencoders to decompose a transformer’s polysemantic neuron activations into thousands of far more interpretable features — Arabic script, DNA sequences, base64 strings — providing the first strong evidence that dictionary learning can unpick superposition. The demonstration is on a one-layer toy model; scaling the technique to frontier models became its own research program in the follow-up work.', 'Trenton Bricken, Adly Templeton, Joshua Batson, et al.', 'https://www.google.com/s2/favicons?domain=transformer-circuits.pub&sz=128', 'Trustworthy AI', array['Sparse Autoencoders','Superposition','Mechanistic Interpretability','Features'], '60 min read', '2023-10-04', 'Transformer Circuits', 'https://transformer-circuits.pub/2023/monosemantic-features/index.html', 'assets/img/covers/real/anthropic-towards-monosemanticity.png', 'Real cover from Transformer Circuits page screenshot: Towards Monosemanticity title card', 'cover', 'published', false),
('anthropic-constitutional-ai-harmlessness', 'Constitutional AI: Harmlessness from AI Feedback', 'Anthropic trains a harmless assistant by having the model critique and revise its own outputs against a written constitution, then applying RL from AI feedback — replacing human harmfulness labels and producing less evasive, more transparent refusals. The method still depends on human helpfulness labels, and choosing the constitution itself remains a normative decision the technique cannot settle.', 'Anthropic', 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128', 'Trustworthy AI', array['Constitutional AI','RLAIF','Harmlessness','Alignment'], '14 min read', '2022-12-15', 'Anthropic Research', 'https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback', 'assets/img/covers/real/anthropic-constitutional-ai-harmlessness.jpg', 'Constitutional AI research page cover', 'cover', 'published', false),
('deepmind-taking-a-responsible-path-to-agi', 'Taking a Responsible Path to AGI', 'Google DeepMind summarizes its AGI safety approach — organized around misuse and misalignment, with amplified oversight, access controls, interpretability, and an internal AGI Safety Council — and argues transformative capabilities are plausible within a few years. It is a strategy document accompanying a 100+ page technical paper: the timelines are contested, and the plan presumes the current training paradigm continues to hold.', 'Google DeepMind', 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128', 'Trustworthy AI', array['AGI Safety','Misalignment','Frontier Safety','Governance'], '9 min read', '2025-04-02', 'Google DeepMind Blog', 'https://deepmind.google/blog/taking-a-responsible-path-to-agi/', 'assets/img/covers/real/deepmind-taking-a-responsible-path-to-agi.webp', 'DeepMind responsible path to AGI blog cover art', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
