-- Add the eighteen 2026-08-25 Foundation Model / LLM & MLLM / Multimodal Model blog additions to Supabase.
-- Mirrors the entries inserted into getRecentCommunityBlogAdditions() in site/assets/js/app.js.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('giux78-joy-pain-training-llm-from-scratch', 'The Joy and Pain of Training an LLM from Scratch', 'Alessandro Ercolani documents the full pipeline behind the Zagreus and Nesso small language model families, from framework selection with Nanotron through tokenizer data engineering and Slurm-driven pretraining to multilingual evaluation, with honest notes on what broke along the way.', 'Alessandro Ercolani', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'Foundation Model', array['Small Language Models','Pretraining','Nanotron','Multilingual','Training Report'], '25 min read', '2026-04-02', 'Hugging Face Blog', 'https://huggingface.co/blog/giux78/slm-zagreus-nesso', 'assets/img/covers/real/giux78-joy-pain-training-llm-from-scratch.png', 'Zagreus and Nesso training report cover', 'cover', 'published', false),
('openai-techniques-training-large-neural-networks', 'Techniques for Training Large Neural Networks', 'OpenAI walks through the parallelism toolbox for training large models, explaining how data, pipeline, tensor, and expert parallelism each split computation across GPUs, where the communication costs land, and which memory-saving tricks make the pieces fit.', 'Lilian Weng and Justin Jay Wang', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Foundation Model', array['Distributed Training','Data Parallelism','Pipeline Parallelism','Tensor Parallelism','Mixture of Experts'], '10 min read', '2022-06-09', 'OpenAI', 'https://openai.com/index/techniques-for-training-large-neural-networks/', 'assets/img/covers/real/openai-techniques-training-large-neural-networks.webp', 'Parallelism techniques diagram from OpenAI', 'cover', 'published', false),
('ai2-dolma-3-trillion-token-open-corpus', 'Dolma: 3 Trillion Token Open Corpus for Language Model Pretraining', 'Ai2 explains how it assembled Dolma, a 3-trillion-token openly licensed pretraining corpus, walking through source selection, language and quality filtering, deduplication, and toxicity decisions, and releases the toolkit so the pipeline can be audited or remixed.', 'Luca Soldaini', 'https://www.google.com/s2/favicons?domain=allenai.org&sz=128', 'Foundation Model', array['Pretraining Data','Open Corpus','Data Curation','Deduplication'], '12 min read', '2023-08-18', 'Ai2 Blog', 'https://allenai.org/blog/dolma-3-trillion-tokens-open-llm-corpus-9a0ff4b8da64', 'assets/img/covers/real/ai2-dolma-3-trillion-token-open-corpus.jpg', 'Dolma open pretraining corpus cover', 'cover', 'published', false),
('apple-third-generation-foundation-models', 'Introducing the Third Generation of Apple''s Foundation Models', 'Apple details its third-generation foundation model family: a 3B dense on-device model, a 20B sparse on-device model that activates only 1-4B parameters per request, and three server models on Private Cloud Compute, with privacy-preserving deployment as a first-class design constraint.', 'Apple Machine Learning Research', 'https://www.google.com/s2/favicons?domain=machinelearning.apple.com&sz=128', 'Foundation Model', array['Apple Foundation Models','On-Device AI','Sparse Models','Private Cloud Compute'], '11 min read', '2026-06-08', 'Apple Machine Learning Research', 'https://machinelearning.apple.com/research/introducing-third-generation-of-apple-foundation-models', 'assets/img/covers/real/apple-third-generation-foundation-models.png', 'Apple Foundation Models third generation hero image', 'cover', 'published', false),
('google-multi-token-prediction-gemma-4', 'Accelerating Gemma 4: Faster Inference with Multi-Token Prediction Drafters', 'Google engineers explain how Multi-Token Prediction drafters give Gemma 4 up to a 3x decoding speedup through a specialized speculative decoding architecture, covering why standard LLM inference is memory-bandwidth bound and how draft-and-verify preserves output quality.', 'Olivier Lacombe and Maarten Grootendorst', 'https://www.google.com/s2/favicons?domain=blog.google&sz=128', 'Foundation Model', array['Gemma 4','Multi-Token Prediction','Speculative Decoding','Inference'], '8 min read', '2026-05-05', 'Google Blog', 'https://blog.google/innovation-and-ai/technology/developers-tools/multi-token-prediction-gemma-4/', 'assets/img/covers/real/google-multi-token-prediction-gemma-4.png', 'Gemma 4 multi-token prediction cover', 'cover', 'published', false),
('hazyresearch-structured-state-spaces-s4', 'Structured State Spaces: Combining Continuous-Time, Recurrent, and Convolutional Models', 'Albert Gu, Karan Goel, and Chris Re unpack the S4 architecture, showing how one state space model can be computed as a continuous-time system, a recurrence, or a convolution, and why switching between the three views unlocks efficient long-range sequence modeling.', 'Albert Gu, Karan Goel, and Chris Re', 'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128', 'Foundation Model', array['State Space Models','S4','Long-Range Dependencies','Sequence Modeling'], '15 min read', '2022-01-14', 'Stanford Hazy Research', 'https://hazyresearch.stanford.edu/blog/2022-01-14-s4-3', 'assets/img/covers/real/hazyresearch-structured-state-spaces-s4.png', 'State space model diagram from the S4 blog', 'cover', 'published', false),
('openai-learning-to-reason-with-llms', 'Learning to Reason with LLMs', 'OpenAI describes how o1 was trained with large-scale reinforcement learning to produce a private chain of thought before answering, and shows accuracy climbing smoothly with both train-time and test-time compute across competition math, coding, and science benchmarks.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'LLM & MLLM', array['Reasoning','Reinforcement Learning','Chain of Thought','Test-Time Compute','o1'], '12 min read', '2024-09-12', 'OpenAI', 'https://openai.com/index/learning-to-reason-with-llms/', 'assets/img/covers/real/openai-learning-to-reason-with-llms.png', 'OpenAI o1 reasoning article cover', 'cover', 'published', false),
('minimax-maxproof-math-proof-evolution', 'MaxProof: Scaling Mathematical Proof with Generative-Verifier RL and Evolutionary Search', 'MiniMax details the framework that pushed its M3 model past the human gold-medal threshold on IMO 2025 and USAMO 2026, combining a stronger base prover, an aligned generative verifier, refinement training, and evolutionary search at test time.', 'MiniMax', 'https://www.google.com/s2/favicons?domain=minimax.io&sz=128', 'LLM & MLLM', array['Theorem Proving','Generative Verifier','Reinforcement Learning','Test-Time Scaling'], '14 min read', '2026-06-09', 'MiniMax Research', 'https://www.minimax.io/blog/minimax-maxproof-math-proof-evolution', 'assets/img/covers/real/minimax-maxproof-math-proof-evolution.png', 'MaxProof mathematical proof framework cover', 'cover', 'published', false),
('jalammar-illustrated-retrieval-transformer', 'The Illustrated Retrieval Transformer', 'Jay Alammar visualizes DeepMind''s RETRO, explaining step by step how a 7.5B-parameter model backed by a trillion-token retrieval database can match far larger models by separating world-knowledge lookup from language modeling.', 'Jay Alammar', 'https://www.google.com/s2/favicons?domain=jalammar.github.io&sz=128', 'LLM & MLLM', array['RETRO','Retrieval-Augmented Generation','Retrieval','Transformers'], '10 min read', '2022-01-03', 'Jay Alammar', 'https://jalammar.github.io/illustrated-retrieval-transformer/', 'assets/img/covers/real/jalammar-illustrated-retrieval-transformer.png', 'RETRO retrieval transformer illustration', 'cover', 'published', false),
('jalammar-illustrated-transformer', 'The Illustrated Transformer', 'The canonical visual walkthrough of the Transformer, building up self-attention, multi-head attention, positional encoding, and the encoder-decoder stack one diagram at a time - still the fastest way to develop intuition for the architecture behind modern LLMs.', 'Jay Alammar', 'https://www.google.com/s2/favicons?domain=jalammar.github.io&sz=128', 'LLM & MLLM', array['Transformers','Self-Attention','Architecture','Visualization'], '18 min read', '2018-06-27', 'Jay Alammar', 'https://jalammar.github.io/illustrated-transformer/', 'assets/img/covers/real/jalammar-illustrated-transformer.png', 'Illustrated Transformer architecture diagram', 'cover', 'published', false),
('anthropic-mapping-mind-language-model', 'Mapping the Mind of a Large Language Model', 'Anthropic reports the first detailed look inside a production LLM, using sparse autoencoders to extract millions of interpretable features from Claude 3 Sonnet - including safety-relevant ones - and showing that amplifying or suppressing features causally changes behavior.', 'Anthropic', 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128', 'LLM & MLLM', array['Interpretability','Sparse Autoencoders','Features','Claude'], '12 min read', '2024-05-21', 'Anthropic', 'https://www.anthropic.com/research/mapping-mind-language-model', 'assets/img/covers/real/anthropic-mapping-mind-language-model.jpg', 'Vintage head diagrams representing concept mapping inside an AI model', 'cover', 'published', false),
('google-chain-of-thought-reasoning', 'Language Models Perform Reasoning via Chain of Thought', 'Jason Wei and Denny Zhou show that simply prompting large models to produce intermediate reasoning steps unlocks major gains on arithmetic, commonsense, and symbolic reasoning - and that chain-of-thought ability emerges only past a certain model scale.', 'Jason Wei and Denny Zhou', 'https://www.google.com/s2/favicons?domain=research.google&sz=128', 'LLM & MLLM', array['Chain of Thought','Prompting','Reasoning','Emergent Abilities'], '7 min read', '2022-05-11', 'Google Research Blog', 'https://research.google/blog/language-models-perform-reasoning-via-chain-of-thought/', 'assets/img/covers/real/google-chain-of-thought-reasoning.jpg', 'Chain-of-thought prompting illustration from Google Research', 'cover', 'published', false),
('hf-whats-going-on-open-llm-leaderboard', 'What''s Going On with the Open LLM Leaderboard?', 'Hugging Face''s evaluation team dissects why three implementations of the same MMLU benchmark give wildly different LLaMA scores, tracing the gaps to prompt formatting and log-likelihood versus generation-based scoring - a cautionary tale for anyone comparing eval numbers.', 'Clementine Fourrier, Nathan Habib, Julien Launay, and Thomas Wolf', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'LLM & MLLM', array['Evaluation','MMLU','Benchmarks','Reproducibility'], '13 min read', '2023-06-23', 'Hugging Face Blog', 'https://huggingface.co/blog/open-llm-leaderboard-mmlu', 'assets/img/covers/real/hf-whats-going-on-open-llm-leaderboard.png', 'Open LLM Leaderboard MMLU deep dive cover', 'cover', 'published', false),
('hf-illustrating-rlhf', 'Illustrating Reinforcement Learning from Human Feedback (RLHF)', 'Nathan Lambert and collaborators break RLHF into its three trainable stages - a base language model, a human-preference reward model, and PPO-based policy optimization - clarifying what each stage actually optimizes and where the open research problems sit.', 'Nathan Lambert, Louis Castricato, Leandro von Werra, and Alex Havrilla', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'LLM & MLLM', array['RLHF','Reward Models','PPO','Post-Training'], '11 min read', '2022-12-09', 'Hugging Face Blog', 'https://huggingface.co/blog/rlhf', 'assets/img/covers/real/hf-illustrating-rlhf.png', 'Illustrated RLHF training pipeline cover', 'cover', 'published', false),
('matteo-nulli-demystifying-multimodal-learning', 'Demystifying Multimodal Learning: Enabling Vision in Language Models', 'Matteo Nulli builds vision-language models up from first principles: the mathematical formulation, ViT-CLIP vision encoders, contrastive alignment of image and text embeddings, and the architectural flow that turns raw pixels into tokens an LLM can attend to.', 'Matteo Nulli', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'Multimodal Model', array['Vision-Language Models','CLIP','Contrastive Learning','Vision Encoders'], '14 min read', '2026-02-17', 'Hugging Face Blog', 'https://huggingface.co/blog/MatteoNulli/de-mystifying-multimodal-learning-enabiling-vision', 'assets/img/covers/real/matteo-nulli-demystifying-multimodal-learning.png', 'VLM architecture overview from the demystifying multimodal learning post', 'cover', 'published', false),
('lilian-weng-generalized-visual-language-models', 'Generalized Visual Language Models', 'Lilian Weng surveys four families of visually-augmented language models - joint training on image-text pairs, learned visual prefixes, cross-attention fusion, and frozen-LLM approaches - comparing how each injects vision into a text backbone and what it costs.', 'Lilian Weng', 'https://www.google.com/s2/favicons?domain=lilianweng.github.io&sz=128', 'Multimodal Model', array['Vision-Language Models','Multimodal','Image Captioning','Survey'], '20 min read', '2022-06-09', 'Lil''Log', 'https://lilianweng.github.io/posts/2022-06-09-vlm/', 'assets/img/covers/real/lilian-weng-generalized-visual-language-models.png', 'VisualBERT architecture diagram from Generalized Visual Language Models', 'cover', 'published', false),
('chip-huyen-multimodality-large-multimodal-models', 'Multimodality and Large Multimodal Models (LMMs)', 'Chip Huyen maps the large multimodal model landscape, working through CLIP''s contrastive pretraining and Flamingo''s vision-language fusion in detail, then cataloging the data, architecture, and training choices that separate today''s LMM systems.', 'Chip Huyen', 'https://www.google.com/s2/favicons?domain=huyenchip.com&sz=128', 'Multimodal Model', array['Large Multimodal Models','CLIP','Flamingo','Multimodal Systems'], '25 min read', '2023-10-10', 'Chip Huyen', 'https://huyenchip.com/2023/10/10/multimodal.html', 'assets/img/covers/real/chip-huyen-multimodality-large-multimodal-models.png', 'CLIP architecture diagram from the LMM overview', 'cover', 'published', false),
('hf-accelerating-document-ai', 'Accelerating Document AI', 'Rajiv Shah, Niels Rogge, and Nicholas Broad organize document AI into six practical use cases - from OCR and classification to layout analysis, document QA, and table extraction - matching each with open-source models like LayoutLM and Donut and the licensing realities practitioners face.', 'Rajiv Shah, Niels Rogge, and Nicholas Broad', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'Multimodal Model', array['Document AI','LayoutLM','OCR','Document QA'], '12 min read', '2022-11-21', 'Hugging Face Blog', 'https://huggingface.co/blog/document-ai', 'assets/img/covers/real/hf-accelerating-document-ai.png', 'Document AI use cases cover', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
