-- Add the 2026-08-25 Efficient AI, Trustworthy AI, and Frontier blog additions to Supabase.
-- Mirrors the static corpus entries added to getRecentCommunityBlogAdditions() in site/assets/js/app.js.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('lilianweng-large-transformer-model-inference-optimization', 'Large Transformer Model Inference Optimization', 'Lilian Weng maps the full toolbox for cheaper, faster transformer inference: knowledge distillation, quantization and the outlier problem in models past 6.7B parameters, structured pruning and sparsity, mixture-of-experts tricks, and architecture changes, all grounded in the memory and compute costs that make LLM serving hard.', 'Lilian Weng', 'https://www.google.com/s2/favicons?domain=lilianweng.github.io&sz=128', 'Efficient AI', array['Inference Optimization','Quantization','Distillation','Pruning','Sparsity'], '35 min read', '2023-01-10', 'Lil''Log', 'https://lilianweng.github.io/posts/2023-01-10-inference-optimization/', 'assets/img/covers/real/lilianweng-large-transformer-model-inference-optimization.png', 'Knowledge distillation teacher-student framework diagram from the post', 'cover', 'published', false),
('anyscale-continuous-batching-llm-inference', 'How Continuous Batching Enables 23x Throughput in LLM Inference While Reducing p50 Latency', 'The Anyscale team benchmarks static versus continuous batching for LLM serving, explaining how iteration-level scheduling lets new requests join a running batch as sequences finish, and measures up to 23x throughput gains with vLLM''s PagedAttention on top of the scheduling win.', 'Cade Daniel, Chen Shen, Eric Liang, and Richard Liaw', 'https://www.google.com/s2/favicons?domain=anyscale.com&sz=128', 'Efficient AI', array['Continuous Batching','LLM Serving','Throughput','vLLM'], '14 min read', '2023-06-22', 'Anyscale Blog', 'https://www.anyscale.com/blog/continuous-batching-llm-inference', 'assets/img/covers/real/anyscale-continuous-batching-llm-inference.png', 'Continuous batching for LLM inference article cover', 'cover', 'published', false),
('characterai-optimizing-ai-inference', 'Optimizing AI Inference at Character.AI', 'Character.AI explains how it serves over 20,000 inference queries per second: multi-query attention, hybrid local-global attention layers, cross-layer KV cache sharing, and native int8 quantization-aware training combine to shrink KV cache more than 20x and cut serving cost by a factor of 33 since launch.', 'Character.AI', 'https://www.google.com/s2/favicons?domain=research.character.ai&sz=128', 'Efficient AI', array['KV Cache','Multi-Query Attention','Int8 Quantization','LLM Serving'], '8 min read', '2024-06-20', 'Character.AI Research', 'https://research.character.ai/optimizing-inference/', 'assets/img/covers/real/characterai-optimizing-ai-inference.png', 'Character.AI research card artwork', 'cover', 'published', false),
('openai-weak-to-strong-generalization', 'Weak-to-Strong Generalization', 'OpenAI''s Superalignment team asks whether a weak supervisor can control a much stronger model, showing that GPT-4 supervised by a GPT-2-level teacher recovers most of the capability gap with a simple confidence-based auxiliary loss, and frames weak-to-strong generalization as a testable path to aligning superhuman models.', 'Collin Burns, Pavel Izmailov, Jan Leike, et al.', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Trustworthy AI', array['Superalignment','Weak-to-Strong','Scalable Oversight','Alignment Research'], '12 min read', '2023-12-14', 'OpenAI', 'https://openai.com/index/weak-to-strong-generalization/', 'assets/img/covers/real/openai-weak-to-strong-generalization.jpg', 'Weak-to-strong generalization announcement artwork', 'cover', 'published', false),
('anthropic-core-views-on-ai-safety', 'Core Views on AI Safety: When, Why, What, and How', 'Anthropic lays out the reasoning behind its safety strategy: why rapid AI progress makes safety urgent, a portfolio approach spanning optimistic, intermediate, and pessimistic scenarios, and how mechanistic interpretability, scalable oversight, and process-oriented learning fit together as empirical safety research directions.', 'Anthropic', 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128', 'Trustworthy AI', array['AI Safety','Safety Strategy','Scalable Oversight','Interpretability'], '25 min read', '2023-03-08', 'Anthropic', 'https://www.anthropic.com/news/core-views-on-ai-safety', 'assets/img/covers/real/anthropic-core-views-on-ai-safety.jpg', 'Anthropic core views on AI safety article cover', 'cover', 'published', false),
('openai-chain-of-thought-monitoring', 'Detecting Misbehavior in Frontier Reasoning Models', 'OpenAI shows that frontier reasoning models exploit loopholes in plain language inside their chain of thought, that a weaker LLM can monitor those thoughts to catch reward hacking in coding tasks, and that directly optimizing the chain of thought to look safe teaches models to hide intent rather than stop misbehaving.', 'Bowen Baker, Joost Huizinga, Leo Gao, et al.', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Trustworthy AI', array['Chain-of-Thought Monitoring','Reward Hacking','Reasoning Models','Frontier Safety'], '11 min read', '2025-03-10', 'OpenAI', 'https://openai.com/index/chain-of-thought-monitoring/', 'assets/img/covers/real/openai-chain-of-thought-monitoring.png', 'Chain-of-thought monitoring announcement artwork', 'cover', 'published', false),
('deepmind-funsearch-mathematical-discoveries', 'FunSearch: Making New Discoveries in Mathematical Sciences Using Large Language Models', 'Google DeepMind pairs an LLM that proposes programs with an automated evaluator in an evolutionary loop, producing the first LLM-driven discovery of new constructions for the cap set problem and better online bin-packing heuristics, with solutions output as inspectable code rather than opaque answers.', 'Alhussein Fawzi and Bernardino Romera-Paredes', 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128', 'Frontier', array['FunSearch','Mathematical Discovery','Program Search','LLM + Evolution'], '9 min read', '2023-12-14', 'Google DeepMind Blog', 'https://deepmind.google/discover/blog/funsearch-making-new-discoveries-in-mathematical-sciences-using-large-language-models/', 'assets/img/covers/real/deepmind-funsearch-mathematical-discoveries.webp', 'FunSearch announcement hero artwork', 'cover', 'published', false),
('sakana-ai-scientist', 'The AI Scientist: Towards Fully Automated Open-Ended Scientific Discovery', 'Sakana AI introduces The AI Scientist, a pipeline where frontier LLMs generate research ideas, write and run experiments, produce full papers, and review them with an automated reviewer at roughly $15 per paper, alongside a frank discussion of failure modes like unsafe code execution and reviewer gaming.', 'Sakana AI', 'https://www.google.com/s2/favicons?domain=sakana.ai&sz=128', 'Frontier', array['AI Scientist','Automated Discovery','Research Agents','Open-Endedness'], '15 min read', '2024-08-13', 'Sakana AI', 'https://sakana.ai/ai-scientist/', 'assets/img/covers/real/sakana-ai-scientist.jpeg', 'The AI Scientist illustrated cover artwork', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
