-- Add the quality Foundation Model, LLM & MLLM, and Multimodal Model canonical essays to Supabase.
-- Run this in the Supabase SQL Editor for the project backing the public site.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'mii-llm-zagreus-training-llm-from-scratch',
  'The Joy and Pain of Training an LLM from Scratch',
  'The mii-llm community documents training the 0.4B Zagreus models from scratch with Hugging Face Nanotron, covering framework selection, the tokenization pipeline, Slurm pretraining configs, and Axolotl post-training into the Nesso instruct models, with evaluations across Italian, Spanish, French, and Portuguese benchmarks. Findings come from 0.4B-parameter runs on a single sponsored cluster, so the recipe does not directly speak to larger-scale training.',
  'Alessandro Ercolani',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Foundation Model',
  array['Pretraining','Small Language Models','Nanotron','Multilingual'],
  '15 min read',
  '2026-04-02',
  'Hugging Face Blog',
  'https://huggingface.co/blog/giux78/slm-zagreus-nesso',
  'assets/img/covers/real/mii-llm-zagreus-training-llm-from-scratch.png',
  'Zagreus and Nesso small language model training cover',
  'cover',
  'published',
  false
),
(
  'openai-techniques-for-training-large-neural-networks',
  'Techniques for Training Large Neural Networks',
  'OpenAI surveys the parallelism toolkit behind large-model training: data, pipeline, and tensor parallelism, mixture-of-experts routing, and memory savers such as activation recomputation, CPU offloading, and mixed precision, explaining how gradient synchronization and pipeline bubbles limit scaling efficiency. It is a 2022 snapshot, so newer stacks like FSDP and modern MoE kernels are outside its scope.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Foundation Model',
  array['Distributed Training','Parallelism','Mixture of Experts','GPU Systems'],
  '11 min read',
  '2022-06-09',
  'OpenAI',
  'https://openai.com/index/techniques-for-training-large-neural-networks/',
  'assets/img/covers/real/openai-techniques-for-training-large-neural-networks.webp',
  'OpenAI large neural network training techniques cover',
  'cover',
  'published',
  false
),
(
  'ai2-dolma-3-trillion-token-open-corpus',
  'Dolma: 3 Trillion Token Open Corpus for Language Model Pretraining',
  'Ai2 releases Dolma, a 3-trillion-token pretraining corpus mixing web text, academic publications, code, books, and encyclopedic sources, and documents the curation goals, filtering decisions, and a datasheet alongside comparisons with the corpora behind closed and open models. Curation choices are tuned to the OLMo project, and the fuller technical report followed later.',
  'Ai2',
  'https://www.google.com/s2/favicons?domain=allenai.org&sz=128',
  'Foundation Model',
  array['Pretraining Data','Open Corpus','OLMo','Data Curation'],
  '12 min read',
  '2023-08-18',
  'Ai2 Blog',
  'https://allenai.org/blog/dolma-3-trillion-tokens-open-llm-corpus-9a0ff4b8da64',
  'assets/img/covers/real/ai2-dolma-3-trillion-token-open-corpus.jpg',
  'Dolma open pretraining corpus cover',
  'cover',
  'published',
  false
),
(
  'apple-third-generation-foundation-models',
  'Introducing the Third Generation of Apple’s Foundation Models',
  'Apple details AFM 3: a 3B dense on-device model, a natively multimodal 20B sparse on-device model that activates only 1–4B parameters per request, and three Private Cloud Compute server models, with sections on architectures for Apple silicon and training methodology. Most reported evaluations are Apple’s own, and the sparse on-device model requires the most capable Apple silicon systems.',
  'Apple Machine Learning Research',
  'https://www.google.com/s2/favicons?domain=machinelearning.apple.com&sz=128',
  'Foundation Model',
  array['On-Device AI','Sparse Models','Private Cloud Compute','Apple Silicon'],
  '14 min read',
  '2026-06-08',
  'Apple Machine Learning Research',
  'https://machinelearning.apple.com/research/introducing-third-generation-of-apple-foundation-models',
  'assets/img/covers/real/apple-third-generation-foundation-models.png',
  'Apple third-generation foundation models cover',
  'cover',
  'published',
  false
),
(
  'google-gemma-4-multi-token-prediction-drafters',
  'Accelerating Gemma 4: Faster Inference with Multi-Token Prediction Drafters',
  'Google releases multi-token prediction drafter models for the Gemma 4 family, a speculative-decoding setup where drafters reuse the target model’s activations and share its KV cache to propose several tokens that the target verifies in one forward pass, reporting up to 3x speedups with unchanged outputs. Gains are hardware- and batch-dependent: the 26B MoE model needs batch sizes of 4–8 to reach about 2.2x on Apple silicon.',
  'Olivier Lacombe, Maarten Grootendorst',
  'https://www.google.com/s2/favicons?domain=blog.google&sz=128',
  'Foundation Model',
  array['Gemma 4','Speculative Decoding','Multi-Token Prediction','Inference Efficiency'],
  '8 min read',
  '2026-05-05',
  'Google Blog',
  'https://blog.google/innovation-and-ai/technology/developers-tools/multi-token-prediction-gemma-4/',
  'assets/img/covers/real/google-gemma-4-multi-token-prediction-drafters.png',
  'Gemma 4 multi-token prediction drafters cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-structured-state-spaces-s4',
  'Structured State Spaces: Combining Continuous-Time, Recurrent, and Convolutional Models',
  'Hazy Research shows how the linear state space model x′(t) = Ax(t) + Bu(t) admits three equivalent views — continuous-time, recurrent, and convolutional — and how S4 switches between them for efficient training and inference, with discretization and HiPPO initialization providing long-range memory. The post predates selective SSMs like Mamba, so it reflects the first generation of structured state space models.',
  'Albert Gu, Karan Goel, Christopher Ré',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Foundation Model',
  array['State Space Models','S4','Long Sequences','Architecture'],
  '13 min read',
  '2022-01-14',
  'Stanford Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2022-01-14-s4-3',
  'assets/img/covers/real/hazyresearch-structured-state-spaces-s4.png',
  'Structured state space model views diagram',
  'contain',
  'published',
  false
),
(
  'hugging-face-moe-in-transformers',
  'Mixture of Experts (MoEs) in Transformers',
  'Hugging Face explains how MoE layers replace dense feed-forward blocks with routed experts, then walks through the engineering that makes them practical in the transformers library: weight conversion, lazy tensor materialization, faster weight loading, expert-parallel backends, and where quantization fits. A worked example predicts gpt-oss-20b decode speed from active parameters and memory bandwidth (~111 estimated vs ~115 measured tok/s on an M3 Ultra); benchmarks target the transformers stack rather than dedicated serving engines.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'LLM & MLLM',
  array['Mixture of Experts','Transformers Library','Expert Parallelism','Inference'],
  '14 min read',
  '2026-02-26',
  'Hugging Face Blog',
  'https://huggingface.co/blog/moe-transformers',
  'assets/img/covers/real/hugging-face-moe-in-transformers.png',
  'Mixture of experts in transformers cover',
  'cover',
  'published',
  false
),
(
  'openai-learning-to-reason-with-llms',
  'Learning to Reason with LLMs',
  'OpenAI introduces o1, trained with large-scale reinforcement learning to produce a long private chain of thought before answering, and shows accuracy climbing with both train-time RL compute and test-time thinking compute — reaching AIME qualifier scores among the top 500 US students and above-PhD accuracy on GPQA. The chain of thought is hidden from users, and the data and RL recipe are not disclosed, so results are hard to reproduce externally.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'LLM & MLLM',
  array['Reasoning','Reinforcement Learning','Test-Time Compute','o1'],
  '13 min read',
  '2024-09-12',
  'OpenAI',
  'https://openai.com/index/learning-to-reason-with-llms/',
  'assets/img/covers/real/openai-learning-to-reason-with-llms.png',
  'OpenAI o1 learning to reason cover',
  'cover',
  'published',
  false
),
(
  'minimax-maxproof-math-proof-evolution',
  'MaxProof: Scaling Mathematical Proof with Generative-Verifier RL and Evolutionary Search',
  'MiniMax trains three expert models — a proof generator via long-horizon RL, a verifier aligned through error-finding RL, and a repair model fine-tuned on flawed-proof and verification-analysis pairs — then merges them and applies MaxProof, an evolutionary test-time-scaling loop that converts best@K capability into a more stable pass@1. The post centers on training characteristics and system tradeoffs; evaluations focus on contest-style proofs and the evolutionary search consumes substantial inference compute.',
  'MiniMax',
  'https://www.google.com/s2/favicons?domain=minimax.io&sz=128',
  'LLM & MLLM',
  array['Mathematical Reasoning','Generative Verifier','Test-Time Scaling','Reinforcement Learning'],
  '16 min read',
  '2026-06-09',
  'MiniMax Research',
  'https://www.minimax.io/blog/minimax-maxproof-math-proof-evolution',
  'assets/img/covers/real/minimax-maxproof-math-proof-evolution.png',
  'MaxProof mathematical proof evolution cover',
  'cover',
  'published',
  false
),
(
  'illustrated-retrieval-transformer',
  'The Illustrated Retrieval Transformer',
  'Jay Alammar visually explains DeepMind’s RETRO, showing how a 7.5B-parameter model paired with a 2-trillion-token retrieval database can match far larger models by injecting nearest-neighbor text chunks through chunked cross-attention, separating world knowledge in the database from language ability in the parameters. It covers the mechanism at intuition level; training details and ablations live in the RETRO paper.',
  'Jay Alammar',
  'https://www.google.com/s2/favicons?domain=jalammar.github.io&sz=128',
  'LLM & MLLM',
  array['Retrieval Augmentation','RETRO','Cross-Attention','Visual Explainer'],
  '9 min read',
  '2022-01-03',
  'Jay Alammar',
  'https://jalammar.github.io/illustrated-retrieval-transformer/',
  'assets/img/covers/real/illustrated-retrieval-transformer.png',
  'RETRO retrieval transformer illustration',
  'cover',
  'published',
  false
),
(
  'illustrated-transformer',
  'The Illustrated Transformer',
  'The canonical visual walkthrough of the Transformer: self-attention built from query, key, and value projections, multi-head attention, positional encodings, residual connections, and the full encoder-decoder stack, all rendered as per-matrix diagrams. It describes the original 2017 encoder-decoder design, so decoder-only variants and later attention optimizations such as FlashAttention are not covered.',
  'Jay Alammar',
  'https://www.google.com/s2/favicons?domain=jalammar.github.io&sz=128',
  'LLM & MLLM',
  array['Transformer','Self-Attention','Architecture','Visual Explainer'],
  '15 min read',
  '2018-06-27',
  'Jay Alammar',
  'https://jalammar.github.io/illustrated-transformer/',
  'assets/img/covers/real/illustrated-transformer.png',
  'Illustrated Transformer architecture diagram',
  'contain',
  'published',
  false
),
(
  'hugging-face-illustrating-rlhf',
  'Illustrating Reinforcement Learning from Human Feedback (RLHF)',
  'Hugging Face breaks RLHF into three stages — pretraining a base language model, training a reward model on human preference rankings, and PPO fine-tuning against that reward with a KL penalty that keeps the policy near the reference model — and maps the design space along with open tooling like TRL and TRLX. Written in the ChatGPT era, it predates DPO-style direct preference optimization now common in post-training.',
  'Nathan Lambert, Louis Castricato, Leandro von Werra, Alex Havrilla',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'LLM & MLLM',
  array['RLHF','Reward Models','PPO','Alignment'],
  '12 min read',
  '2022-12-09',
  'Hugging Face Blog',
  'https://huggingface.co/blog/rlhf',
  'assets/img/covers/real/hugging-face-illustrating-rlhf.png',
  'Illustrating RLHF cover',
  'cover',
  'published',
  false
),
(
  'anthropic-mapping-mind-language-model',
  'Mapping the Mind of a Large Language Model',
  'Anthropic scales sparse dictionary learning to Claude 3 Sonnet, extracting millions of interpretable features from a production model — spanning multilingual and multimodal concepts like the Golden Gate Bridge as well as safety-relevant ones like deception and sycophancy — and shows that clamping features causally steers behavior. The recovered features are likely a small fraction of what the model represents, and the dictionary-learning pass is compute-intensive.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'LLM & MLLM',
  array['Interpretability','Sparse Autoencoders','Feature Steering','Claude'],
  '12 min read',
  '2024-05-21',
  'Anthropic',
  'https://www.anthropic.com/research/mapping-mind-language-model',
  'assets/img/covers/real/anthropic-mapping-mind-language-model.jpg',
  'Mapping the mind of a language model cover',
  'cover',
  'published',
  false
),
(
  'google-language-models-chain-of-thought',
  'Language Models Perform Reasoning via Chain of Thought',
  'Google Research shows that prompting PaLM with a few worked examples that spell out intermediate reasoning steps sharply improves arithmetic, commonsense, and symbolic reasoning, reaching 58% on GSM8K with PaLM 540B — then state of the art over a fine-tuned, verifier-ranked GPT-3. The gains are emergent with scale: smaller models produce fluent but illogical chains, so the technique mainly benefits models around 100B parameters and up.',
  'Jason Wei, Denny Zhou',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'LLM & MLLM',
  array['Chain of Thought','Prompting','Reasoning','Emergent Abilities'],
  '9 min read',
  '2022-05-11',
  'Google Research',
  'https://research.google/blog/language-models-perform-reasoning-via-chain-of-thought/',
  'assets/img/covers/real/google-language-models-chain-of-thought.jpg',
  'Chain of thought prompting cover',
  'cover',
  'published',
  false
),
(
  'matteo-nulli-demystifying-multimodal-learning',
  'Demystifying Multimodal Learning: Enabling Vision in Language Models',
  'Matteo Nulli builds vision-language models up from formal definitions: a ViT-based CLIP vision encoder, the contrastive objective that aligns image and text embeddings in a shared space, and the projector that turns patch embeddings into visual tokens a language model can consume, illustrated with LLaVA-OneVision-style diagrams. It is a tutorial synthesis rather than new experiments, and it focuses on the adapter-style VLM family.',
  'Matteo Nulli',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Multimodal Model',
  array['Vision-Language Models','CLIP','Visual Tokens','Tutorial'],
  '13 min read',
  '2026-02-17',
  'Hugging Face Blog',
  'https://huggingface.co/blog/MatteoNulli/de-mystifying-multimodal-learning-enabiling-vision',
  'assets/img/covers/real/matteo-nulli-demystifying-multimodal-learning.png',
  'Demystifying multimodal learning cover',
  'cover',
  'published',
  false
),
(
  'lilian-weng-generalized-visual-language-models',
  'Generalized Visual Language Models',
  'Lilian Weng surveys four ways to give language models vision: joint training on image-text pairs (VisualBERT, SimVLM), learned visual prefixes feeding a frozen LM (Frozen, ClipCap), cross-attention fusion, and training-free combinations of specialist models, comparing architectures and ablations across captioning and VQA benchmarks. Written in mid-2022, it predates instruction-tuned VLMs like LLaVA and GPT-4V-class systems.',
  'Lilian Weng',
  'https://www.google.com/s2/favicons?domain=lilianweng.github.io&sz=128',
  'Multimodal Model',
  array['Vision-Language Models','Frozen LM','Cross-Attention','Survey'],
  '18 min read',
  '2022-06-09',
  'Lil''Log',
  'https://lilianweng.github.io/posts/2022-06-09-vlm/',
  'assets/img/covers/real/lilian-weng-generalized-visual-language-models.png',
  'Generalized visual language models architecture diagram',
  'contain',
  'published',
  false
),
(
  'chip-huyen-multimodality-large-multimodal-models',
  'Multimodality and Large Multimodal Models (LMMs)',
  'Chip Huyen dissects two representative multimodal systems: CLIP’s contrastive image-text pretraining with a shared embedding space, and Flamingo’s Perceiver Resampler plus gated cross-attention layers for interleaved vision-language generation, then maps research directions like instruction tuning and more efficient training. The survey stops at 2023-era systems, before natively multimodal frontier models became standard.',
  'Chip Huyen',
  'https://www.google.com/s2/favicons?domain=huyenchip.com&sz=128',
  'Multimodal Model',
  array['Multimodal Models','CLIP','Flamingo','Survey'],
  '20 min read',
  '2023-10-10',
  'Chip Huyen',
  'https://huyenchip.com/2023/10/10/multimodal.html',
  'assets/img/covers/real/chip-huyen-multimodality-large-multimodal-models.png',
  'CLIP architecture diagram from multimodality survey',
  'contain',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;

select id, title, category, publish_date, status
from public.blogs
where id in (
  'mii-llm-zagreus-training-llm-from-scratch',
  'openai-techniques-for-training-large-neural-networks',
  'ai2-dolma-3-trillion-token-open-corpus',
  'apple-third-generation-foundation-models',
  'google-gemma-4-multi-token-prediction-drafters',
  'hazyresearch-structured-state-spaces-s4',
  'hugging-face-moe-in-transformers',
  'openai-learning-to-reason-with-llms',
  'minimax-maxproof-math-proof-evolution',
  'illustrated-retrieval-transformer',
  'illustrated-transformer',
  'hugging-face-illustrating-rlhf',
  'anthropic-mapping-mind-language-model',
  'google-language-models-chain-of-thought',
  'matteo-nulli-demystifying-multimodal-learning',
  'lilian-weng-generalized-visual-language-models',
  'chip-huyen-multimodality-large-multimodal-models'
)
order by category asc, publish_date desc, id asc;
