-- Add the fifteen 2026-08-25 Foundation Model / LLM & MLLM / Multimodal Model quality shelf expansion blogs to Supabase.
-- Mirrors the entries added to getQualityFoundationLlmMultimodalBlogs() in site/assets/js/app.js.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('deepmind-chinchilla-compute-optimal-training', 'An Empirical Analysis of Compute-Optimal Large Language Model Training', 'DeepMind trains over 400 language models from 70M to 16B parameters to answer one question: for a fixed compute budget, how should model size and training tokens trade off? The answer - scale both roughly equally - yields Chinchilla, a 70B model trained on 4x more data that outperforms the 280B Gopher and GPT-3 across most benchmarks. The analysis assumes a single pass over the data and ignores inference cost, which later work shows pushes the optimum toward even smaller, longer-trained models.', 'Jordan Hoffmann, Sebastian Borgeaud, Arthur Mensch, Laurent Sifre', 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128', 'Foundation Model', array['Scaling Laws','Chinchilla','Compute-Optimal Training','Pretraining'], '9 min read', '2022-04-12', 'Google DeepMind', 'https://deepmind.google/blog/an-empirical-analysis-of-compute-optimal-large-language-model-training/', 'assets/img/covers/real/deepmind-chinchilla-compute-optimal-training.webp', 'Chinchilla compute-optimal training blog cover', 'cover', 'published', false),
('ai2-olmo-3-model-flow', 'Olmo 3: Charting a Path Through the Model Flow to Lead Open-Source AI', 'Ai2 releases Olmo 3, a fully open family of 7B and 32B base, instruct, and reasoning models, and - unlike typical open-weight releases - publishes the entire model flow: Dolma 3 pretraining data, mid-training and long-context recipes, post-training datasets, and intermediate checkpoints. The 32B Think variant claims the strongest fully open reasoning results, narrowing the gap to Qwen 3 while training on roughly 6x fewer tokens; comparisons are against open-weight peers rather than frontier closed models.', 'Ai2', 'https://www.google.com/s2/favicons?domain=allenai.org&sz=128', 'Foundation Model', array['Olmo 3','Open Source Models','Reasoning Models','Model Flow'], '14 min read', '2025-11-20', 'Ai2 Blog', 'https://allenai.org/blog/olmo3', 'assets/img/covers/real/ai2-olmo-3-model-flow.jpg', 'Olmo 3 model flow announcement cover', 'cover', 'published', false),
('apple-on-device-server-foundation-models', 'Introducing Apple''s On-Device and Server Foundation Models', 'Apple introduces the foundation models behind Apple Intelligence: a ~3B-parameter on-device model and a larger server model running on Private Cloud Compute, specialized for everyday writing and summarization tasks. The post details swappable LoRA adapters fine-tuned per feature over a shared quantized base (3.7 bits per weight on average) and reports human evaluations where the on-device model beats similar-size open models; evaluations use Apple''s own task suites rather than public leaderboards.', 'Apple Machine Learning Research', 'https://www.google.com/s2/favicons?domain=machinelearning.apple.com&sz=128', 'Foundation Model', array['Apple Intelligence','On-Device AI','LoRA Adapters','Quantization'], '12 min read', '2024-06-10', 'Apple Machine Learning Research', 'https://machinelearning.apple.com/research/introducing-apple-foundation-models', 'assets/img/covers/real/apple-on-device-server-foundation-models.jpg', 'Apple on-device and server foundation models cover', 'cover', 'published', false),
('lilian-weng-transformer-family-v2', 'The Transformer Family Version 2.0', 'Lilian Weng''s comprehensive refresh of the Transformer taxonomy, organizing years of architectural refinements - positional encodings from sinusoidal to RoPE and ALiBi, longer-context mechanisms from Transformer-XL to memorizing transformers, adaptive computation, and sparse and efficient attention - into one coherent map with the math spelled out. It is a survey of designs rather than a benchmark shootout, so it tells you what exists and how each piece works, not which variant wins in practice.', 'Lilian Weng', 'https://www.google.com/s2/favicons?domain=lilianweng.github.io&sz=128', 'Foundation Model', array['Transformers','Architecture Survey','Positional Encoding','Attention Variants'], '30 min read', '2023-01-27', 'Lil''Log', 'https://lilianweng.github.io/posts/2023-01-27-the-transformer-family-v2/', 'assets/img/covers/real/lilian-weng-transformer-family-v2.png', 'Transformer architecture diagram from The Transformer Family v2', 'cover', 'published', false),
('hazyresearch-monarch-mixer-bert', 'Monarch Mixer: Revisiting BERT, Without Attention or MLPs', 'Hazy Research asks whether BERT quality is achievable without attention or MLPs, replacing both with Monarch matrices - generalizations of the FFT that are sub-quadratic in sequence length and model dimension. The resulting M2-BERT matches BERT-base GLUE quality with 27% fewer parameters and up to 9x higher throughput at long sequence lengths; results cover BERT-scale encoders only, and the authors flag scaling up and causal language modeling as open questions at the time.', 'Dan Fu, Simran Arora, and Chris Re', 'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128', 'Foundation Model', array['Monarch Matrices','Attention-Free Models','BERT','Sub-Quadratic Architectures'], '11 min read', '2023-07-25', 'Stanford Hazy Research', 'https://hazyresearch.stanford.edu/blog/2023-07-25-m2-bert', 'assets/img/covers/real/hazyresearch-monarch-mixer-bert.png', 'Monarch Mixer architecture diagram', 'cover', 'published', false),
('openai-instructgpt-instruction-following', 'Aligning Language Models to Follow Instructions', 'The InstructGPT announcement: OpenAI fine-tunes GPT-3 with supervised demonstrations and reinforcement learning from human feedback so it follows instructions, and labelers prefer outputs from the 1.3B InstructGPT model over the 175B GPT-3 - a 100x parameter deficit overcome by alignment training. The post is candid that this aligns models to labeler preferences under researcher-written guidelines, that the models still fabricate facts, and that toxicity drops only modestly while bias does not improve.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'LLM & MLLM', array['InstructGPT','RLHF','Alignment','Instruction Following'], '9 min read', '2022-01-27', 'OpenAI', 'https://openai.com/index/instruction-following/', 'assets/img/covers/real/openai-instructgpt-instruction-following.webp', 'InstructGPT instruction following article cover', 'cover', 'published', false),
('jalammar-illustrated-bert', 'The Illustrated BERT, ELMo, and co. (How NLP Cracked Transfer Learning)', 'Jay Alammar''s visual walkthrough of NLP''s "ImageNet moment": how ELMo''s contextualized embeddings, ULM-FiT''s transfer learning recipe, and the Transformer encoder converge into BERT''s masked-language-model pretraining and simple fine-tuning interface, explained one diagram at a time. Written in 2018, it describes the pretrain-and-fine-tune era rather than today''s prompt-based usage, but it remains one of the clearest entry points to encoder models.', 'Jay Alammar', 'https://www.google.com/s2/favicons?domain=jalammar.github.io&sz=128', 'LLM & MLLM', array['BERT','ELMo','Transfer Learning','Visualization'], '16 min read', '2018-12-03', 'Jay Alammar', 'https://jalammar.github.io/illustrated-bert/', 'assets/img/covers/real/jalammar-illustrated-bert.png', 'BERT transfer learning diagram from The Illustrated BERT', 'cover', 'published', false),
('hf-how-to-generate-decoding-methods', 'How to Generate Text: Using Different Decoding Methods for Language Generation with Transformers', 'Patrick von Platen explains the decoding methods behind every generate() call - greedy search, beam search, top-K, and top-p/nucleus sampling - with runnable Transformers code and concrete examples of the failure modes each fixes, from beam search repetition to the incoherence of naive sampling. Written in 2020, it predates newer strategies like contrastive search and speculative decoding, but its taxonomy still governs how LLM text generation is configured today.', 'Patrick von Platen', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'LLM & MLLM', array['Decoding Methods','Text Generation','Nucleus Sampling','Beam Search'], '12 min read', '2020-03-01', 'Hugging Face Blog', 'https://huggingface.co/blog/how-to-generate', 'assets/img/covers/real/hf-how-to-generate-decoding-methods.png', 'Text generation decoding methods cover', 'cover', 'published', false),
('hf-designing-positional-encoding', 'You Could Have Designed State of the Art Positional Encoding', 'Christopher Fleetwood re-derives modern positional encoding from first principles, starting from an attention layer that cannot tell token order and iteratively fixing it - integer positions, then sinusoidal embeddings, then rotating pairs of dimensions - until Rotary Position Embedding falls out as the natural solution, each step motivated by properties like relative-position dependence. The derivation stops at RoPE, leaving extensions such as multimodal rotary embeddings as pointers for further reading.', 'Christopher Fleetwood', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'LLM & MLLM', array['Positional Encoding','RoPE','Attention','Transformers'], '13 min read', '2024-11-25', 'Hugging Face Blog', 'https://huggingface.co/blog/designing-positional-encoding', 'assets/img/covers/real/hf-designing-positional-encoding.png', 'Designing positional encoding article cover', 'cover', 'published', false),
('lilian-weng-prompt-engineering', 'Prompt Engineering', 'Lilian Weng systematizes prompt engineering: zero-shot and few-shot basics, why example selection and ordering matter, instruction prompting, self-consistency sampling, chain-of-thought and tree-of-thoughts, automatic prompt search, and augmenting models with retrieval and external tools. She is upfront about her skepticism - the introduction calls some results questionable, and the conclusion argues the real goal should be models that make this fiddly tuning unnecessary.', 'Lilian Weng', 'https://www.google.com/s2/favicons?domain=lilianweng.github.io&sz=128', 'LLM & MLLM', array['Prompt Engineering','Chain of Thought','Few-Shot Learning','In-Context Learning'], '21 min read', '2023-03-15', 'Lil''Log', 'https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/', 'assets/img/covers/real/lilian-weng-prompt-engineering.png', 'Tree-of-thoughts diagram from the Prompt Engineering post', 'cover', 'published', false),
('openai-multimodal-neurons', 'Multimodal Neurons in Artificial Neural Networks', 'OpenAI finds neurons in CLIP that respond to concepts rather than surface forms - a "Spider-Man" neuron firing for photos, drawings, and the text "spider" - echoing the multimodal cells reported in human brains. The same abstraction enables "typographic attacks": taping a paper label reading "iPod" onto an apple flips the classification. Findings are specific to CLIP, and the interpretability tools inspect individual neurons rather than complete circuits.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Multimodal Model', array['CLIP','Interpretability','Multimodal Neurons','Typographic Attacks'], '13 min read', '2021-03-04', 'OpenAI', 'https://openai.com/index/multimodal-neurons/', 'assets/img/covers/real/openai-multimodal-neurons.png', 'Multimodal neurons in CLIP article cover', 'cover', 'published', false),
('openai-introducing-whisper', 'Introducing Whisper', 'OpenAI open-sources Whisper, a speech recognition transformer trained on 680,000 hours of weakly supervised multilingual web audio that transcribes, identifies language, and translates to English within a single sequence-to-sequence model. The bet on diverse, noisy supervision pays off in robustness - roughly 50% fewer errors than specialized models on out-of-distribution audio - while the post concedes Whisper does not beat models fine-tuned on LibriSpeech at their own benchmark.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Multimodal Model', array['Whisper','Speech Recognition','Weak Supervision','Open Source Models'], '8 min read', '2022-09-21', 'OpenAI', 'https://openai.com/index/whisper/', 'assets/img/covers/real/openai-introducing-whisper.jpg', 'Whisper speech recognition announcement cover', 'cover', 'published', false),
('ai2-olmocr-pdf-extraction-vlm', 'olmOCR: Efficient PDF Text Extraction with Vision Language Models', 'Ai2 releases olmOCR, an open toolkit that fine-tunes a 7B vision-language model to convert PDFs into clean, linearized plain text for language model training, using "document anchoring" to inject the PDF''s internal text and layout metadata alongside the rendered page image. It handles equations, tables, and handwriting at roughly $190 per million pages - about 1/32 the cost of GPT-4o batch processing - though quality is validated mainly by pairwise human preference against other OCR pipelines rather than a public benchmark.', 'Ai2', 'https://www.google.com/s2/favicons?domain=allenai.org&sz=128', 'Multimodal Model', array['OCR','Vision-Language Models','PDF Extraction','Training Data'], '10 min read', '2025-02-25', 'Ai2 Blog', 'https://allenai.org/blog/olmocr', 'assets/img/covers/real/ai2-olmocr-pdf-extraction-vlm.png', 'olmOCR PDF extraction toolkit cover', 'cover', 'published', false),
('nvidia-multimodal-rag-introduction', 'An Easy Introduction to Multimodal Retrieval-Augmented Generation', 'Annie Surla lays out the three architectures for extending RAG beyond text - grounding all modalities into one (captioning images at ingest), embedding everything in a shared space like CLIP, or routing to separate stores per modality - and walks through a concrete pipeline that detects charts, converts them to linearized tables with DePlot, and retrieves them alongside text. It is a tutorial built around NVIDIA-hosted endpoints, so the specific components are illustrative rather than prescriptive.', 'Annie Surla', 'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128', 'Multimodal Model', array['Multimodal RAG','Retrieval-Augmented Generation','Vision-Language Models','Document Understanding'], '11 min read', '2024-03-20', 'NVIDIA Technical Blog', 'https://developer.nvidia.com/blog/an-easy-introduction-to-multimodal-retrieval-augmented-generation/', 'assets/img/covers/real/nvidia-multimodal-rag-introduction.jpg', 'Multimodal retrieval-augmented generation cover', 'cover', 'published', false),
('hf-idefics-open-visual-language-model', 'Introducing IDEFICS: An Open Reproduction of State-of-the-Art Visual Language Model', 'Hugging Face releases IDEFICS, an 80B open-access reproduction of DeepMind''s closed Flamingo visual language model, trained exclusively on publicly available data - including the purpose-built OBELICS web-document dataset - and matching the original on image captioning and visual question answering benchmarks. The post documents the red-teaming and filtering behind the release while noting the model inherits the failure modes of web-trained VLMs, including hallucination and bias.', 'Hugo Laurencon, Victor Sanh, et al.', 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128', 'Multimodal Model', array['IDEFICS','Flamingo','Vision-Language Models','Open Reproduction'], '10 min read', '2023-08-22', 'Hugging Face Blog', 'https://huggingface.co/blog/idefics', 'assets/img/covers/real/hf-idefics-open-visual-language-model.png', 'IDEFICS visual language model announcement cover', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
