-- Add the 2026-08-25 canonical How to Research batch to Supabase.
-- Mirrors the entries added to getQualityHowToResearchBlogs() in site/assets/js/app.js.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('paul-graham-how-to-do-great-work', 'How to Do Great Work', 'Paul Graham merges the advice given across fields into one recipe: pick a field matching your natural aptitude and deep curiosity, work hard at the frontier until you can see the gaps, and let curiosity rather than premeditated plans steer each stage. The essay is long, aphoristic, and deliberately general, so readers must map its claims onto their own discipline.', 'Paul Graham', 'https://www.google.com/s2/favicons?domain=paulgraham.com&sz=128', 'How to Research', array['Ambition','Curiosity','Problem Selection','Classic Essay'], '55 min read', '2023-07-01', 'paulgraham.com', 'https://www.paulgraham.com/greatwork.html', 'assets/img/covers/cover-great-work.svg', 'Editorial cover showing an upward path toward a highlighted goal', 'cover', 'published', false),
('sebastian-ruder-10-tips-for-research-and-a-phd', '10 Tips for Research and a PhD', 'Fresh from finishing his own PhD, Sebastian Ruder lists ten habits that compounded: start writing from day one, work on one or two focused projects at a time, be ambitious enough to fail, collaborate deliberately, and publish artifacts — code, blog posts, and reviews — that outlive individual papers. The advice targets machine learning and NLP students specifically.', 'Sebastian Ruder', 'https://www.google.com/s2/favicons?domain=ruder.io&sz=128', 'How to Research', array['PhD Advice','ML Research','Writing Habits','Collaboration'], '15 min read', '2020-05-22', 'ruder.io', 'https://www.ruder.io/10-tips-for-research-and-a-phd/', 'assets/img/covers/real/sebastian-ruder-10-tips-for-research-and-a-phd.jpg', 'Real cover from og:image', 'cover', 'published', false),
('tim-dettmers-machine-learning-phd-applications', 'Machine Learning PhD Applications — Everything You Need to Know', 'Tim Dettmers dissects how ML PhD admissions actually weigh publications, recommendation letters, and research fit, then walks through school selection, statement writing, and interviews with data from his own application cycle. The mechanics are specific to competitive US and Canadian programs around 2018, but the ranking of what matters has aged well.', 'Tim Dettmers', 'https://www.google.com/s2/favicons?domain=timdettmers.com&sz=128', 'How to Research', array['PhD Applications','Graduate School','ML Research','Career Advice'], '35 min read', '2018-11-26', 'Tim Dettmers', 'https://timdettmers.com/2018/11/26/phd-applications/', 'assets/img/covers/real/tim-dettmers-machine-learning-phd-applications.gif', 'Real cover from og:image', 'cover', 'published', false),
('richard-feynman-cargo-cult-science', 'Cargo Cult Science', 'Feynman''s 1974 Caltech commencement address names the failure mode where work has the outer form of science but lacks utter honesty: report everything that could make your result wrong, not just what supports it. His account of why the measured charge of the electron drifted slowly after Millikan remains the canonical parable of experimenter bias.', 'Richard Feynman', 'https://www.google.com/s2/favicons?domain=calteches.library.caltech.edu&sz=128', 'How to Research', array['Scientific Integrity','Experimental Rigor','Research Ethics','Classic Essay'], '18 min read', '1974-06-14', 'Caltech Engineering and Science', 'https://calteches.library.caltech.edu/51/2/CargoCult.htm', 'assets/img/covers/cover-cargo-cult-science.svg', 'Editorial cover contrasting a solid document with a hollow dashed copy', 'cover', 'published', false),
('martin-schwartz-the-importance-of-stupidity-in-scientific-research', 'The Importance of Stupidity in Scientific Research', 'Martin Schwartz''s one-page Journal of Cell Science essay argues that real research means feeling actively confused most of the time, and that graduate school is hard because coursework rewards knowing answers while research demands wading into the unknown. Embracing this ''productive stupidity'' is presented as the core psychological transition of becoming a scientist.', 'Martin A. Schwartz', 'https://www.google.com/s2/favicons?domain=journals.biologists.com&sz=128', 'How to Research', array['Productive Stupidity','Research Mindset','Graduate School','Classic Essay'], '5 min read', '2008-06-01', 'Journal of Cell Science', 'https://journals.biologists.com/jcs/article/121/11/1771/30038/The-importance-of-stupidity-in-scientific-research', 'assets/img/covers/cover-productive-stupidity.svg', 'Editorial cover showing a head silhouette filled with a question mark', 'cover', 'published', false),
('michael-ernst-how-to-write-a-technical-paper', 'How to Write a Technical Paper', 'Michael Ernst''s continuously updated guide covers point-first writing, one idea per paragraph and sentence, figure design, naming, responding to reviews, and relentless revision, with each rule illustrated by concrete before-and-after examples from real drafts. It reads as a working editor''s checklist rather than abstract style advice.', 'Michael Ernst', 'https://www.google.com/s2/favicons?domain=homes.cs.washington.edu&sz=128', 'How to Research', array['Paper Writing','Technical Communication','Revision','Research Skills'], '40 min read', '2005-01-01', 'University of Washington CSE', 'https://homes.cs.washington.edu/~mernst/advice/write-technical-paper.html', 'assets/img/covers/cover-technical-paper-writing.svg', 'Editorial cover showing an annotated manuscript with an editing pencil', 'cover', 'published', false),
('mensh-kording-ten-simple-rules-for-structuring-papers', 'Ten Simple Rules for Structuring Papers', 'Brett Mensh and Konrad Kording compress paper structure into ten rules built around a single central contribution: apply context-content-conclusion at every scale from sentence to manuscript, write for the time-constrained reader who skims, and budget writing effort by how much each section shapes the paper''s fate. The rules are field-agnostic and widely taught in ML groups.', 'Brett Mensh and Konrad Kording', 'https://www.google.com/s2/favicons?domain=journals.plos.org&sz=128', 'How to Research', array['Paper Writing','Scientific Communication','Storytelling','Research Skills'], '20 min read', '2017-09-28', 'PLOS Computational Biology', 'https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005619', 'assets/img/covers/real/kording-mensh-ten-simple-rules-for-structuring-papers.png', 'Real cover from og:image', 'contain', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
