-- Add the 2026-08-25 canonical batch of Research Craft, Frontier, How to Research, and Trustworthy AI blogs to Supabase.
-- Mirrors the entries added to the static corpus in site/assets/js/app.js (getCanonicalQualityBlogs).
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('paul-graham-how-to-do-great-work', 'How to Do Great Work', 'Graham distills the intersection of what great workers in many fields do: pick work matching aptitude and deep interest, run excitingly ambitious projects of your own, chase outlier ideas the field ignores, and let excited curiosity — not a plan — steer decades of compounding effort.', 'Paul Graham', 'https://www.google.com/s2/favicons?domain=paulgraham.com&sz=128', 'How to Research', array['Ambition','Problem Selection','Curiosity','Classic Essay'], '60 min read', '2023-07-01', 'paulgraham.com', 'https://www.paulgraham.com/greatwork.html', 'assets/img/covers/real/paul-graham-how-to-do-great-work.png', 'Real cover from manual:original-page-screenshot', 'cover', 'published', false),
('michael-nielsen-augmenting-long-term-memory', 'Augmenting Long-term Memory', 'Nielsen makes memory a choice: he uses Anki to internalize the AlphaGo literature and an unfamiliar field, then derives concrete practice — atomic cards, twenty simple questions over one profound one, syntopic reading — for turning spaced repetition into a serious research instrument.', 'Michael Nielsen', 'https://www.google.com/s2/favicons?domain=augmentingcognition.com&sz=128', 'How to Research', array['Spaced Repetition','Memory Systems','Paper Reading','Research Tools'], '60 min read', '2018-07-01', 'Y Combinator Research', 'https://augmentingcognition.com/ltm.html', 'assets/img/covers/real/michael-nielsen-augmenting-long-term-memory.png', 'Real cover from manual:original-page-screenshot', 'cover', 'published', false),
('feynman-cargo-cult-science', 'Cargo Cult Science', 'Feynman’s 1974 Caltech commencement address names the failure mode of research that follows every form of science but omits its essence: bending over backwards to report what might make you wrong. The first principle is that you must not fool yourself — and you are the easiest person to fool.', 'Richard P. Feynman', 'https://www.google.com/s2/favicons?domain=calteches.library.caltech.edu&sz=128', 'How to Research', array['Scientific Integrity','Self-Deception','Experimental Method','Classic Essay'], '15 min read', '1974-06-14', 'Caltech Engineering & Science', 'https://calteches.library.caltech.edu/51/2/CargoCult.htm', 'assets/img/covers/real/feynman-cargo-cult-science.png', 'Real cover from manual:original-page-screenshot', 'cover', 'published', false),
('eugene-yan-llm-patterns', 'Patterns for Building LLM-based Systems & Products', 'Eugene Yan’s field survey of seven patterns for shipping LLM systems — evals, RAG, fine-tuning, caching, guardrails, defensive UX, and collecting user feedback — organized along the axes of improving performance versus reducing cost and risk.', 'Eugene Yan', 'https://www.google.com/s2/favicons?domain=eugeneyan.com&sz=128', 'Research Craft', array['LLM Systems','Evals','RAG','Design Patterns'], '45 min read', '2023-07-30', 'eugeneyan.com', 'https://eugeneyan.com/writing/llm-patterns/', 'assets/img/covers/real/eugene-yan-llm-patterns.png', 'Real cover from og:image', 'cover', 'published', false),
('hamel-husain-show-me-the-prompt', 'Fuck You, Show Me The Prompt.', 'Hamel Husain intercepts the API calls of popular LLM frameworks with mitmproxy to expose the prompts they actually send, arguing that inspecting raw prompts — not trusting framework abstractions — is the fastest way to debug, evaluate, and often simplify LLM pipelines.', 'Hamel Husain', 'https://www.google.com/s2/favicons?domain=hamel.dev&sz=128', 'Research Craft', array['Prompt Engineering','Debugging','LLM Tooling','Observability'], '18 min read', '2024-02-14', 'Hamel’s Blog', 'https://hamel.dev/blog/posts/prompt/', 'assets/img/covers/real/hamel-husain-show-me-the-prompt.png', 'Real cover from og:image', 'cover', 'published', false),
('distill-why-momentum-really-works', 'Why Momentum Really Works', 'Gabriel Goh’s interactive Distill article derives momentum’s dynamics on convex quadratics, showing how the optimizer trades short-term oscillation for a quadratic speedup in convergence — and why the folk story of a heavy ball rolling downhill undersells what is really going on.', 'Gabriel Goh', 'https://www.google.com/s2/favicons?domain=distill.pub&sz=128', 'Research Craft', array['Optimization','Momentum','Gradient Descent','Interactive Explanation'], '25 min read', '2017-04-04', 'Distill', 'https://distill.pub/2017/momentum/', 'assets/img/covers/real/distill-why-momentum-really-works.jpg', 'Real cover from og:image', 'cover', 'published', false),
('distill-multimodal-neurons', 'Multimodal Neurons in Artificial Neural Networks', 'The OpenAI Clarity team finds neurons in CLIP that respond to concepts — Spider-Man, emotions, regions — across photos, drawings, and text, and demonstrates typographic adversarial attacks where taping a paper label to an apple changes its classification.', 'Gabriel Goh, Nick Cammarata, Chelsea Voss, Shan Carter, Michael Petrov, Ludwig Schubert, Alec Radford, and Chris Olah', 'https://www.google.com/s2/favicons?domain=distill.pub&sz=128', 'Trustworthy AI', array['Interpretability','CLIP','Multimodal Neurons','Adversarial Examples'], '40 min read', '2021-03-04', 'Distill', 'https://distill.pub/2021/multimodal-neurons/', 'assets/img/covers/real/distill-multimodal-neurons.png', 'Real cover from og:image', 'cover', 'published', false),
('metr-recent-frontier-models-are-reward-hacking', 'Recent Frontier Models Are Reward Hacking', 'METR documents recent frontier models rewriting timers, special-casing test files, and subverting scoring code in RE-Bench and HCAST tasks — behavior the models themselves often describe as cheating when asked — and analyzes why naive training against detected hacks may push deception underground.', 'METR', 'https://www.google.com/s2/favicons?domain=metr.org&sz=128', 'Trustworthy AI', array['Reward Hacking','Frontier Models','Evaluations','AI Safety'], '15 min read', '2025-06-05', 'METR Blog', 'https://metr.org/blog/2025-06-05-recent-reward-hacking/', 'assets/img/covers/real/metr-recent-frontier-models-are-reward-hacking.png', 'Real cover from og:image', 'cover', 'published', false),
('uk-aisi-safety-cases-at-aisi', 'Safety cases at AISI', 'AISI’s chief scientist introduces safety cases — structured, reviewable arguments that a system is safe in a specific context — and explains why the institute is sketching them now for future frontier risks like loss of control, before the evidence needed to complete them exists.', 'Geoffrey Irving', 'https://www.google.com/s2/favicons?domain=aisi.gov.uk&sz=128', 'Trustworthy AI', array['Safety Cases','AI Governance','Loss of Control','Structured Arguments'], '12 min read', '2024-08-23', 'UK AISI', 'https://www.aisi.gov.uk/blog/safety-cases-at-aisi', 'assets/img/covers/real/uk-aisi-safety-cases-at-aisi.png', 'Real cover from og:image', 'cover', 'published', false),
('epoch-ai-algorithmic-progress-in-language-models', 'Algorithmic Progress in Language Models', 'Analyzing over 200 language models from 2012-2023, Epoch estimates that the compute needed to reach a fixed capability level halves roughly every eight months — faster than Moore’s law — though compute scaling still explains most recent performance gains.', 'Anson Ho et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Algorithmic Progress','Compute Efficiency','Scaling Laws','Trend Analysis'], '10 min read', '2024-03-12', 'Epoch AI', 'https://epoch.ai/publications/algorithmic-progress-in-language-models', 'assets/img/covers/real/epoch-ai-algorithmic-progress-in-language-models.png', 'Real cover from og:image', 'cover', 'published', false),
('epoch-ai-how-much-does-it-cost-to-train-frontier-ai-models', 'How Much Does It Cost to Train Frontier AI Models?', 'Epoch develops two methods for estimating the cost of frontier training runs, finding costs have grown 2.4x per year since 2016 — with GPT-4 around $40M and Gemini Ultra near $130M in amortized hardware and energy — implying billion-dollar runs within a few years.', 'Ben Cottier et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Training Costs','Compute Economics','Frontier Models','Hardware'], '12 min read', '2024-06-03', 'Epoch AI', 'https://epoch.ai/publications/how-much-does-it-cost-to-train-frontier-ai-models', 'assets/img/covers/real/epoch-ai-how-much-does-it-cost-to-train-frontier-ai-models.png', 'Real cover from og:image', 'cover', 'published', false),
('epoch-ai-will-we-run-out-of-data', 'Will We Run Out of Data? Limits of LLM Scaling Based on Human-Generated Data', 'Epoch projects the total stock of public human-generated text — roughly 300 trillion tokens — against dataset growth, concluding frontier LLMs will fully utilize it between 2026 and 2032 and making synthetic data, multimodality, and transfer learning decisive for scaling beyond.', 'Pablo Villalobos et al.', 'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128', 'Frontier', array['Data Scarcity','Scaling Limits','Training Data','Forecasting'], '15 min read', '2024-06-06', 'Epoch AI', 'https://epoch.ai/publications/will-we-run-out-of-data-limits-of-llm-scaling-based-on-human-generated-data', 'assets/img/covers/real/epoch-ai-will-we-run-out-of-data.png', 'Real cover from og:image', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
