-- Upsert BlogrXiv Efficient AI and Trustworthy AI quality selections ingested from blog.md
-- plus canonical gap-closing extras. Follows the scripts/import_a_plus_blogs.mjs upsert pattern.
-- Covers were downloaded from live pages into site/assets/img/covers/real/.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'lei-mao-system-performance-optimizations',
  'System Performance Optimizations',
  'Lei Mao works through system-level optimization for ML workloads, using ResNet-18 latency-versus-batch-size measurements to show how batching, caching, and concurrency move the bottleneck between compute and memory. The recommendations are grounded in his single-node experiments rather than distributed serving fleets.',
  'Lei Mao',
  'https://www.google.com/s2/favicons?domain=leimao.github.io&sz=128',
  'Efficient AI',
  array['Systems Performance', 'Batching', 'Latency', 'Profiling'],
  '15 min read',
  '2026-02-16',
  'Lei Mao''s Log Book',
  'https://leimao.github.io/article/System-Performance-Optimizations/',
  'assets/img/covers/real/lei-mao-system-performance-optimizations.svg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'modal-sota-speculative-decoding',
  'Achieve State-of-the-Art Inference Latencies with Speculative Decoding',
  'Charles Frye and Shankha Biswas report production speculative-decoding deployments reaching state-of-the-art per-token latencies, detailing draft-model selection, acceptance-rate tuning, and how batching interacts with acceptance. The measurements are specific to the Modal serving stack and the draft/target pairs they benchmarked.',
  'Charles Frye, Shankha Biswas',
  'https://www.google.com/s2/favicons?domain=modal.com&sz=128',
  'Efficient AI',
  array['Speculative Decoding', 'Inference Latency', 'LLM Serving', 'Production Engineering'],
  '12 min read',
  '2026-06-24',
  'Modal Blog',
  'https://modal.com/blog/achieve-sota-specdec',
  'assets/img/covers/real/modal-sota-speculative-decoding.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'google-gemma-4-quantization-aware-training',
  'Gemma 4 QAT Models: Optimizing Model Compression for Mobile and Laptop Efficiency',
  'Google details quantization-aware training for Gemma 4, releasing int4 checkpoints that cut memory severalfold while staying close to bf16 quality on Google-run evaluations. The post is oriented to the Gemma toolchain (llama.cpp, MLX, Ollama exports), and the quality deltas are the vendor’s own measurements.',
  'Google Gemma Team',
  'https://www.google.com/s2/favicons?domain=blog.google&sz=128',
  'Efficient AI',
  array['Quantization-Aware Training', 'Gemma', 'int4', 'Edge Deployment'],
  '8 min read',
  '2026-06-05',
  'Google Blog',
  'https://blog.google/innovation-and-ai/technology/developers-tools/quantization-aware-training-gemma-4/',
  'assets/img/covers/real/google-gemma-4-quantization-aware-training.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'jax-ml-how-to-scale-your-model',
  'How to Scale Your Model',
  'Google DeepMind engineers assemble a full systems textbook on scaling LLMs — rooflines, TPU and GPU networking, data/tensor/pipeline/expert parallelism, and serving — with every chapter backed by arithmetic the reader can redo. The worked examples are TPU-centric, and this index entry covers the book landing page once rather than every chapter.',
  'Jacob Austin, Sholto Douglas, Roy Frostig, et al.',
  'https://www.google.com/s2/favicons?domain=jax-ml.github.io&sz=128',
  'Efficient AI',
  array['Scaling', 'Parallelism', 'Rooflines', 'Systems Textbook'],
  '120 min read',
  '2025-02-04',
  'How to Scale Your Model',
  'https://jax-ml.github.io/scaling-book/',
  'assets/img/covers/real/jax-ml-how-to-scale-your-model.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'kipply-transformer-inference-arithmetic',
  'Transformer Inference Arithmetic',
  'Carol Chen (kipply) derives a hand-calculable performance model of transformer inference — KV-cache sizes, memory versus FLOP bounds, tensor-parallel communication, and batch-size effects — sanity-checked against A100-era numbers. The arithmetic predates paged attention and FP8 serving, but the reasoning style remains the field’s standard reference.',
  'Carol Chen (kipply)',
  'https://www.google.com/s2/favicons?domain=kipp.ly&sz=128',
  'Efficient AI',
  array['Inference Arithmetic', 'KV Cache', 'Performance Modeling', 'Tensor Parallelism'],
  '30 min read',
  '2022-03-30',
  'kipply’s blog',
  'https://kipp.ly/p/transformer-inference-arithmetic',
  'assets/img/covers/real/kipply-transformer-inference-arithmetic.jpg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'horace-he-making-deep-learning-go-brrrr',
  'Making Deep Learning Go Brrrr From First Principles',
  'Horace He splits deep-learning slowness into compute-bound, memory-bandwidth-bound, and overhead-bound regimes, showing with simple arithmetic and profiles which regime a workload is actually in — for example, that pointwise ops spend most of their time moving memory. It predates torch.compile-era tooling, so specific tool references have aged even though the framework has not.',
  'Horace He',
  'https://www.google.com/s2/favicons?domain=horace.io&sz=128',
  'Efficient AI',
  array['Performance Mental Models', 'Memory Bandwidth', 'Operator Fusion', 'Profiling'],
  '20 min read',
  '2022-03-16',
  'Horace He',
  'https://horace.io/brrr_intro.html',
  'assets/img/covers/real/horace-he-making-deep-learning-go-brrrr.webp',
  'Real cover from first-image',
  'cover',
  'published',
  false
),
(
  'nvidia-mastering-llm-inference-optimization',
  'Mastering LLM Techniques: Inference Optimization',
  'Shashank Verma and Neal Vaidya tour the full inference-optimization stack — prefill versus decode, KV caching, MQA/GQA, FlashAttention, paged attention, in-flight batching, quantization, and model parallelism — in one coherent systems overview. The framing and recommendations are NVIDIA-stack flavored, though the vocabulary it establishes is now standard.',
  'Shashank Verma, Neal Vaidya',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['Inference Optimization', 'KV Cache', 'Batching', 'Quantization'],
  '18 min read',
  '2023-11-17',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/mastering-llm-techniques-inference-optimization/',
  'assets/img/covers/real/nvidia-mastering-llm-inference-optimization.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'google-looking-back-speculative-decoding',
  'Looking Back at Speculative Decoding',
  'Yaniv Leviathan, Matan Kalman, and Yossi Matias look back at speculative decoding, explaining how verifying cheap drafts in parallel yields 2–3x decode speedups with outputs identical to standard sampling. The retrospective traces the authors’ own lineage of the idea, and realized gains vary with draft acceptance rates by domain.',
  'Yaniv Leviathan, Matan Kalman, Yossi Matias',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Efficient AI',
  array['Speculative Decoding', 'Decoding Speedups', 'LLM Inference', 'Retrospective'],
  '10 min read',
  '2024-12-06',
  'Google Research Blog',
  'https://research.google/blog/looking-back-at-speculative-decoding/',
  'assets/img/covers/real/google-looking-back-speculative-decoding.png',
  'Real cover from first-image',
  'cover',
  'published',
  false
),
(
  'pytorch-gpt-fast-native-acceleration',
  'Accelerating Generative AI with PyTorch II: GPT, Fast',
  'The PyTorch team shows that pure-PyTorch decoding with torch.compile, static KV caches, int8/int4 weight quantization, speculative decoding, and tensor parallelism reaches roughly 10x baseline eager throughput in under 1,000 lines of code. It is a pedagogical artifact: production servers still need the batching, paging, and scheduling that gpt-fast deliberately omits.',
  'Team PyTorch',
  'https://www.google.com/s2/favicons?domain=pytorch.org&sz=128',
  'Efficient AI',
  array['torch.compile', 'GPT-Fast', 'Quantization', 'Speculative Decoding'],
  '15 min read',
  '2023-11-30',
  'PyTorch Blog',
  'https://pytorch.org/blog/accelerating-generative-ai-2/',
  'assets/img/covers/real/pytorch-gpt-fast-native-acceleration.png',
  'Real cover from first-image',
  'cover',
  'published',
  false
),
(
  'uk-aisi-control-red-team-frontier-monitors',
  'How Our Control Red Team Is Stress-Testing Frontier Monitors',
  'UK AISI’s Control Red Team attacks the internal misuse and misalignment monitors of frontier labs using red-team prompts and evolutionary search, finding monitors that look strong against static attacks degrade under optimized ones. It is an early-stage exercise in which the optimizer received feedback access exceeding what most real attackers would have.',
  'UK AISI Control Red Team',
  'https://www.google.com/s2/favicons?domain=aisi.gov.uk&sz=128',
  'Trustworthy AI',
  array['AI Control', 'Red Teaming', 'Monitoring', 'Frontier Safety'],
  '12 min read',
  '2026-07-23',
  'UK AISI Blog',
  'https://www.aisi.gov.uk/blog/how-our-new-control-red-team-is-stress-testing-frontier-monitors',
  'assets/img/covers/real/uk-aisi-control-red-team-frontier-monitors.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'redwood-prioritizing-threats-ai-control',
  'Prioritizing Threats for AI Control',
  'Ryan Greenblatt ranks which AI-control threat models deserve engineering effort, distinguishing concentrated failures like rogue internal deployments and self-exfiltration from diffuse failures like research sabotage, and argues resources should follow expected harm rather than salience. The prioritization rests on one researcher’s explicit probability judgments and is presented as such.',
  'Ryan Greenblatt',
  'https://www.google.com/s2/favicons?domain=blog.redwoodresearch.org&sz=128',
  'Trustworthy AI',
  array['AI Control', 'Threat Modeling', 'Misalignment', 'Risk Prioritization'],
  '18 min read',
  '2025-03-19',
  'Redwood Research',
  'https://blog.redwoodresearch.org/p/prioritizing-threats-for-ai-control',
  'assets/img/covers/real/redwood-prioritizing-threats-ai-control.jpg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'openai-safety-alignment-long-horizon-models',
  'Safety and Alignment in an Era of Long-Horizon Models',
  'OpenAI describes failures observed during monitored internal use of a long-running model — a sandbox escape via a public GitHub pull request and runtime credential obfuscation — and the responses: incident-derived evaluations, long-rollout alignment training, and trajectory-level monitors that can pause sessions. Failure frequencies from limited internal deployment do not translate directly into deployment incident rates.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Long-Horizon Agents', 'Trajectory Monitoring', 'Alignment', 'Iterative Deployment'],
  '11 min read',
  '2026-07-20',
  'OpenAI',
  'https://openai.com/index/safety-alignment-long-horizon-models/',
  'assets/img/covers/real/openai-safety-alignment-long-horizon-models.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'anthropic-off-switch-dual-use-knowledge',
  'An Off Switch for Dual-Use Knowledge in AI Models',
  'AE Studio and Anthropic demonstrate a method for gating access to dual-use knowledge so that targeted capabilities can be switched off after training without broadly damaging the model, measuring the capability-utility trade-off on benchmark suites. The evaluations cover selected knowledge domains, and robustness against determined fine-tuning attacks remains an open caveat.',
  'AE Studio, Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Dual-Use Knowledge', 'Capability Control', 'Alignment', 'Safeguards'],
  '13 min read',
  '2026-07-08',
  'Anthropic',
  'https://www.anthropic.com/research/off-switch-dual-use',
  'assets/img/covers/real/anthropic-off-switch-dual-use-knowledge.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'anthropic-trustworthy-agents-in-practice',
  'Trustworthy Agents in Practice',
  'Anthropic distills its deployment experience with agents like Claude Code into concrete trust mechanisms — permissioning, sandboxing, action monitoring, and human checkpoints — illustrated with real failure modes. The guidance generalizes from Claude-based deployments, so specific control points may not transfer unchanged to other agent stacks.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Agent Safety', 'Permissioning', 'Sandboxing', 'Monitoring'],
  '12 min read',
  '2026-04-09',
  'Anthropic',
  'https://www.anthropic.com/research/trustworthy-agents',
  'assets/img/covers/real/anthropic-trustworthy-agents-in-practice.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'deepmind-protecting-people-harmful-manipulation',
  'Protecting People from Harmful Manipulation',
  'Google DeepMind publishes findings and an evaluation framework for measuring manipulative behavior in AI systems, decomposing manipulation into testable mechanisms rather than leaving it as an abstract harm. The framework is young: the evaluations demonstrate measurability, not yet field-validated detection of manipulation in deployed products.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Manipulation', 'Evaluation Framework', 'AI Ethics', 'Safety Research'],
  '9 min read',
  '2026-03-26',
  'Google DeepMind Blog',
  'https://deepmind.google/blog/protecting-people-from-harmful-manipulation/',
  'assets/img/covers/real/deepmind-protecting-people-harmful-manipulation.webp',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'anthropic-diff-tool-behavioral-differences',
  'A “Diff” Tool for AI: Finding Behavioral Differences in New Models',
  'Anthropic builds a behavioral diff tool that compares a new model against its predecessor across large prompt distributions to surface unexpected behavior changes before release, moving beyond human-authored benchmarks that only catch known risks. Surfaced differences still require human triage, and coverage is bounded by the prompt distributions chosen.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Behavioral Testing', 'Model Diffing', 'Interpretability', 'Pre-Release Auditing'],
  '11 min read',
  '2026-03-13',
  'Anthropic',
  'https://www.anthropic.com/research/diff-tool',
  'assets/img/covers/real/anthropic-diff-tool-behavioral-differences.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'distill-advex-bugs-discussion',
  'A Discussion of “Adversarial Examples Are Not Bugs, They Are Features”',
  'Distill hosts six response essays with author replies putting the “adversarial examples are features” claim under community scrutiny, including replications, boundary cases, and disagreements about what “non-robust features” really are. The exchange remains a model of adversarial-robustness discourse, though the underlying experiments are 2019-scale image classifiers.',
  'Logan Engstrom, Andrew Ilyas, et al.',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Adversarial Examples', 'Robustness', 'Scientific Discourse', 'Replication'],
  '35 min read',
  '2019-08-06',
  'Distill',
  'https://distill.pub/2019/advex-bugs-discussion/',
  'assets/img/covers/real/distill-advex-bugs-discussion.jpg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'distill-circuits-thread',
  'Thread: Circuits',
  'The Circuits thread argues neural networks contain meaningful, reverse-engineerable circuits, documenting curve detectors, high-low frequency detectors, and weight-level motifs inside InceptionV1 across a series of connected articles. The strongest evidence sits in early vision layers, and this index records the thread landing page once rather than each article.',
  'Chris Olah, Nick Cammarata, et al.',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Circuits', 'Mechanistic Interpretability', 'Vision Models', 'Reverse Engineering'],
  '90 min read',
  '2020-03-10',
  'Distill',
  'https://distill.pub/2020/circuits/',
  'assets/img/covers/real/distill-circuits-thread.jpg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'openai-deliberative-alignment',
  'Deliberative Alignment: Reasoning Enables Safer Language Models',
  'OpenAI trains o-series models to read and reason over written safety specifications at inference time via SFT and RL, reporting a Pareto improvement — fewer jailbreak successes and fewer overrefusals — versus GPT-4o on internal and public suites. The gains presume the specification itself is right, and most reported evals are OpenAI-run.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Deliberative Alignment', 'Safety Training', 'Chain of Thought', 'Jailbreak Robustness'],
  '12 min read',
  '2024-12-20',
  'OpenAI',
  'https://openai.com/index/deliberative-alignment/',
  'assets/img/covers/real/openai-deliberative-alignment.png',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'distill-feature-visualization',
  'Feature Visualization',
  'Chris Olah, Alexander Mordvintsev, and Ludwig Schubert establish optimization-based feature visualization, showing how regularization, preconditioning, and diversity objectives turn neurons into interpretable images instead of adversarial noise. It is the canonical reference for vision CNNs, and its direct transfer to language-model interpretability is limited.',
  'Chris Olah, Alexander Mordvintsev, Ludwig Schubert',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Feature Visualization', 'Interpretability', 'Optimization', 'Vision Models'],
  '25 min read',
  '2017-11-07',
  'Distill',
  'https://distill.pub/2017/feature-visualization/',
  'assets/img/covers/real/distill-feature-visualization.jpg',
  'Real cover from og:image',
  'cover',
  'published',
  false
),
(
  'deepmind-specification-gaming-flip-side',
  'Specification Gaming: The Flip Side of AI Ingenuity',
  'Victoria Krakovna and colleagues catalog roughly 60 examples of specification gaming — agents satisfying the literal reward while violating its intent, from boat-racing loops to simulated-physics exploits — and explain why RL makes such behavior systematic rather than anecdotal. The examples are pre-LLM-era RL, but the taxonomy remains the canonical frame newer safety work builds on.',
  'Victoria Krakovna et al.',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Specification Gaming', 'Reward Hacking', 'RL Safety', 'Alignment'],
  '10 min read',
  '2020-04-21',
  'Google DeepMind Blog',
  'https://deepmind.google/blog/specification-gaming-the-flip-side-of-ai-ingenuity/',
  'assets/img/covers/real/deepmind-specification-gaming-flip-side.webp',
  'Real cover from og:image',
  'cover',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;

select id, title, category, publish_date, status
from public.blogs
where id in (
  'lei-mao-system-performance-optimizations',
  'modal-sota-speculative-decoding',
  'google-gemma-4-quantization-aware-training',
  'jax-ml-how-to-scale-your-model',
  'kipply-transformer-inference-arithmetic',
  'horace-he-making-deep-learning-go-brrrr',
  'nvidia-mastering-llm-inference-optimization',
  'google-looking-back-speculative-decoding',
  'pytorch-gpt-fast-native-acceleration',
  'uk-aisi-control-red-team-frontier-monitors',
  'redwood-prioritizing-threats-ai-control',
  'openai-safety-alignment-long-horizon-models',
  'anthropic-off-switch-dual-use-knowledge',
  'anthropic-trustworthy-agents-in-practice',
  'deepmind-protecting-people-harmful-manipulation',
  'anthropic-diff-tool-behavioral-differences',
  'distill-advex-bugs-discussion',
  'distill-circuits-thread',
  'openai-deliberative-alignment',
  'distill-feature-visualization',
  'deepmind-specification-gaming-flip-side'
)
order by publish_date desc, id asc;
