-- Quality pass: Efficient AI, Trustworthy AI, Research Craft, Frontier.
-- Run in the Supabase SQL Editor for the public BlogrXiv project.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'nvidia-cuda-kernel-fusion',
  'Kernel Fusion in NVIDIA CUDA: Optimizing Memory Traffic and Launch Overhead',
  'Daniel Rodriguez uses Nsight traces to compare hand-written CUDA, torch.compile, and explicit fusion, showing when fusion cuts memory traffic versus when launch overhead still dominates. The measurements are single-GPU microbenchmarks, so the ranking should not be treated as a multi-node serving result.',
  'Daniel Rodriguez',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['CUDA','Kernel Fusion','Nsight','Memory Bandwidth'],
  '12 min read',
  '2026-07-10',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/kernel-fusion-in-nvidia-cuda-optimizing-memory-traffic-and-launch-overhead/',
  'assets/img/covers/real/nvidia-cuda-kernel-fusion.webp',
  'Kernel Fusion in NVIDIA CUDA: Optimizing Memory Traffic and Launch Overhead article cover',
  'cover',
  'published',
  false
),
(
  'lei-mao-system-performance-optimizations',
  'System Performance Optimizations',
  'Lei Mao walks through practical systems optimizations for deep learning workloads, connecting CPU/GPU overlap, memory layout, and kernel choices to observable latency. It is an independent engineering note rather than a controlled multi-hardware study.',
  'Lei Mao',
  'https://www.google.com/s2/favicons?domain=leimao.github.io&sz=128',
  'Efficient AI',
  array['Systems','Performance','Profiling','Deep Learning'],
  '14 min read',
  '2026-01-15',
  'Lei Mao',
  'https://leimao.github.io/article/System-Performance-Optimizations/',
  'assets/img/covers/real/lei-mao-system-performance-optimizations.png',
  'System Performance Optimizations article cover',
  'cover',
  'published',
  false
),
(
  'modal-sota-speculative-decoding',
  'Achieve State-of-the-Art Inference Latencies with Speculative Decoding',
  'Charles Frye and Shankha Biswas report production measurements of speculative decoding, including draft-model choice, acceptance rates, and end-to-end latency rather than token-throughput alone. Gains remain tied to the serving stack and draft/target pairing under test.',
  'Charles Frye and Shankha Biswas',
  'https://www.google.com/s2/favicons?domain=modal.com&sz=128',
  'Efficient AI',
  array['Speculative Decoding','Inference','Latency','Serving'],
  '11 min read',
  '2026-03-01',
  'Modal',
  'https://modal.com/blog/achieve-sota-specdec',
  'assets/img/covers/real/modal-sota-speculative-decoding.png',
  'Achieve State-of-the-Art Inference Latencies with Speculative Decoding article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-tensorrt-llm-public-release',
  'Optimizing Inference on LLMs with TensorRT-LLM',
  'NVIDIA documents TensorRT-LLM''s public inference stack: kernel selection, in-flight batching, and quantization paths intended to turn a trained decoder into a deployable engine. The performance claims are NVIDIA-hardware specific and should be re-benchmarked on other runtimes.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['TensorRT-LLM','Inference','Quantization','Serving'],
  '10 min read',
  '2023-10-17',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/',
  'assets/img/covers/real/nvidia-tensorrt-llm-public-release.png',
  'Optimizing Inference on LLMs with TensorRT-LLM article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-tensorrt-kv-cache-reuse',
  'New KV Cache Reuse Optimizations in TensorRT-LLM',
  'This note explains how prefix and block reuse in TensorRT-LLM reduce KV-cache traffic for multi-turn and batched decode. The speedups assume compatible cache layouts and will shrink when prefixes rarely overlap.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['KV Cache','TensorRT-LLM','Prefix Caching','Inference'],
  '8 min read',
  '2024-06-01',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/introducing-new-kv-cache-reuse-optimizations-in-nvidia-tensorrt-llm/',
  'assets/img/covers/real/nvidia-tensorrt-kv-cache-reuse.jpg',
  'New KV Cache Reuse Optimizations in TensorRT-LLM article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-nvfp4-kv-cache',
  'NVFP4 KV Cache for Long Context and Large Batches',
  'NVIDIA describes NVFP4 KV-cache quantization for long-context and large-batch decode, trading a controlled precision loss for memory capacity and bandwidth. Results are reported on NVIDIA GPUs and should not be copied onto other low-bit formats without re-measurement.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['NVFP4','KV Cache','Quantization','Long Context'],
  '9 min read',
  '2025-11-01',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/optimizing-inference-for-long-context-and-large-batch-sizes-with-nvfp4-kv-cache/',
  'assets/img/covers/real/nvidia-nvfp4-kv-cache.png',
  'NVFP4 KV Cache for Long Context and Large Batches article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-tensorrt-speculative-decoding-llama',
  'TensorRT-LLM Speculative Decoding',
  'NVIDIA reports speculative decoding inside TensorRT-LLM on Llama 3.3 70B, including draft acceptance and throughput multipliers versus autoregressive decode. The 3× figure is configuration-specific and depends on draft quality plus batch shape.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['Speculative Decoding','Llama','TensorRT-LLM','Throughput'],
  '8 min read',
  '2025-01-15',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/boost-llama-3-3-70b-inference-throughput-3x-with-nvidia-tensorrt-llm-speculative-decoding/',
  'assets/img/covers/real/nvidia-tensorrt-speculative-decoding-llama.png',
  'TensorRT-LLM Speculative Decoding article cover',
  'cover',
  'published',
  false
),
(
  'deepspeed-ulysses-offload',
  'DeepSpeed Ulysses-Offload',
  'The DeepSpeed tutorial presents Ulysses-Offload as a sequence-parallel recipe that shards attention along sequence and offloads activation pressure for long-context training. It is a systems recipe, not a new modeling result, and assumes the DeepSpeed/Ulysses software stack.',
  'Microsoft DeepSpeed',
  'https://www.google.com/s2/favicons?domain=deepspeed.ai&sz=128',
  'Efficient AI',
  array['DeepSpeed','Sequence Parallelism','Long Context','Offloading'],
  '16 min read',
  '2025-06-01',
  'DeepSpeed',
  'https://www.deepspeed.ai/tutorials/ulysses-offload/',
  'https://www.google.com/s2/favicons?domain=deepspeed.ai&sz=128',
  'DeepSpeed Ulysses-Offload article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-peft-parameter-efficient-fine-tuning',
  'Parameter-Efficient Fine-Tuning with PEFT',
  'Hugging Face introduces PEFT as a library for LoRA, prefix tuning, and related adapters, emphasizing memory savings versus full fine-tuning. The post is a systems and API guide; adapter quality still depends on rank, data, and task.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['PEFT','LoRA','Fine-tuning','Adapters'],
  '10 min read',
  '2023-02-10',
  'Hugging Face Blog',
  'https://huggingface.co/blog/peft',
  'assets/img/covers/real/huggingface-peft-parameter-efficient-fine-tuning.png',
  'Parameter-Efficient Fine-Tuning with PEFT article cover',
  'cover',
  'published',
  false
),
(
  'raschka-lora-and-dora-from-scratch',
  'LoRA and DoRA From Scratch',
  'Sebastian Raschka derives LoRA and DoRA as low-rank update rules, then implements them so a reader can see where magnitude and direction are decoupled. It is a teaching derivation, not a large-scale adapter bake-off.',
  'Sebastian Raschka',
  'https://www.google.com/s2/favicons?domain=magazine.sebastianraschka.com&sz=128',
  'Efficient AI',
  array['LoRA','DoRA','Fine-tuning','Low-Rank Adaptation'],
  '22 min read',
  '2024-11-12',
  'Ahead of AI',
  'https://magazine.sebastianraschka.com/p/lora-and-dora-from-scratch',
  'assets/img/covers/real/raschka-lora-and-dora-from-scratch.png',
  'LoRA and DoRA From Scratch article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-assisted-generation',
  'Assisted Generation: A New Direction Toward Low-Latency Text Generation',
  'Hugging Face explains assisted generation as a draft-then-verify decoding method that reduces sequential steps without changing the target model''s distribution when verification is exact. Latency gains depend on draft acceptance and are smaller on already-batched decode.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['Assisted Generation','Speculative Decoding','Latency','Transformers'],
  '12 min read',
  '2023-06-23',
  'Hugging Face Blog',
  'https://huggingface.co/blog/assisted-generation',
  'assets/img/covers/real/huggingface-assisted-generation.png',
  'Assisted Generation: A New Direction Toward Low-Latency Text Generation article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-4bit-transformers-bitsandbytes',
  'Making LLMs Even More Accessible with 4-Bit Quantization',
  'Hugging Face documents 4-bit bitsandbytes quantization in Transformers, covering QLoRA-style loading and the memory arithmetic that makes large models fit on a single GPU. Accuracy trade-offs are task-dependent and not claimed to be free.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['Quantization','bitsandbytes','QLoRA','4-bit'],
  '9 min read',
  '2023-05-05',
  'Hugging Face Blog',
  'https://huggingface.co/blog/4bit-transformers-bitsandbytes',
  'assets/img/covers/real/huggingface-4bit-transformers-bitsandbytes.png',
  'Making LLMs Even More Accessible with 4-Bit Quantization article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-torch-attention-profile',
  'Profiling PyTorch: Attention Kernels',
  'A PyTorch profiling walkthrough that isolates attention kernel time, memory traffic, and the difference between naive and fused implementations. It is a teaching profile, not a claim about every production attention backend.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['PyTorch','Attention','Profiling','Kernels'],
  '11 min read',
  '2026-07-10',
  'Hugging Face Blog',
  'https://huggingface.co/blog/torch-attention-profile',
  'assets/img/covers/real/huggingface-torch-attention-profile.png',
  'Profiling PyTorch: Attention Kernels article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-native-speed-vllm-transformers-backend',
  'Native-Speed vLLM with the Transformers Backend',
  'Hugging Face describes running Transformers models through vLLM at native kernel speed, reducing the historical gap between research checkpoints and serving engines. Throughput still depends on the vLLM version, hardware, and whether custom modeling code maps cleanly.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['vLLM','Transformers','Serving','Inference'],
  '8 min read',
  '2026-07-08',
  'Hugging Face Blog',
  'https://huggingface.co/blog/native-speed-vllm-transformers-backend',
  'assets/img/covers/real/huggingface-native-speed-vllm-transformers-backend.png',
  'Native-Speed vLLM with the Transformers Backend article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-pushing-intelligence-to-4-bit',
  'Pushing Intelligence to 4-Bit',
  'NVIDIA Research discusses 4-bit inference as a systems and accuracy problem, covering KV-cache and weight quantization under long context. The essay is hardware-aware; bit-width conclusions may not transfer to non-NVIDIA kernels.',
  'NVIDIA Research',
  'https://www.google.com/s2/favicons?domain=research.nvidia.com&sz=128',
  'Efficient AI',
  array['4-bit','Quantization','Inference','KV Cache'],
  '10 min read',
  '2026-06-16',
  'NVIDIA Research',
  'https://research.nvidia.com/labs/eai/blogs/pushing-intelligence-to-4-bit/',
  'assets/img/covers/real/nvidia-pushing-intelligence-to-4-bit.png',
  'Pushing Intelligence to 4-Bit article cover',
  'cover',
  'published',
  false
),
(
  'google-gemini-nano-frozen-mtp',
  'Accelerating Gemini Nano with Frozen Multi-Token Prediction',
  'Google Research explains frozen multi-token prediction as an on-device decode accelerator for Gemini Nano on Pixel, keeping a frozen draft head rather than training a separate speculator. The latency numbers are device-specific and tied to the Pixel stack.',
  'Google Research',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Efficient AI',
  array['Multi-Token Prediction','On-Device','Gemini Nano','Speculative Decoding'],
  '9 min read',
  '2026-06-26',
  'Google Research',
  'https://research.google/blog/accelerating-gemini-nano-models-on-pixel-with-frozen-multi-token-prediction/',
  'assets/img/covers/real/google-gemini-nano-frozen-mtp.jpg',
  'Accelerating Gemini Nano with Frozen Multi-Token Prediction article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-kv-cache-compression-infra',
  'KV-Cache Compression and Its Infrastructure Problems',
  'NVIDIA Research treats KV-cache compression as an infrastructure problem: layout, paging, and quantizers interact with batching in ways a paper ablation can hide. The post is diagnostic; it does not offer a single universally best compressor.',
  'NVIDIA Research',
  'https://www.google.com/s2/favicons?domain=research.nvidia.com&sz=128',
  'Efficient AI',
  array['KV Cache','Compression','Serving','Infrastructure'],
  '11 min read',
  '2026-06-12',
  'NVIDIA Research',
  'https://research.nvidia.com/labs/eai/post/kv-cache-compression-and-its-infra-problems/',
  'https://www.google.com/s2/favicons?domain=research.nvidia.com&sz=128',
  'KV-Cache Compression and Its Infrastructure Problems article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-optimum-intel-v2',
  'Optimum Intel 2.0',
  'Jeff Boudier presents Optimum Intel 2.0 as a path from Transformers checkpoints to Intel-optimized inference, covering quantization and runtime backends. Performance claims are Intel-hardware specific.',
  'Jeff Boudier',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['Optimum','Intel','Quantization','CPU Inference'],
  '7 min read',
  '2026-06-11',
  'Hugging Face Blog',
  'https://huggingface.co/blog/jeffboudier/optimum-intel-v2',
  'assets/img/covers/real/huggingface-optimum-intel-v2.png',
  'Optimum Intel 2.0 article cover',
  'cover',
  'published',
  false
),
(
  'huggingface-torch-mlp-fusion',
  'Profiling in PyTorch, Part 2: From nn.Linear to a Fused MLP',
  'The follow-up profile traces an MLP from nn.Linear through fusion, showing how kernel launch and memory traffic change once pointwise ops are merged. It is a teaching example on a single device class.',
  'Hugging Face',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Efficient AI',
  array['PyTorch','Fusion','MLP','Profiling'],
  '12 min read',
  '2026-06-11',
  'Hugging Face Blog',
  'https://huggingface.co/blog/torch-mlp-fusion',
  'assets/img/covers/real/huggingface-torch-mlp-fusion.png',
  'Profiling in PyTorch, Part 2: From nn.Linear to a Fused MLP article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-thunderkittens-2',
  'ThunderKittens 2.0: Making Kernels Faster and Easier to Write',
  'Stanford Hazy Research updates ThunderKittens as an embedded DSL for AI kernels, aiming to keep Tensor-core performance without full CUDA specialist workflows. Ease-of-use claims should be read against the team''s hardware and kernel set.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['ThunderKittens','Kernels','CUDA','DSL'],
  '13 min read',
  '2026-02-19',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2026-02-19-tk-2',
  'assets/img/covers/real/hazyresearch-thunderkittens-2.png',
  'ThunderKittens 2.0: Making Kernels Faster and Easier to Write article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-thunderkittens-dsl',
  'ThunderKittens: A Simple Embedded DSL for AI Kernels',
  'The original ThunderKittens note argues that a small embedded DSL can hit competitive attention and GEMM performance by exposing tiling primitives instead of hiding the GPU. It is a research systems essay, not a drop-in replacement for every vendor kernel.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['ThunderKittens','Kernels','Attention','GPU'],
  '12 min read',
  '2024-05-12',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2024-05-12-quick-tk',
  'assets/img/covers/real/hazyresearch-thunderkittens-dsl.png',
  'ThunderKittens: A Simple Embedded DSL for AI Kernels article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-minions-on-device-cloud',
  'Minions: Cost-Efficient Collaboration Between On-Device and Cloud Language Models',
  'Hazy Research describes Minions as a protocol for splitting work between on-device and cloud LMs to cut cost while preserving task quality. The savings depend on which subtasks can be locally filtered before a cloud call.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['On-Device','Cloud','Cost','Language Models'],
  '11 min read',
  '2025-02-24',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2025-02-24-minions',
  'assets/img/covers/real/hazyresearch-minions-on-device-cloud.png',
  'Minions: Cost-Efficient Collaboration Between On-Device and Cloud Language Models article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-lolcats-part-2',
  'LoLCATs Part 2: Low-Rank Linearizing of LLMs',
  'Part 2 of LoLCATs develops low-rank linearization as a way to convert softmax attention models toward linear-time forms without a full retrain. Quality gaps versus the original Transformer remain task-dependent.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['Linear Attention','Low-Rank','LoLCATs','Architecture'],
  '14 min read',
  '2024-10-14',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2024-10-14-lolcats-p2',
  'assets/img/covers/real/hazyresearch-lolcats-part-2.png',
  'LoLCATs Part 2: Low-Rank Linearizing of LLMs article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-just-read-twice',
  'Just Read Twice: Closing the Recall Gap for Recurrent Language Models',
  'Just Read Twice proposes a simple two-pass recipe to recover associative recall in recurrent language models that otherwise lag Transformers. The gap closed here is recall-centric and does not automatically transfer to every long-context benchmark.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['Recurrent LMs','Recall','Long Context','Architecture'],
  '12 min read',
  '2024-07-01',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2024-07-01-jrt',
  'assets/img/covers/real/hazyresearch-just-read-twice.png',
  'Just Read Twice: Closing the Recall Gap for Recurrent Language Models article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-based-one-year-later',
  'BASED One Year Later: Exploring the State of Linear Attention',
  'A retrospective on BASED and linear attention, revisiting what held up empirically and where softmax attention still wins. It is a field-status essay, not a new architecture announcement.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['Linear Attention','BASED','Architecture','Retrospective'],
  '13 min read',
  '2025-03-24',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2025-03-24-based-retro',
  'assets/img/covers/real/hazyresearch-based-one-year-later.png',
  'BASED One Year Later: Exploring the State of Linear Attention article cover',
  'cover',
  'published',
  false
),
(
  'epoch-inference-economics-of-language-models',
  'Inference Economics of Language Models',
  'Epoch AI models inference cost as a function of parameters, tokens, hardware, and utilization, making the distinction between training-time and serving-time economics explicit. The estimates inherit Epoch''s hardware-price and utilization assumptions.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Efficient AI',
  array['Inference Economics','Cost','Scaling','Serving'],
  '25 min read',
  '2024-12-01',
  'Epoch AI',
  'https://epoch.ai/publications/inference-economics-of-language-models',
  'assets/img/covers/real/epoch-inference-economics-of-language-models.png',
  'Inference Economics of Language Models article cover',
  'cover',
  'published',
  false
),
(
  'epoch-is-a-compute-crunch-coming',
  'Is a Compute Crunch Coming?',
  'Epoch AI examines whether supply of AI accelerators and power can keep pace with demand, separating chip fabrication, packaging, and datacenter constraints. It is a scenario analysis, not a point forecast.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Efficient AI',
  array['Compute','Hardware','Forecasting','Infrastructure'],
  '18 min read',
  '2024-08-01',
  'Epoch AI',
  'https://epoch.ai/gradient-updates/is-a-compute-crunch-coming',
  'assets/img/covers/real/epoch-is-a-compute-crunch-coming.png',
  'Is a Compute Crunch Coming? article cover',
  'cover',
  'published',
  false
),
(
  'bair-tiny-agent-function-calling-edge',
  'TinyAgent: Function Calling at the Edge',
  'BAIR presents TinyAgent as a small on-device agent that performs function calling without round-tripping every step to a frontier cloud model. Edge accuracy and tool coverage remain narrower than large-server agents.',
  'BAIR',
  'https://www.google.com/s2/favicons?domain=bair.berkeley.edu&sz=128',
  'Efficient AI',
  array['On-Device','Function Calling','Agents','Edge'],
  '10 min read',
  '2024-05-29',
  'BAIR',
  'https://bair.berkeley.edu/blog/2024/05/29/tiny-agent/',
  'assets/img/covers/real/bair-tiny-agent-function-calling-edge.png',
  'TinyAgent: Function Calling at the Edge article cover',
  'cover',
  'published',
  false
),
(
  'jax-how-to-scale-your-model',
  'How to Scale Your Model',
  'The JAX/DeepMind scaling book is a first-principles curriculum from clusters and rooflines through sharding and serving, intended as a single entry point rather than a chapter dump. Read it as a systems textbook; hardware numbers will age.',
  'Google DeepMind / JAX team',
  'https://www.google.com/s2/favicons?domain=jax-ml.github.io&sz=128',
  'Efficient AI',
  array['Scaling','Parallelism','JAX','Roofline'],
  '90 min read',
  '2025-01-15',
  'JAX Scaling Book',
  'https://jax-ml.github.io/scaling-book/',
  'assets/img/covers/real/jax-how-to-scale-your-model.png',
  'How to Scale Your Model article cover',
  'cover',
  'published',
  false
),
(
  'kipply-transformer-inference-arithmetic',
  'Transformer Inference Arithmetic',
  'Kipply builds a hand-computable model of Transformer inference from KV-cache bytes, weight traffic, tensor-parallel communication, batch size, and FLOPs. The arithmetic is a planning tool, not a substitute for a profiler on a real engine.',
  'Kipply',
  'https://www.google.com/s2/favicons?domain=kipp.ly&sz=128',
  'Efficient AI',
  array['Inference','KV Cache','Tensor Parallel','Performance Model'],
  '20 min read',
  '2022-07-12',
  'Kipply',
  'https://kipp.ly/p/transformer-inference-arithmetic',
  'assets/img/covers/real/kipply-transformer-inference-arithmetic.png',
  'Transformer Inference Arithmetic article cover',
  'cover',
  'published',
  false
),
(
  'horace-he-making-deep-learning-go-brrrr',
  'Making Deep Learning Go Brrrr From First Principles',
  'Horace He explains why models stall using a compute-bound, memory-bandwidth-bound, and overhead-bound trichotomy, then shows where compilers can and cannot help. The essay is diagnostic; it does not claim a single kernel will always win.',
  'Horace He',
  'https://www.google.com/s2/favicons?domain=horace.io&sz=128',
  'Efficient AI',
  array['Performance','Memory Bandwidth','Compilers','PyTorch'],
  '25 min read',
  '2022-04-01',
  'Horace He',
  'https://horace.io/brrr_intro.html',
  'https://www.google.com/s2/favicons?domain=horace.io&sz=128',
  'Making Deep Learning Go Brrrr From First Principles article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-mastering-llm-inference-optimization',
  'Mastering LLM Techniques: Inference Optimization',
  'NVIDIA surveys prefill versus decode, KV cache, MQA/GQA, FlashAttention, PagedAttention, and parallelism as a practitioner map of inference optimization. It is a technique catalog; numbers are illustrative of the NVIDIA stack.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['Inference','FlashAttention','PagedAttention','GQA'],
  '16 min read',
  '2023-11-15',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/mastering-llm-techniques-inference-optimization/',
  'assets/img/covers/real/nvidia-mastering-llm-inference-optimization.png',
  'Mastering LLM Techniques: Inference Optimization article cover',
  'cover',
  'published',
  false
),
(
  'pytorch-accelerating-llm-inference-gemlite',
  'Accelerating LLM Inference with GemLite, TorchAO and SGLang',
  'PyTorch, Mobius Labs, and SGLang combine low-bit kernels, TorchAO quantization, and a serving engine in a reproducible end-to-end recipe. Speedups are for the reported model and GPU pair and should be re-run before citing as general.',
  'PyTorch / Mobius Labs / SGLang',
  'https://www.google.com/s2/favicons?domain=pytorch.org&sz=128',
  'Efficient AI',
  array['TorchAO','SGLang','Quantization','Serving'],
  '12 min read',
  '2025-03-01',
  'PyTorch Blog',
  'https://pytorch.org/blog/accelerating-llm-inference/',
  'https://www.google.com/s2/favicons?domain=pytorch.org&sz=128',
  'Accelerating LLM Inference with GemLite, TorchAO and SGLang article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-flashattention-long-sequences',
  'FlashAttention: Fast Transformer Training with Long Sequences',
  'The FlashAttention blog derives IO-aware attention that tiles softmax without materializing the full N×N matrix, unlocking longer training sequences. Speedups are largest when attention is memory-bound on the measured GPUs.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['FlashAttention','Attention','IO-Awareness','Training'],
  '14 min read',
  '2023-01-12',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2023-01-12-flashattention-long-sequences',
  'assets/img/covers/real/hazyresearch-flashattention-long-sequences.png',
  'FlashAttention: Fast Transformer Training with Long Sequences article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-flashfftconv',
  'FlashFFTConv: Efficient Convolutions for Long Sequences with Tensor Cores',
  'FlashFFTConv fuses FFT convolution onto Tensor Cores so long-sequence convolutional models can approach attention-class hardware utilization. Gains assume convolution-heavy architectures rather than vanilla Transformers.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['FFT','Convolution','Tensor Cores','Long Sequences'],
  '12 min read',
  '2023-11-13',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2023-11-13-flashfftconv',
  'assets/img/covers/real/hazyresearch-flashfftconv.png',
  'FlashFFTConv: Efficient Convolutions for Long Sequences with Tensor Cores article cover',
  'cover',
  'published',
  false
),
(
  'google-looking-back-speculative-decoding',
  'Looking back at speculative decoding',
  'Google Research revisits speculative decoding after it entered production stacks, clarifying which assumptions (draft quality, rejection sampling, batching) survived contact with serving. It is a retrospective, not a new algorithm paper.',
  'Google Research',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Efficient AI',
  array['Speculative Decoding','Inference','Retrospective','Serving'],
  '10 min read',
  '2024-11-01',
  'Google Research',
  'https://research.google/blog/looking-back-at-speculative-decoding/',
  'assets/img/covers/real/google-looking-back-speculative-decoding.jpg',
  'Looking back at speculative decoding article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-flashattention-2',
  'FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning',
  'FlashAttention-2 re-partitions work across warps and reduces non-matmul overhead relative to the first FlashAttention, improving occupancy on long sequences. As with FA1, the gains are GPU- and sequence-length dependent.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Efficient AI',
  array['FlashAttention-2','Attention','Parallelism','GPU'],
  '12 min read',
  '2023-07-17',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2023-07-17-flash2',
  'assets/img/covers/real/hazyresearch-flashattention-2.png',
  'FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning article cover',
  'cover',
  'published',
  false
),
(
  'google-gspmd-parallelization',
  'GSPMD: General and Scalable Parallelization for ML Computation Graphs',
  'Google Research presents GSPMD as a compiler-level sharding system that annotates tensors once and generates data, operator, and pipeline parallel programs. It is a 2021 systems result; later stacks (XLA, JAX) absorbed related ideas.',
  'Google Research',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Efficient AI',
  array['GSPMD','Sharding','XLA','Parallelism'],
  '11 min read',
  '2021-06-01',
  'Google Research',
  'https://research.google/blog/general-and-scalable-parallelization-for-neural-networks/',
  'assets/img/covers/real/google-gspmd-parallelization.jpg',
  'GSPMD: General and Scalable Parallelization for ML Computation Graphs article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-megatron-trillion-parameters',
  'Scaling Language Model Training to a Trillion Parameters Using Megatron',
  'NVIDIA describes Megatron-style tensor, pipeline, and data parallelism that made trillion-parameter training tractable on their clusters. The recipe is historical and cluster-specific; modern successors changed several partitioning defaults.',
  'NVIDIA',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Efficient AI',
  array['Megatron','Tensor Parallel','Pipeline Parallel','Training'],
  '12 min read',
  '2021-10-01',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/scaling-language-model-training-to-a-trillion-parameters-using-megatron/',
  'assets/img/covers/real/nvidia-megatron-trillion-parameters.png',
  'Scaling Language Model Training to a Trillion Parameters Using Megatron article cover',
  'cover',
  'published',
  false
),
(
  'uk-aisi-control-red-team-frontier-monitors',
  'How our new Control Red Team is stress-testing frontier monitors',
  'UK AISI''s Control Red Team uses evolutionary search against frontier-lab monitors to find monitor failures under optimistic attacker access. The work is an early stress test; optimizer privileges exceed many realistic attackers, so failure rates are not incident rates.',
  'UK AISI Control Red Team',
  'https://www.google.com/s2/favicons?domain=aisi.gov.uk&sz=128',
  'Trustworthy AI',
  array['AI Control','Red Teaming','Monitoring','Evaluations'],
  '14 min read',
  '2026-07-23',
  'UK AI Security Institute',
  'https://www.aisi.gov.uk/blog/how-our-new-control-red-team-is-stress-testing-frontier-monitors',
  'assets/img/covers/real/uk-aisi-control-red-team-frontier-monitors.png',
  'How our new Control Red Team is stress-testing frontier monitors article cover',
  'cover',
  'published',
  false
),
(
  'redwood-prioritizing-threats-ai-control',
  'Prioritizing Threats for AI Control',
  'Ryan Greenblatt argues for ranking AI-control threats by a combination of plausibility, damage, and tractability rather than treating every speculative failure equally. It is a threat-model essay, not an empirical incident study.',
  'Ryan Greenblatt',
  'https://www.google.com/s2/favicons?domain=blog.redwoodresearch.org&sz=128',
  'Trustworthy AI',
  array['AI Control','Threat Model','Prioritization','Safety'],
  '16 min read',
  '2025-06-01',
  'Redwood Research',
  'https://blog.redwoodresearch.org/p/prioritizing-threats-for-ai-control',
  'assets/img/covers/real/redwood-prioritizing-threats-ai-control.jpg',
  'Prioritizing Threats for AI Control article cover',
  'cover',
  'published',
  false
),
(
  'deepmind-frontier-safety-framework',
  'Strengthening Our Frontier Safety Framework',
  'Google DeepMind updates its frontier safety framework with sharper capability thresholds and evaluation commitments. The post is a policy-and-process note; independent auditors cannot verify every internal eval from the blog alone.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Frontier Safety','Evaluations','Governance','DeepMind'],
  '9 min read',
  '2025-02-04',
  'Google DeepMind',
  'https://deepmind.google/blog/strengthening-our-frontier-safety-framework/',
  'assets/img/covers/real/deepmind-frontier-safety-framework.png',
  'Strengthening Our Frontier Safety Framework article cover',
  'cover',
  'published',
  false
),
(
  'deepmind-early-warning-system-novel-ai-risks',
  'An Early Warning System for Novel AI Risks',
  'DeepMind describes an early-warning posture for novel AI risks: monitoring capability jumps, misuse pathways, and evaluation gaps before they become incidents. It is a program description rather than a validated detector with published ROC numbers.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Early Warning','Risk','Monitoring','Governance'],
  '8 min read',
  '2024-10-01',
  'Google DeepMind',
  'https://deepmind.google/blog/an-early-warning-system-for-novel-ai-risks/',
  'assets/img/covers/real/deepmind-early-warning-system-novel-ai-risks.png',
  'An Early Warning System for Novel AI Risks article cover',
  'cover',
  'published',
  false
),
(
  'openai-trustworthy-third-party-evaluations',
  'Trustworthy Third-Party Evaluations',
  'OpenAI outlines conditions under which third-party model evaluations can be trusted: access, independence, documentation, and limits on training on the eval itself. The post sets a bar; it does not publish a full open eval harness.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Evaluations','Third Party','Governance','Transparency'],
  '10 min read',
  '2025-03-01',
  'OpenAI',
  'https://openai.com/index/trustworthy-third-party-evaluations-foundations/',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy Third-Party Evaluations article cover',
  'cover',
  'published',
  false
),
(
  'openai-hf-model-evaluation-security-incident',
  'Hugging Face Model Evaluation Security Incident',
  'OpenAI reports a security incident around Hugging Face model evaluation infrastructure, treating eval platforms as part of the trusted computing base. The write-up is an incident note; readers should check Hugging Face''s own timeline for operational details.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Security','Evaluations','Incident','Infrastructure'],
  '7 min read',
  '2026-07-21',
  'OpenAI',
  'https://openai.com/index/hugging-face-model-evaluation-security-incident/',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Hugging Face Model Evaluation Security Incident article cover',
  'cover',
  'published',
  false
),
(
  'openai-safety-alignment-long-horizon-models',
  'Safety and Alignment in an Era of Long-Horizon Models',
  'OpenAI discusses how long-horizon agents change alignment: specification, monitoring, and evaluation all stretch when tasks last hours rather than a single turn. It is a research-program essay rather than a finished control theorem.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Alignment','Long-Horizon','Agents','Safety'],
  '12 min read',
  '2026-07-20',
  'OpenAI',
  'https://openai.com/index/safety-alignment-long-horizon-models/',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Safety and Alignment in an Era of Long-Horizon Models article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-off-switch-dual-use',
  'An Off Switch for Dual-Use Knowledge in AI Models',
  'Anthropic describes methods for suppressing dual-use knowledge so a model can refuse or forget dangerous procedures without collapsing general capability. The off switch is evaluated in lab settings and is not a guarantee against determined jailbreaks.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Dual-Use','Unlearning','Refusal','Safety'],
  '13 min read',
  '2026-07-08',
  'Anthropic',
  'https://www.anthropic.com/research/off-switch-dual-use',
  'assets/img/covers/real/anthropic-off-switch-dual-use.png',
  'An Off Switch for Dual-Use Knowledge in AI Models article cover',
  'cover',
  'published',
  false
),
(
  'deepmind-securing-internal-systems-ai-agents',
  'Securing Internal Systems against Increasingly Capable and Imperfectly Aligned AI',
  'DeepMind argues that internal tools must assume agents will be capable and imperfectly aligned, so sandboxing, least privilege, and monitoring become first-class design constraints. The post is a security architecture note, not a public red-team dataset.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Agent Security','Sandboxing','Least Privilege','Monitoring'],
  '11 min read',
  '2026-06-18',
  'Google DeepMind',
  'https://deepmind.google/blog/securing-the-future-of-ai-agents/',
  'assets/img/covers/real/deepmind-securing-internal-systems-ai-agents.png',
  'Securing Internal Systems against Increasingly Capable and Imperfectly Aligned AI article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-measuring-n-day-exploits',
  'Measuring LLMs’ Impact on N-Day Exploits',
  'Anthropic measures whether frontier models change the cost of exploiting known n-day vulnerabilities, separating assistance from fully autonomous exploitation. The result is an eval snapshot and should not be read as a live cyber-risk dashboard.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Cybersecurity','N-day','Evaluations','Risk'],
  '12 min read',
  '2026-06-08',
  'Anthropic',
  'https://www.anthropic.com/research/n-days',
  'assets/img/covers/real/anthropic-measuring-n-day-exploits.jpg',
  'Measuring LLMs’ Impact on N-Day Exploits article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-mapping-ai-enabled-cyber-threats',
  'Mapping AI-Enabled Cyber Threats',
  'Anthropic''s attack navigator maps how language models can assist along a cyber kill chain, distinguishing reconnaissance, exploit development, and operations. It is a taxonomy for defenders, not a proof of observed campaigns.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Cybersecurity','Threat Model','Kill Chain','Risk'],
  '11 min read',
  '2026-06-03',
  'Anthropic',
  'https://www.anthropic.com/research/attack-navigator',
  'assets/img/covers/real/anthropic-mapping-ai-enabled-cyber-threats.jpg',
  'Mapping AI-Enabled Cyber Threats article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-trustworthy-agents-in-practice',
  'Trustworthy Agents in Practice',
  'Anthropic collects practical controls for agents that use tools: permissioning, logging, human approval, and evaluation loops. The guidance is operational; it does not claim a solved alignment problem.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Agents','Permissions','Monitoring','Safety'],
  '12 min read',
  '2026-04-09',
  'Anthropic',
  'https://www.anthropic.com/research/trustworthy-agents',
  'assets/img/covers/real/anthropic-trustworthy-agents-in-practice.png',
  'Trustworthy Agents in Practice article cover',
  'cover',
  'published',
  false
),
(
  'deepmind-protecting-people-harmful-manipulation',
  'Protecting People from Harmful Manipulation',
  'DeepMind discusses harmful manipulation as a product and model-behavior problem, including evaluation of persuasive failure modes. The post mixes research and policy and is not a complete taxonomy of influence attacks.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Manipulation','Safety','Evaluations','Policy'],
  '9 min read',
  '2026-03-26',
  'Google DeepMind',
  'https://deepmind.google/blog/protecting-people-from-harmful-manipulation/',
  'assets/img/covers/real/deepmind-protecting-people-harmful-manipulation.png',
  'Protecting People from Harmful Manipulation article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-diff-tool-behavioral-differences',
  'A “Diff” Tool for AI: Finding Behavioral Differences in New Models',
  'Anthropic describes a behavioral diff tool that surfaces how a new model disagrees with a predecessor on the same prompts, turning regression hunting into a first-class eval. Coverage is only as good as the prompt set and raters behind the diff.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Model Diff','Evaluations','Regression','Behavior'],
  '10 min read',
  '2026-03-13',
  'Anthropic',
  'https://www.anthropic.com/research/diff-tool',
  'assets/img/covers/real/anthropic-diff-tool-behavioral-differences.png',
  'A “Diff” Tool for AI: Finding Behavioral Differences in New Models article cover',
  'cover',
  'published',
  false
),
(
  'distill-advex-bugs-discussion',
  'Adversarial Examples Are Not Bugs, They Are Features — Discussion',
  'Distill hosts a structured discussion of whether adversarial examples are bugs or useful features of the data geometry, collecting critiques and replies around the Ilyas et al. claim. Read it as a 2019 debate, not a settled 2026 result.',
  'Distill',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Adversarial Examples','Robustness','Features','Debate'],
  '30 min read',
  '2019-08-06',
  'Distill',
  'https://distill.pub/2019/advex-bugs-discussion/',
  'assets/img/covers/real/distill-advex-bugs-discussion.jpg',
  'Adversarial Examples Are Not Bugs, They Are Features — Discussion article cover',
  'cover',
  'published',
  false
),
(
  'distill-building-blocks-of-interpretability',
  'The Building Blocks of Interpretability',
  'Olah, Satyanarayan, and colleagues assemble feature visualization, attribution, and spatial maps into interactive building blocks for inspecting vision networks. The techniques are classic CNN interpretability and do not automatically transfer to modern LLMs.',
  'Chris Olah et al.',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Interpretability','Feature Visualization','Attribution','Vision'],
  '40 min read',
  '2018-03-06',
  'Distill',
  'https://distill.pub/2018/building-blocks/',
  'assets/img/covers/real/distill-building-blocks-of-interpretability.jpg',
  'The Building Blocks of Interpretability article cover',
  'cover',
  'published',
  false
),
(
  'distill-circuits-thread',
  'Circuits: A Thread on Neural Network Interpretability',
  'The Distill Circuits thread treats small vision models as circuits of features and weights, establishing a vocabulary later reused in mechanistic interpretability. It is a research program, not a complete map of frontier-model internals.',
  'Chris Olah et al.',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Trustworthy AI',
  array['Circuits','Mechanistic Interpretability','Vision','Features'],
  '45 min read',
  '2020-03-10',
  'Distill',
  'https://distill.pub/2020/circuits/',
  'assets/img/covers/real/distill-circuits-thread.jpg',
  'Circuits: A Thread on Neural Network Interpretability article cover',
  'cover',
  'published',
  false
),
(
  'deepmind-undesired-goals-correct-rewards',
  'How Undesired Goals Can Arise with Correct Rewards',
  'DeepMind separates specification gaming from goal misgeneralisation, showing how an agent can pursue the wrong objective even when the training reward looks right. Examples span RL and language models; they are illustrations, not a full incident census.',
  'Google DeepMind',
  'https://www.google.com/s2/favicons?domain=deepmind.google&sz=128',
  'Trustworthy AI',
  array['Specification Gaming','Goal Misgeneralization','RL','Alignment'],
  '11 min read',
  '2022-10-01',
  'Google DeepMind',
  'https://deepmind.google/blog/how-undesired-goals-can-arise-with-correct-rewards/',
  'assets/img/covers/real/deepmind-undesired-goals-correct-rewards.png',
  'How Undesired Goals Can Arise with Correct Rewards article cover',
  'cover',
  'published',
  false
),
(
  'openai-deliberative-alignment',
  'Deliberative Alignment: Reasoning Enables Safer Language Models',
  'OpenAI trains models to deliberate over an explicit safety specification via SFT and RL, then evaluates whether chain-of-thought deliberation reduces disallowed behavior. The safety gains are measured on OpenAI''s evals and may not match other policy sets.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Trustworthy AI',
  array['Deliberative Alignment','RLHF','Safety Spec','Reasoning'],
  '14 min read',
  '2024-12-20',
  'OpenAI',
  'https://openai.com/index/deliberative-alignment/',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Deliberative Alignment: Reasoning Enables Safer Language Models article cover',
  'cover',
  'published',
  false
),
(
  'anthropic-simple-probes-sleeper-agents',
  'Simple probes can catch sleeper agents',
  'Anthropic shows that linear probes on residual streams can detect sleeper-agent backdoors more cheaply than full behavioral red-teaming in their setup. Probe success is not a general backdoor detector; it depends on the implanted behavior and activations studied.',
  'Anthropic',
  'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
  'Trustworthy AI',
  array['Probes','Sleeper Agents','Interpretability','Backdoors'],
  '12 min read',
  '2024-12-10',
  'Anthropic',
  'https://www.anthropic.com/research/probes-catch-sleeper-agents',
  'assets/img/covers/real/anthropic-simple-probes-sleeper-agents.jpg',
  'Simple probes can catch sleeper agents article cover',
  'cover',
  'published',
  false
),
(
  'metr-changing-developer-productivity-experiment-design',
  'We are Changing our Developer Productivity Experiment Design',
  'METR publicly diagnoses confounding in its developer-productivity experiment and redesigns the randomization. It is an unusually transparent methods correction and is not yet a final causal-effect report.',
  'METR',
  'https://www.google.com/s2/favicons?domain=metr.org&sz=128',
  'Research Craft',
  array['Experiment Design','Causal Inference','Developer Productivity','Methods'],
  '15 min read',
  '2026-02-24',
  'METR',
  'https://metr.org/blog/2026-02-24-uplift-update/',
  'assets/img/covers/real/metr-changing-developer-productivity-experiment-design.png',
  'We are Changing our Developer Productivity Experiment Design article cover',
  'cover',
  'published',
  false
),
(
  'cmu-ml-blog-reproducibility',
  '5 – Reproducibility',
  'The CMU ML blog distinguishes kinds of reproducibility and turns them into a checklist covering data, code, seeds, variance, and repeats. Some tooling examples are dated, but the taxonomy of claims remains usable.',
  'Zihao Ding, Aniketh Reddy, Aparna Joshi',
  'https://www.google.com/s2/favicons?domain=blog.ml.cmu.edu&sz=128',
  'Research Craft',
  array['Reproducibility','Checklist','Experiment Design','ML Practice'],
  '18 min read',
  '2020-08-31',
  'ML@CMU',
  'https://blog.ml.cmu.edu/2020/08/31/5-reproducibility/',
  'assets/img/covers/real/cmu-ml-blog-reproducibility.png',
  '5 – Reproducibility article cover',
  'cover',
  'published',
  false
),
(
  'hamel-eval-smell-is-a-product-smell',
  '“It’s Hard to Eval” Is a Product Smell',
  'Hamel Husain treats inability to evaluate as a product-design failure: if you cannot write checks, you do not yet know the task. The argument is methodological, not a claim that every product needs a public leaderboard.',
  'Hamel Husain',
  'https://www.google.com/s2/favicons?domain=hamel.dev&sz=128',
  'Research Craft',
  array['Evaluations','Product','LLM Apps','Methodology'],
  '10 min read',
  '2026-06-29',
  'Hamel Husain',
  'https://hamel.dev/blog/posts/eval-smell/',
  'assets/img/covers/real/hamel-eval-smell-is-a-product-smell.png',
  '“It’s Hard to Eval” Is a Product Smell article cover',
  'cover',
  'published',
  false
),
(
  'google-deep-learning-tuning-playbook',
  'Deep Learning Tuning Playbook',
  'Google''s tuning playbook gives a staged protocol for baselines, hyperparameters, and when to stop searching, aimed at reducing cargo-cult training. It is a living engineering guide; defaults will lag the newest optimizers.',
  'Google',
  'https://www.google.com/s2/favicons?domain=developers.google.com&sz=128',
  'Research Craft',
  array['Hyperparameters','Tuning','Baselines','Training'],
  '40 min read',
  '2023-01-15',
  'Google Developers',
  'https://developers.google.com/machine-learning/guides/deep-learning-tuning-playbook',
  'assets/img/covers/real/google-deep-learning-tuning-playbook.png',
  'Deep Learning Tuning Playbook article cover',
  'cover',
  'published',
  false
),
(
  'google-good-data-analysis',
  'Good Data Analysis',
  'Google''s good-data-analysis guide lists failure modes in slicing, leakage, and metric choice before a model is trained. It is a practice checklist, not a statistics textbook.',
  'Google',
  'https://www.google.com/s2/favicons?domain=developers.google.com&sz=128',
  'Research Craft',
  array['Data Analysis','Metrics','Leakage','Methodology'],
  '20 min read',
  '2022-06-01',
  'Google Developers',
  'https://developers.google.com/machine-learning/guides/good-data-analysis',
  'assets/img/covers/real/google-good-data-analysis.png',
  'Good Data Analysis article cover',
  'cover',
  'published',
  false
),
(
  'google-data-traps',
  'Data Traps',
  'A companion guide to traps in training data: skewed sampling, label leakage, feedback loops, and silent schema change. The examples are production-oriented and still apply to LLM pipelines.',
  'Google',
  'https://www.google.com/s2/favicons?domain=developers.google.com&sz=128',
  'Research Craft',
  array['Data Quality','Leakage','Feedback Loops','ML Ops'],
  '18 min read',
  '2022-06-01',
  'Google Developers',
  'https://developers.google.com/machine-learning/guides/data-traps',
  'assets/img/covers/real/google-data-traps.png',
  'Data Traps article cover',
  'cover',
  'published',
  false
),
(
  'fsdl-experiment-management',
  'Experiment Management',
  'Full Stack Deep Learning''s experiment-management lab covers tracking, configs, and comparison discipline so runs remain interpretable weeks later. It is course material from 2022; tool names have changed more than the underlying hygiene.',
  'Full Stack Deep Learning',
  'https://www.google.com/s2/favicons?domain=fullstackdeeplearning.com&sz=128',
  'Research Craft',
  array['Experiment Tracking','Configs','ML Ops','Reproducibility'],
  '35 min read',
  '2022-03-01',
  'Full Stack Deep Learning',
  'https://fullstackdeeplearning.com/course/2022/lab-4-experiment-management/',
  'assets/img/covers/real/fsdl-experiment-management.png',
  'Experiment Management article cover',
  'cover',
  'published',
  false
),
(
  'fsdl-development-infrastructure-tooling',
  'Development Infrastructure and Tooling',
  'The FSDL lecture on development infrastructure treats environments, data versioning, and CI as part of the research loop rather than afterthoughts. Tooling specifics are 2022-era; the argument for investing in infra is not.',
  'Full Stack Deep Learning',
  'https://www.google.com/s2/favicons?domain=fullstackdeeplearning.com&sz=128',
  'Research Craft',
  array['Infrastructure','Tooling','ML Ops','Research Workflow'],
  '40 min read',
  '2022-03-01',
  'Full Stack Deep Learning',
  'https://fullstackdeeplearning.com/course/2022/lecture-2-development-infrastructure-and-tooling/',
  'assets/img/covers/real/fsdl-development-infrastructure-tooling.png',
  'Development Infrastructure and Tooling article cover',
  'cover',
  'published',
  false
),
(
  'ai2-astabench-update-spring-2026',
  'AstaBench Update: Spring 2026',
  'Ai2 updates AstaBench with new scientific-agent tasks and scoring notes, treating benchmark drift as something to document rather than hide. Scores remain benchmark-specific and should not be flattened into a single agent IQ.',
  'Ai2',
  'https://www.google.com/s2/favicons?domain=allenai.org&sz=128',
  'Research Craft',
  array['Benchmarks','Scientific Agents','Evaluation','AstaBench'],
  '9 min read',
  '2026-04-30',
  'Ai2',
  'https://allenai.org/blog/astabench-update-spring-2026',
  'assets/img/covers/real/ai2-astabench-update-spring-2026.png',
  'AstaBench Update: Spring 2026 article cover',
  'cover',
  'published',
  false
),
(
  'google-empirical-research-assistance',
  'Four Ways Google Researchers Have Been Using Empirical Research Assistance',
  'Google Research scientists describe using empirical-research assistance for literature triage, experiment bookkeeping, and writing support, with notes on where the tools still fail. It is a practice report from one lab, not a product benchmark.',
  'Google Research',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Research Craft',
  array['Research Workflow','Assistance','Literature','Experiments'],
  '8 min read',
  '2026-04-29',
  'Google Research',
  'https://research.google/blog/four-ways-google-research-scientists-have-been-using-empirical-research-assistance/',
  'assets/img/covers/real/google-empirical-research-assistance.jpg',
  'Four Ways Google Researchers Have Been Using Empirical Research Assistance article cover',
  'cover',
  'published',
  false
),
(
  'distill-bayesian-optimization',
  'Exploring Bayesian Optimization',
  'Distill''s interactive essay on Bayesian optimization builds intuition for Gaussian processes, acquisition functions, and when BO beats grid search. It is a 2020 teaching piece; modern HPO stacks add multivariate and multi-fidelity wrinkles.',
  'Distill',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Research Craft',
  array['Bayesian Optimization','HPO','Gaussian Processes','Interactive'],
  '35 min read',
  '2020-04-06',
  'Distill',
  'https://distill.pub/2020/bayesian-optimization/',
  'assets/img/covers/real/distill-bayesian-optimization.jpg',
  'Exploring Bayesian Optimization article cover',
  'cover',
  'published',
  false
),
(
  'distill-how-to-use-tsne-effectively',
  'How to Use t-SNE Effectively',
  'Wattenberg, Viégas, and Johnson show how t-SNE cluster shapes are artifacts of perplexity and exaggeration, not proofs of structure. The cautions still apply whenever embeddings are plotted as evidence.',
  'Martin Wattenberg, Fernanda Viégas, Ian Johnson',
  'https://www.google.com/s2/favicons?domain=distill.pub&sz=128',
  'Research Craft',
  array['t-SNE','Visualization','Embeddings','Pitfalls'],
  '25 min read',
  '2016-10-13',
  'Distill',
  'https://distill.pub/2016/misread-tsne/',
  'assets/img/covers/real/distill-how-to-use-tsne-effectively.jpg',
  'How to Use t-SNE Effectively article cover',
  'cover',
  'published',
  false
),
(
  'google-rules-of-machine-learning',
  'Rules of Machine Learning: Best Practices for ML Engineering',
  'Google''s Rules of ML is a staged playbook from a no-ML baseline through feature hygiene, training-serving skew, and mature pipelines. It predates foundation-model serving but the operational rules remain a high-signal checklist.',
  'Google',
  'https://www.google.com/s2/favicons?domain=developers.google.com&sz=128',
  'Research Craft',
  array['ML Engineering','Baselines','Skew','Production'],
  '45 min read',
  '2017-10-01',
  'Google Developers',
  'https://developers.google.com/machine-learning/guides/rules-of-ml/',
  'assets/img/covers/real/google-rules-of-machine-learning.png',
  'Rules of Machine Learning: Best Practices for ML Engineering article cover',
  'cover',
  'published',
  false
),
(
  'eugene-yan-testing-ml',
  'How to Test Machine Learning Code and Systems',
  'Eugene Yan separates software-logic tests, learning-behavior tests, and model evaluation, with pre-train and post-train checks a team can actually run. It is a testing taxonomy, not a complete CI template for every stack.',
  'Eugene Yan',
  'https://www.google.com/s2/favicons?domain=eugeneyan.com&sz=128',
  'Research Craft',
  array['Testing','ML Systems','Evaluation','Quality'],
  '22 min read',
  '2022-01-17',
  'Eugene Yan',
  'https://eugeneyan.com/writing/testing-ml/',
  'assets/img/covers/real/eugene-yan-testing-ml.jpg',
  'How to Test Machine Learning Code and Systems article cover',
  'cover',
  'published',
  false
),
(
  'eugene-yan-maintaining-ml-production',
  'A Practical Guide to Maintaining Machine Learning in Production',
  'Eugene Yan catalogs long-horizon maintenance: data contamination, retraining cadence, feedback loops, engineering complexity, and team structure. The guide is industry-practice, not a single-vendor runbook.',
  'Eugene Yan',
  'https://www.google.com/s2/favicons?domain=eugeneyan.com&sz=128',
  'Research Craft',
  array['ML Ops','Maintenance','Retraining','Feedback Loops'],
  '24 min read',
  '2021-09-15',
  'Eugene Yan',
  'https://eugeneyan.com/writing/practical-guide-to-maintaining-machine-learning/',
  'assets/img/covers/real/eugene-yan-maintaining-ml-production.jpg',
  'A Practical Guide to Maintaining Machine Learning in Production article cover',
  'cover',
  'published',
  false
),
(
  'openai-evals-drive-next-chapter-of-ai',
  'How evals drive the next chapter in AI',
  'OpenAI argues that evaluations, not just model size, now gate capability claims and product decisions. The piece is programmatic; specific eval items live in other technical reports.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'Research Craft',
  array['Evaluations','Benchmarks','Capability','Methodology'],
  '8 min read',
  '2025-05-01',
  'OpenAI',
  'https://openai.com/index/evals-drive-next-chapter-of-ai/',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'How evals drive the next chapter in AI article cover',
  'cover',
  'published',
  false
),
(
  'hazyresearch-what-data-centric-ai-is-not',
  'What Data-Centric AI Is Not',
  'Stanford Hazy Research clarifies data-centric AI by ruling out slogans: it is not merely ''more data'', nor a replacement for learning algorithms. The 2021 framing still helps keep dataset work from collapsing into marketing.',
  'Stanford Hazy Research',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'Research Craft',
  array['Data-Centric AI','Datasets','Methodology','Definitions'],
  '8 min read',
  '2021-06-01',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/what-data-centric-ai-is-not',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'What Data-Centric AI Is Not article cover',
  'cover',
  'published',
  false
),
(
  'colin-raffel-when-will-language-models-be-good-enough',
  'When Will Language Models Be Good Enough?',
  'Colin Raffel asks what ''good enough'' means for language models as a scientific and product question, distinguishing saturation on current evals from remaining real-world failure. It is an expert opinion essay, not a scaling-law forecast.',
  'Colin Raffel',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Frontier',
  array['Language Models','Evaluations','Saturation','Research Taste'],
  '12 min read',
  '2026-07-16',
  'Hugging Face Blog',
  'https://huggingface.co/blog/craffel/when-will-language-models-be-good-enough',
  'assets/img/covers/real/colin-raffel-when-will-language-models-be-good-enough.png',
  'When Will Language Models Be Good Enough? article cover',
  'cover',
  'published',
  false
),
(
  'mishig-two-years-local-ai-moores-law',
  'Two Years of Local AI on a Laptop: When Open Models Outpaced Moore''s Law',
  'Mishig Davaadorj tracks local open models on a laptop over two years and argues capability gains outran hardware scaling on that device class. The trend is community-replicable for similar laptops and should not be extrapolated to datacenter training.',
  'Mishig Davaadorj',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'Frontier',
  array['Local AI','Open Models','Hardware','Trends'],
  '11 min read',
  '2026-04-01',
  'Hugging Face Blog',
  'https://huggingface.co/blog/mishig/local-moores-law',
  'assets/img/covers/real/mishig-two-years-local-ai-moores-law.png',
  'Two Years of Local AI on a Laptop: When Open Models Outpaced Moore''s Law article cover',
  'cover',
  'published',
  false
),
(
  'eu-ai-office-frontier-expert-findings',
  'Frontier AI Expert Findings: EU Competitiveness, Sovereignty and Security',
  'The European Commission AI Office publishes expert findings on frontier AI competitiveness, sovereignty, and security. Treat it as a policy-and-evidence brief, not a model card or a training recipe.',
  'European Commission AI Office',
  'https://www.google.com/s2/favicons?domain=digital-strategy.ec.europa.eu&sz=128',
  'Frontier',
  array['Policy','Frontier AI','EU','Security'],
  '30 min read',
  '2026-07-15',
  'European Commission',
  'https://digital-strategy.ec.europa.eu/en/library/ai-office-publishes-frontier-ai-expert-findings-eu-competitiveness-sovereignty-and-security',
  'https://www.google.com/s2/favicons?domain=digital-strategy.ec.europa.eu&sz=128',
  'Frontier AI Expert Findings: EU Competitiveness, Sovereignty and Security article cover',
  'cover',
  'published',
  false
),
(
  'un-scientific-panel-ai-preliminary-report',
  'Preliminary Report of the UN Independent International Scientific Panel on AI',
  'The UN Independent International Scientific Panel on AI releases a preliminary scientific assessment of capabilities, risks, and evidence gaps. It is a panel report, not a lab blog, and should be read as a synthesis with explicit uncertainty.',
  'United Nations',
  'https://www.google.com/s2/favicons?domain=un.org&sz=128',
  'Frontier',
  array['UN','Scientific Panel','Risk','Governance'],
  '40 min read',
  '2026-06-01',
  'United Nations',
  'https://www.un.org/independent-international-scientific-panel-ai/en/preliminary-report',
  'https://www.google.com/s2/favicons?domain=un.org&sz=128',
  'Preliminary Report of the UN Independent International Scientific Panel on AI article cover',
  'cover',
  'published',
  false
),
(
  'international-ai-safety-report-2026',
  'International AI Safety Report 2026',
  'The International AI Safety Report 2026 synthesizes evidence on frontier capabilities and risks across contributing institutions. Cite individual chapters for technical claims; the landing page is the canonical report entry, not a news index.',
  'International AI Safety Report',
  'https://www.google.com/s2/favicons?domain=internationalaisafetyreport.org&sz=128',
  'Frontier',
  array['AI Safety','Frontier','Risk','Evidence Synthesis'],
  '60 min read',
  '2026-01-15',
  'International AI Safety Report',
  'https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026',
  'assets/img/covers/real/international-ai-safety-report-2026.jpg',
  'International AI Safety Report 2026 article cover',
  'cover',
  'published',
  false
),
(
  'stanford-hai-ai-index-2026',
  'AI Index Report 2026',
  'Stanford HAI''s 2026 AI Index compiles quantitative trends on capability, investment, policy, and public opinion. Use the underlying charts rather than any single headline; methodology notes matter for cross-year comparisons.',
  'Stanford HAI',
  'https://www.google.com/s2/favicons?domain=hai.stanford.edu&sz=128',
  'Frontier',
  array['AI Index','Trends','Measurement','Policy'],
  '50 min read',
  '2026-04-01',
  'Stanford HAI',
  'https://hai.stanford.edu/ai-index',
  'assets/img/covers/real/stanford-hai-ai-index-2026.jpg',
  'AI Index Report 2026 article cover',
  'cover',
  'published',
  false
),
(
  'uk-aisi-frontier-ai-trends-report-2026',
  'Frontier AI Trends Report',
  'UK AISI''s Frontier AI Trends Report tracks capability, evaluation, and security-relevant trends with an evaluator''s emphasis on what can be measured. It is a trends report, not a model release.',
  'UK AI Security Institute',
  'https://www.google.com/s2/favicons?domain=aisi.gov.uk&sz=128',
  'Frontier',
  array['Frontier AI','Trends','Evaluations','Security'],
  '35 min read',
  '2026-05-01',
  'UK AI Security Institute',
  'https://www.aisi.gov.uk/frontier-ai-trends-report',
  'assets/img/covers/real/uk-aisi-frontier-ai-trends-report-2026.jpg',
  'Frontier AI Trends Report article cover',
  'cover',
  'published',
  false
),
(
  'state-of-ai-2026-model-provider-survey',
  'State of AI 2026: Model Provider Survey',
  'The 2026 State of AI model-provider survey aggregates how builders report training, serving, and productization choices. Self-reported survey data should be triangulated against public evals and independent measurements.',
  'State of AI',
  'https://www.google.com/s2/favicons?domain=2026.stateofai.dev&sz=128',
  'Frontier',
  array['Survey','Model Providers','Industry','Trends'],
  '20 min read',
  '2026-06-01',
  'State of AI',
  'https://2026.stateofai.dev/en-US/models/',
  'assets/img/covers/real/state-of-ai-2026-model-provider-survey.png',
  'State of AI 2026: Model Provider Survey article cover',
  'cover',
  'published',
  false
),
(
  'epoch-have-ai-capabilities-accelerated',
  'Have AI Capabilities Accelerated?',
  'Epoch AI asks whether capability progress accelerated relative to prior scaling trends, separating benchmark families and compute growth. The answer depends on the metric; the value is the decomposition, not a yes/no slogan.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Capabilities','Scaling','Benchmarks','Measurement'],
  '22 min read',
  '2025-11-01',
  'Epoch AI',
  'https://epoch.ai/publications/have-ai-capabilities-accelerated',
  'assets/img/covers/real/epoch-have-ai-capabilities-accelerated.png',
  'Have AI Capabilities Accelerated? article cover',
  'cover',
  'published',
  false
),
(
  'epoch-where-autonomy-works-2026',
  'Where Autonomy Works: Evaluating Robot Capabilities in 2026',
  'Epoch AI evaluates where robot autonomy actually works in 2026, distinguishing demo-friendly settings from economically relevant ones. Task coverage is necessarily incomplete; treat gaps as missing measurements, not proofs of impossibility.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Robotics','Autonomy','Evaluation','Capabilities'],
  '20 min read',
  '2026-03-01',
  'Epoch AI',
  'https://epoch.ai/publications/where-autonomy-works-evaluating-robot-capabilities-in-2026',
  'assets/img/covers/real/epoch-where-autonomy-works-2026.png',
  'Where Autonomy Works: Evaluating Robot Capabilities in 2026 article cover',
  'cover',
  'published',
  false
),
(
  'epoch-what-will-ai-look-like-in-2030',
  'What Will AI Look Like in 2030?',
  'Epoch AI sketches 2030 scenarios from compute, data, and capability trends, with explicit uncertainty bands. Scenario essays are not commitments; they are structured guesses with stated drivers.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Forecasting','2030','Scenarios','Compute'],
  '24 min read',
  '2025-09-01',
  'Epoch AI',
  'https://epoch.ai/publications/what-will-ai-look-like-in-2030',
  'assets/img/covers/real/epoch-what-will-ai-look-like-in-2030.png',
  'What Will AI Look Like in 2030? article cover',
  'cover',
  'published',
  false
),
(
  'epoch-power-demands-frontier-ai-training',
  'Power Demands of Frontier AI Training',
  'Epoch AI estimates electrical power required for frontier training runs and how that demand grows with compute. The figures inherit utilization and facility-efficiency assumptions that operators can beat or miss.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Power','Training','Infrastructure','Compute'],
  '18 min read',
  '2025-06-01',
  'Epoch AI',
  'https://epoch.ai/publications/power-demands-of-frontier-ai-training',
  'assets/img/covers/real/epoch-power-demands-frontier-ai-training.png',
  'Power Demands of Frontier AI Training article cover',
  'cover',
  'published',
  false
),
(
  'epoch-what-you-need-to-know-ai-data-centers',
  'What You Need to Know About AI Data Centers',
  'A primer on AI datacenters covering power, cooling, networking, and why training clusters differ from inference farms. It is explanatory; site-level numbers will vary by operator and region.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Data Centers','Infrastructure','Power','Clusters'],
  '16 min read',
  '2025-07-01',
  'Epoch AI',
  'https://epoch.ai/publications/what-you-need-to-know-about-ai-data-centers',
  'assets/img/covers/real/epoch-what-you-need-to-know-ai-data-centers.png',
  'What You Need to Know About AI Data Centers article cover',
  'cover',
  'published',
  false
),
(
  'epoch-training-compute-grows-4-5x',
  'Training Compute of Frontier AI Models Grows by 4–5× per Year',
  'Epoch AI estimates that frontier training compute has grown roughly 4–5× per year, with notes on measurement, secret runs, and sparse public disclosures. Treat the multiplier as an estimated trend, not a physical law.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Training Compute','Scaling','Measurement','Frontier'],
  '15 min read',
  '2024-05-01',
  'Epoch AI',
  'https://epoch.ai/publications/training-compute-of-frontier-ai-models-grows-by-4-5x-per-year',
  'assets/img/covers/real/epoch-training-compute-grows-4-5x.png',
  'Training Compute of Frontier AI Models Grows by 4–5× per Year article cover',
  'cover',
  'published',
  false
),
(
  'epoch-can-ai-scaling-continue-through-2030',
  'Can AI Scaling Continue Through 2030?',
  'Epoch AI quantifies four constraints on continued scaling through 2030: power, chip manufacturing, data, and training latency. The report is high information density; each constraint has its own uncertainty, so the binding one can change.',
  'Epoch AI',
  'https://www.google.com/s2/favicons?domain=epoch.ai&sz=128',
  'Frontier',
  array['Scaling','Power','Chips','Data'],
  '28 min read',
  '2024-06-20',
  'Epoch AI',
  'https://epoch.ai/publications/can-ai-scaling-continue-through-2030',
  'assets/img/covers/real/epoch-can-ai-scaling-continue-through-2030.png',
  'Can AI Scaling Continue Through 2030? article cover',
  'cover',
  'published',
  false
),
(
  'mistral-robostral-navigate',
  'Introducing Robostral Navigate',
  'Mistral introduces Robostral Navigate, an 8B single-RGB-camera navigation model, with notes on pointing-style actions, 2.4M trajectories, prefix caching, and online RL. It is a technically specified release, not a full robotics foundation-model paper.',
  'Mistral AI',
  'https://www.google.com/s2/favicons?domain=mistral.ai&sz=128',
  'Frontier',
  array['Robotics','Navigation','VLA','Mistral'],
  '8 min read',
  '2026-05-01',
  'Mistral AI',
  'https://mistral.ai/news/robostral-navigate/',
  'assets/img/covers/real/mistral-robostral-navigate.jpg',
  'Introducing Robostral Navigate article cover',
  'cover',
  'published',
  false
),
(
  'mistral-ocr-4',
  'Mistral OCR 4: SOTA OCR for Document Intelligence',
  'Mistral OCR 4 describes a document-intelligence OCR stack with claimed state-of-the-art document parsing. Benchmark names and languages matter; treat SOTA as measured on the reported suites, not as a universal OCR ranking.',
  'Mistral AI',
  'https://www.google.com/s2/favicons?domain=mistral.ai&sz=128',
  'Frontier',
  array['OCR','Document Intelligence','Mistral','Parsing'],
  '7 min read',
  '2026-03-01',
  'Mistral AI',
  'https://mistral.ai/news/ocr-4/',
  'assets/img/covers/real/mistral-ocr-4.png',
  'Mistral OCR 4: SOTA OCR for Document Intelligence article cover',
  'cover',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status;

