-- Expand quality corpus: Visual Generation, World Model, AI Agents.
-- Run in the Supabase SQL Editor for the public BlogrXiv project.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'sander-dieleman-guidance-cheat-code-diffusion',
  'Guidance: A Cheat Code for Diffusion Models',
  'Sander Dieleman explains classifier guidance and classifier-free guidance, showing how mixing conditional and unconditional score estimates with a scale factor sharpens the conditional distribution and why that near-free change powers the fidelity of DALL-E 2 and Imagen. He builds geometric intuition for the guidance term as a gradient nudging samples toward higher-likelihood regions of the conditional, and is explicit about the price: raising the guidance scale trades sample diversity for fidelity, effectively truncating the distribution the model was trained on.',
  'Sander Dieleman',
  'https://www.google.com/s2/favicons?domain=sander.ai&sz=128',
  'Visual Generation',
  array['Diffusion Models','Classifier-Free Guidance','Conditional Generation','Score Function'],
  '16 min read',
  '2022-05-26',
  'Sander Dieleman',
  'https://sander.ai/2022/05/26/guidance.html',
  'assets/img/covers/real/sander-dieleman-guidance-cheat-code-diffusion.jpg',
  'Guidance for diffusion models article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-improving-diffusion-models-alternative-gans-part-1',
  'Improving Diffusion Models as an Alternative to GANs, Part 1',
  'Arash Vahdat and Karsten Kreis frame generative modeling as a trilemma among sample quality, mode coverage, and sampling speed, then walk through denoising diffusion fundamentals to argue diffusion models beat GANs on training stability and diversity while losing badly on sampling cost. This is the conceptual half of a two-part series: the concrete NVIDIA techniques for overcoming slow sampling, including latent-space diffusion and diffusion-GAN hybrids, are deferred to Part 2.',
  'Arash Vahdat, Karsten Kreis',
  'https://www.google.com/s2/favicons?domain=developer.nvidia.com&sz=128',
  'Visual Generation',
  array['Diffusion Models','GANs','Generative Learning Trilemma','Sampling Speed'],
  '12 min read',
  '2022-04-26',
  'NVIDIA Technical Blog',
  'https://developer.nvidia.com/blog/improving-diffusion-models-as-an-alternative-to-gans-part-1/',
  'assets/img/covers/real/nvidia-improving-diffusion-models-alternative-gans-part-1.png',
  'Generation with diffusion models illustration from NVIDIA',
  'cover',
  'published',
  false
),
(
  'google-high-fidelity-image-generation-diffusion',
  'High Fidelity Image Generation Using Diffusion Models',
  'Jonathan Ho and Chitwan Saharia introduce SR3, which super-resolves images by iterative refinement from noise, and CDM, cascaded class-conditional diffusion pipelines whose ImageNet samples surpass BigGAN-deep and VQ-VAE-2 on both FID and Classification Accuracy Score. SR3 approaches a 50% fool rate in human evaluations of face super-resolution; the results lean on careful cascading and conditioning augmentation across resolutions, and the post predates the guidance techniques that later drove text-to-image quality.',
  'Jonathan Ho, Chitwan Saharia',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'Visual Generation',
  array['Diffusion Models','Super-Resolution','Cascaded Generation','ImageNet'],
  '9 min read',
  '2021-07-16',
  'Google Research Blog',
  'https://research.google/blog/high-fidelity-image-generation-using-diffusion-models/',
  'assets/img/covers/real/google-high-fidelity-image-generation-diffusion.jpg',
  'SR3 and CDM diffusion model results cover',
  'cover',
  'published',
  false
),
(
  'bair-model-based-rl-theory-and-practice',
  'Model-Based Reinforcement Learning: Theory and Practice',
  'Michael Janner surveys when learned dynamics models actually help policy optimization, deriving a monotonic-improvement bound that is too pessimistic to justify model usage and then repairing it with empirical estimates of model generalization. The resulting MBPO recipe, short model rollouts branched from real states with probabilistic ensembles and soft actor-critic, matches the asymptotic performance of model-free methods at a fraction of the samples, though the evidence comes from MuJoCo continuous-control benchmarks rather than high-dimensional or real-world domains.',
  'Michael Janner',
  'https://www.google.com/s2/favicons?domain=bair.berkeley.edu&sz=128',
  'World Model',
  array['Model-Based RL','World Models','Policy Optimization','Sample Efficiency'],
  '12 min read',
  '2019-12-12',
  'BAIR Blog',
  'https://bair.berkeley.edu/blog/2019/12/12/mbpo/',
  'assets/img/covers/real/bair-model-based-rl-theory-and-practice.png',
  'Model-based reinforcement learning header figure',
  'cover',
  'published',
  false
),
(
  'runway-introducing-general-world-models',
  'Introducing General World Models',
  'Anastasis Germanidis argues that video generators like Gen-2 are already early, limited world models: to synthesize realistic motion they must internalize some physics, yet they still fail on complex camera and object dynamics. The post defines general world models as systems that build internal environment representations to simulate futures and names the open problems, consistent environment maps, navigation and interaction, and realistic models of human behavior; it is an agenda-setting research statement rather than a technical report.',
  'Anastasis Germanidis',
  'https://www.google.com/s2/favicons?domain=runwayml.com&sz=128',
  'World Model',
  array['World Models','Video Generation','Research Agenda','Simulation'],
  '6 min read',
  '2023-12-11',
  'Runway Research',
  'https://runwayml.com/research/introducing-general-world-models',
  'assets/img/covers/real/runway-introducing-general-world-models.webp',
  'Runway general world models research cover',
  'cover',
  'published',
  false
),
(
  'onex-1x-world-model',
  '1X World Model',
  '1X trains an action-controllable video world model on thousands of hours of EVE humanoid data, so identical initial frames roll out differently under different commanded trajectories, providing a learned simulator for evaluating manipulation policies on rigid boxes, doors, and deformables like folded shirts. The company releases over 100 hours of vector-quantized video, pretrained baselines, and a staged World Model Challenge with cash prizes, while candidly showing failure cases where generated futures violate object permanence and physics.',
  'Jack Monas, Eric Jang',
  'https://www.google.com/s2/favicons?domain=1x.tech&sz=128',
  'World Model',
  array['World Models','Humanoid Robots','Policy Evaluation','Video Generation'],
  '8 min read',
  '2024-09-17',
  '1X Technologies',
  'https://www.1x.tech/discover/1x-world-model',
  'assets/img/covers/real/onex-1x-world-model.png',
  '1X world model generated humanoid robot scenes',
  'cover',
  'published',
  false
),
(
  'openai-computer-using-agent',
  'Computer-Using Agent',
  'OpenAI introduces CUA, the model behind Operator, which combines GPT-4o vision with reinforcement learning to operate raw graphical interfaces through screenshots and a virtual mouse and keyboard, requiring no OS- or website-specific APIs. At release it set state-of-the-art agent results with 38.1% on OSWorld, 58.1% on WebArena, and 87% on WebVoyager, but remains far below the 72.4% human score on OSWorld, and OpenAI shipped it as a gated research preview with confirmation prompts for consequential actions.',
  'OpenAI',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
  'AI Agents',
  array['Computer Use','GUI Agents','Reinforcement Learning','Operator'],
  '10 min read',
  '2025-01-23',
  'OpenAI',
  'https://openai.com/index/computer-using-agent/',
  'assets/img/covers/real/openai-computer-using-agent.png',
  'OpenAI Computer-Using Agent announcement cover',
  'cover',
  'published',
  false
),
(
  'google-chain-of-agents-long-context',
  'Chain of Agents: Large Language Models Collaborating on Long-Context Tasks',
  'A training-free, task-agnostic framework where worker LLMs each read one chunk of a long input and pass a communication unit down a chain before a manager agent synthesizes the final answer, replacing read-then-process retrieval with interleaved read-process. Presented at NeurIPS 2024, Chain-of-Agents improves up to 10% over RAG, multi-agent, and full-context baselines on long-document question answering, summarization, and code completion, at the cost of strictly sequential worker calls that add latency.',
  'Yusen Zhang, Ruoxi Sun',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'AI Agents',
  array['Multi-Agent Systems','Long Context','LLM Collaboration','RAG'],
  '9 min read',
  '2025-01-23',
  'Google Research Blog',
  'https://research.google/blog/chain-of-agents-large-language-models-collaborating-on-long-context-tasks/',
  'assets/img/covers/real/google-chain-of-agents-long-context.jpg',
  'Chain of Agents framework illustration',
  'cover',
  'published',
  false
),
(
  'meta-cicero-diplomacy-agent',
  'CICERO: An AI Agent That Negotiates, Persuades, and Cooperates with People',
  'CICERO reached human-level performance in full-press Diplomacy by coupling a 2.7B-parameter controllable dialogue model fine-tuned on over 40,000 webDiplomacy games with the piKL planning algorithm, which balances dialogue-consistent intentions against rational play. Across 40 anonymous online games it more than doubled the average human score and ranked in the top 10% of repeat players, though Meta documents cases where the agent generates contradictory messages that undermine its own negotiated plans.',
  'Meta AI',
  'https://www.google.com/s2/favicons?domain=ai.meta.com&sz=128',
  'AI Agents',
  array['Multi-Agent Negotiation','Strategic Reasoning','Dialogue Models','Game AI'],
  '11 min read',
  '2022-11-22',
  'Meta AI',
  'https://ai.meta.com/blog/cicero-ai-negotiates-persuades-and-cooperates-with-people/',
  'assets/img/covers/real/meta-cicero-diplomacy-agent.png',
  'CICERO Diplomacy agent gameplay visualization',
  'cover',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status;
