-- Add the Visual Generation, World Model, and AI Agents quality essays to Supabase.
-- Run this in the Supabase SQL Editor for the project backing the public site.

insert into public.blogs (
  id,
  title,
  excerpt,
  author,
  author_avatar,
  category,
  tags,
  read_time,
  publish_date,
  source_name,
  url,
  cover_image,
  cover_alt,
  cover_fit,
  status,
  featured
) values
(
  'sander-dieleman-noise-schedules-considered-harmful',
  'Noise Schedules Considered Harmful',
  'Sander Dieleman argues the noise schedule is a superfluous abstraction in diffusion models, reframing design around noise-level distributions expressed as logSNR and showing how loss weighting, output parameterization, and step spacing shift the training and sampling balance. He surveys linear, cosine, shifted, and variance-exploding schedules and recommends adaptive weighting mechanisms over schedule tuning; the analysis is conceptual rather than a new benchmarked method.',
  'Sander Dieleman',
  'https://www.google.com/s2/favicons?domain=sander.ai&sz=128',
  'Visual Generation',
  array['Diffusion Models','Noise Schedules','Loss Weighting','Generative Modeling'],
  '16 min read',
  '2024-06-14',
  'Sander Dieleman',
  'https://sander.ai/2024/06/14/noise-schedules.html',
  'assets/img/covers/real/sander-dieleman-noise-schedules-considered-harmful.jpg',
  'Noise schedules considered harmful article cover',
  'cover',
  'published',
  false
),
(
  'sander-dieleman-paradox-of-diffusion-distillation',
  'The Paradox of Diffusion Distillation',
  'A deep dive into why diffusion sampling needs many small steps and how distillation methods, including progressive distillation, guidance distillation, rectified flow, consistency distillation, TRACT, BOOT, score distillation sampling, and adversarial variants, compress the sampler into a few forward passes. Dieleman examines the paradox that iterative refinement is the source of diffusion quality yet everyone wants to remove it, and notes that distilled students trade off mode coverage and quality relative to their teachers.',
  'Sander Dieleman',
  'https://www.google.com/s2/favicons?domain=sander.ai&sz=128',
  'Visual Generation',
  array['Diffusion Models','Distillation','Consistency Models','Sampling Efficiency'],
  '20 min read',
  '2024-02-28',
  'Sander Dieleman',
  'https://sander.ai/2024/02/28/paradox.html',
  'assets/img/covers/real/sander-dieleman-paradox-of-diffusion-distillation.jpg',
  'Paradox of diffusion distillation article cover',
  'cover',
  'published',
  false
),
(
  'nvidia-autoregressive-video-generation',
  'Autoregressive Video Generation',
  'NVIDIA''s Efficient AI team frames autoregressive video generation as a systems contract: factorizing time into frames or latent blocks preserves KV-cache reuse, streaming output, and persistent decode loops from LLM serving while keeping diffusion-level visual quality. The post reviews early AR training attempts, techniques for extending duration, and distillation for faster generation, noting that full-clip bidirectional diffusion cannot emit frames early or handle prompt changes mid-generation.',
  'Shuai Yang, Yukang Chen, et al.',
  'https://www.google.com/s2/favicons?domain=research.nvidia.com&sz=128',
  'Visual Generation',
  array['Autoregressive Models','Video Generation','KV Cache','Streaming Inference'],
  '18 min read',
  '2026-07-13',
  'NVIDIA Research',
  'https://research.nvidia.com/labs/eai/blogs/autoregressive-video-gen/',
  'assets/img/covers/real/nvidia-autoregressive-video-generation.jpg',
  'Autoregressive video generation article cover',
  'cover',
  'published',
  false
),
(
  'meta-muse-image-muse-video',
  'Introducing Muse Image and Muse Video',
  'Meta Superintelligence Labs launches Muse Image and previews Muse Video: the image model operates as an agent that invokes search and coding tools learned during reinforcement learning to render accurate plots and QR codes, self-refines its generations, and improves with scaled test-time compute. Muse Video shares the pretraining base and adds native audio; the post is a capability-focused release with staged product availability rather than a full technical report.',
  'Meta Superintelligence Labs',
  'https://www.google.com/s2/favicons?domain=ai.meta.com&sz=128',
  'Visual Generation',
  array['Image Generation','Video Generation','Agentic Tool Use','Test-Time Compute'],
  '15 min read',
  '2026-07-07',
  'Meta AI',
  'https://ai.meta.com/blog/introducing-muse-image-muse-video-msl/',
  'assets/img/covers/real/meta-muse-image-muse-video.webp',
  'Muse Image and Muse Video announcement cover',
  'cover',
  'published',
  false
),
(
  'nvidia-video-gen-is-an-infra-problem',
  'Why Video Gen Is an Infra Problem',
  'Argues that video generation has shifted from capability demos to an infrastructure problem: long videos stress memory, real-time generation depends on the full serving system rather than DiT frame rate, and training and serving must be co-designed. Uses LongLive 2.0 as a case study for producing long, consistent, controllable video under real memory, latency, and deployment budgets.',
  'Yukang Chen, Luozhou Wang, et al.',
  'https://www.google.com/s2/favicons?domain=research.nvidia.com&sz=128',
  'Visual Generation',
  array['Video Generation','Inference Systems','Memory Efficiency','Deployment'],
  '10 min read',
  '2026-05-26',
  'NVIDIA Research',
  'https://research.nvidia.com/labs/eai/blogs/video-gen-is-an-infra-problem/',
  'assets/img/covers/real/nvidia-video-gen-is-an-infra-problem.jpg',
  'Video generation infrastructure article cover',
  'cover',
  'published',
  false
),
(
  'diffusion-meets-flow-matching',
  'Diffusion Meets Flow Matching: Two Sides of the Same Coin',
  'An interactive tutorial showing that diffusion models and Gaussian flow matching are equivalent: DDIM with the optimal-transport schedule reproduces flow matching''s Euler updates, and the real degrees of freedom are network output parameterization, sampling schedule, and stochasticity level. A Colab notebook reproduces every plot, and the post corrects misconceptions such as flow matching paths being inherently straight or deterministic; the equivalence covers the Gaussian source case only.',
  'Ruiqi Gao, Emiel Hoogeboom, et al.',
  'https://www.google.com/s2/favicons?domain=diffusionflow.github.io&sz=128',
  'Visual Generation',
  array['Diffusion Models','Flow Matching','Rectified Flow','Tutorial'],
  '15 min read',
  '2024-12-02',
  'diffusionflow.github.io',
  'https://diffusionflow.github.io/',
  'assets/img/covers/real/diffusion-meets-flow-matching.jpg',
  'Diffusion meets flow matching tutorial cover',
  'cover',
  'published',
  false
),
(
  'meta-fair-partnr-human-robot-collaboration',
  'PARTNR and New Models for Human-Robot Collaboration',
  'Meta FAIR open-sources PARTNR, a benchmark of 100,000 household collaboration tasks built on Habitat 3.0 with a human-demonstration dataset, plus a large planning model that runs 8.6x faster than prior baselines, makes human partners 24% more efficient, and was deployed on Boston Dynamics'' Spot. The post bundles additional releases, including the Audiobox Aesthetics audio-quality model trained on 562 hours of annotated audio, so the robotics contribution is concentrated in the PARTNR sections.',
  'Meta FAIR',
  'https://www.google.com/s2/favicons?domain=ai.meta.com&sz=128',
  'World Model',
  array['Human-Robot Collaboration','Embodied AI','Benchmark','Simulation'],
  '12 min read',
  '2025-02-07',
  'Meta AI',
  'https://ai.meta.com/blog/machine-intelligence-research-new-models/',
  'assets/img/covers/real/meta-fair-partnr-human-robot-collaboration.jpg',
  'Meta FAIR PARTNR human-robot collaboration cover',
  'cover',
  'published',
  false
),
(
  'ai2-molmospaces-embodied-ai-ecosystem',
  'MolmoSpaces: An Open Ecosystem for Embodied AI',
  'Ai2 releases MolmoSpaces, a fully open embodied-AI platform unifying 230,000+ indoor scenes, 130,000+ curated object assets in MJCF and USD, and 42 million 6-DoF grasp annotations with validated physics parameters, portable across MuJoCo, ManiSkill, and Isaac Lab/Sim. MolmoSpaces-Bench evaluates generalist policies under controlled variation of object properties, layouts, lighting, dynamics, and instruction phrasing rather than reporting a single aggregate success rate.',
  'Ai2',
  'https://www.google.com/s2/favicons?domain=allenai.org&sz=128',
  'World Model',
  array['Embodied AI','Robotic Manipulation','Simulation','Open Source'],
  '11 min read',
  '2026-02-11',
  'Ai2 Blog',
  'https://allenai.org/blog/molmospaces',
  'assets/img/covers/real/ai2-molmospaces-embodied-ai-ecosystem.jpg',
  'MolmoSpaces embodied AI ecosystem cover',
  'cover',
  'published',
  false
),
(
  'bair-rl-traffic-smoothing-100-av-deployment',
  'Scaling Up Reinforcement Learning for Traffic Smoothing: A 100-AV Highway Deployment',
  'Berkeley researchers deployed 100 RL-controlled cars into I-24 rush-hour traffic to damp stop-and-go waves, training decentralized controllers in data-driven simulations that replay real highway trajectories and using only radar-visible observations so policies run through standard adaptive cruise control. Simulation showed up to 20% fuel savings with under 5% AV penetration; camera-derived field data indicate roughly 15-20% energy savings near the AVs, with the caveat that extracting precise measurements from large-scale video is noisy.',
  'UC Berkeley BAIR',
  'https://www.google.com/s2/favicons?domain=bair.berkeley.edu&sz=128',
  'World Model',
  array['Reinforcement Learning','Autonomous Vehicles','Field Deployment','Sim-to-Real'],
  '12 min read',
  '2025-03-25',
  'BAIR Blog',
  'https://bair.berkeley.edu/blog/2025/03/25/rl-av-smoothing/',
  'assets/img/covers/real/bair-rl-traffic-smoothing-100-av-deployment.jpg',
  'RL traffic smoothing 100 AV deployment cover',
  'cover',
  'published',
  false
),
(
  'arena-agent-arena-causal-evaluation',
  'Agent Arena: Causal Evaluation of Agents in the Real World',
  'Arena derives an agent leaderboard from millions of in-the-wild Agent Mode sessions using causal tracing: agent components such as the orchestrator model are randomized across sessions so treatment effects can be estimated with self-normalized importance weighting and time-decayed data. Five signals feed the ranking, including confirmed success, praise versus complaint, steerability, bash error recovery, and tool hallucination, though the platform data and sampling are not independently reproducible.',
  'Arena Team',
  'https://www.google.com/s2/favicons?domain=arena.ai&sz=128',
  'AI Agents',
  array['Agent Evaluation','Causal Inference','Leaderboard','Real-World Data'],
  '9 min read',
  '2026-06-04',
  'Arena.ai',
  'https://arena.ai/blog/agent-arena-methodology',
  'assets/img/covers/real/arena-agent-arena-causal-evaluation.png',
  'Agent Arena causal evaluation methodology cover',
  'cover',
  'published',
  false
),
(
  'github-copilot-agentic-harness-evaluation',
  'Evaluating the GitHub Copilot Agentic Harness Across Models and Tasks',
  'GitHub benchmarks its Copilot agentic harness against Claude Code and Codex CLI while holding model, task, context window, reasoning effort, and tool access fixed, across SWE-bench Verified, SWE-bench Pro, SkillsBench, TerminalBench 2.0, and an internal Windows benchmark. Task resolution lands on par with model-vendor harnesses at lower token consumption in most configurations, with run-to-run variance ellipses reported over five runs; normalized settings mean the numbers differ from public leaderboard submissions.',
  'GitHub',
  'https://www.google.com/s2/favicons?domain=github.blog&sz=128',
  'AI Agents',
  array['Agent Harness','Coding Agents','Benchmarking','Token Efficiency'],
  '7 min read',
  '2026-06-25',
  'GitHub Blog',
  'https://github.blog/ai-and-ml/github-copilot/evaluating-performance-and-efficiency-of-the-github-copilot-agentic-harness-across-models-and-tasks/',
  'assets/img/covers/real/github-copilot-agentic-harness-evaluation.png',
  'GitHub Copilot agentic harness evaluation cover',
  'cover',
  'published',
  false
),
(
  'letta-context-repositories',
  'Introducing Context Repositories: Git-based Memory for Coding Agents',
  'Letta rebuilds Letta Code memory as git-backed context repositories on the local filesystem: every memory change is versioned with informative commit messages, frontmatter descriptions and a pinned system directory drive progressive disclosure, and isolated worktrees let concurrent memory subagents reflect on history and merge findings through standard git conflict resolution. Built-in skills cover memory initialization, sleep-time reflection, and defragmentation; the design has no controlled benchmark evidence for its benefits yet.',
  'Letta',
  'https://www.google.com/s2/favicons?domain=letta.com&sz=128',
  'AI Agents',
  array['Agent Memory','Context Engineering','Git','Coding Agents'],
  '8 min read',
  '2026-02-12',
  'Letta Blog',
  'https://www.letta.com/blog/context-repositories/',
  'assets/img/covers/real/letta-context-repositories.png',
  'Letta context repositories article cover',
  'cover',
  'published',
  false
),
(
  'hf-braintrust-eval-agentic-setups',
  'How to Actually Evaluate AI Agents at Scale',
  'Analyzes 1,781 real agent traces from Exgentic using Braintrust with LLM-as-a-judge scoring, finding the harness moves success roughly 7x more than model choice (12% to 92% for a fixed model), open-weight models match closed ones on SWE-bench tasks, and cost per success ranks configurations very differently from cost per task. Also documents opposite failure patterns, with failing coding agents thrashing and burning tokens while failing customer-service agents give up early; results reflect one trace dataset and judge setup.',
  'Jessica (darubberduckiee)',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'AI Agents',
  array['Agent Evaluation','Trace Analysis','LLM-as-a-Judge','Cost Analysis'],
  '12 min read',
  '2026-06-24',
  'Hugging Face Blog',
  'https://huggingface.co/blog/darubberduckiee/using-braintrust-to-eval-agentic-setups',
  'assets/img/covers/real/hf-braintrust-eval-agentic-setups.png',
  'Evaluating AI agents at scale article cover',
  'cover',
  'published',
  false
),
(
  'hf-is-it-agentic-enough',
  'Is It Agentic Enough? Benchmarking Open Models on Your Own Tooling',
  'Hugging Face maintainers build a tool-specific agentic benchmark around transformers that measures not just task success but how much work the agent needed, sweeping models, library revisions, and tasks with runs fanned out on identical hardware via Hugging Face Jobs and driven entirely by open models with the pi coding agent. They test whether adding a CLI, a Skill, and self-contained task examples makes the library easier for agents to drive, and use in-run markers to attribute where agents struggle.',
  'Lysandre, Nathan Habib, Pedro Cuenca',
  'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
  'AI Agents',
  array['Agentic Benchmarking','Developer Tooling','Open Models','Coding Agents'],
  '11 min read',
  '2026-06-18',
  'Hugging Face Blog',
  'https://huggingface.co/blog/is-it-agentic-enough',
  'assets/img/covers/real/hf-is-it-agentic-enough.png',
  'Is it agentic enough benchmark article cover',
  'cover',
  'published',
  false
),
(
  'microsoft-magentic-ui-human-centered-web-agent',
  'Magentic-UI: An Experimental Human-Centered Web Agent',
  'Microsoft Research releases Magentic-UI, an MIT-licensed research prototype built on Magentic-One and AutoGen that collaborates with users on web tasks through co-planning, co-tasking, action guards requiring approval for irreversible steps, and plan learning from prior sessions. Rather than pursuing full autonomy, the sandboxed system targets open questions about human-in-the-loop oversight for agents that browse, code, and manipulate files in real time.',
  'Microsoft Research',
  'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
  'AI Agents',
  array['Web Agents','Human-in-the-Loop','Agent Safety','Open Source'],
  '10 min read',
  '2025-05-19',
  'Microsoft Research Blog',
  'https://www.microsoft.com/en-us/research/blog/magentic-ui-an-experimental-human-centered-web-agent/',
  'assets/img/covers/real/microsoft-magentic-ui-human-centered-web-agent.jpg',
  'Magentic-UI human-centered web agent cover',
  'cover',
  'published',
  false
),
(
  'microsoft-magentic-one-generalist-multi-agent',
  'Magentic-One: A Generalist Multi-Agent System for Solving Complex Tasks',
  'Magentic-One uses an Orchestrator that maintains task and progress ledgers in outer and inner loops while directing WebSurfer, FileSurfer, Coder, and ComputerTerminal agents, reaching statistically competitive results with prior state of the art on GAIA, AssistantBench, and WebArena using unmodified GPT-4o. Microsoft releases it open-source on AutoGen alongside AutoGenBench for isolated, repeatable agentic evaluation, and candidly documents risky emergent behaviors such as agents attempting to recruit humans when stuck.',
  'Adam Fourney, Gagan Bansal, et al.',
  'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
  'AI Agents',
  array['Multi-Agent Systems','Orchestration','AutoGen','Agent Benchmarks'],
  '12 min read',
  '2024-11-04',
  'Microsoft Research',
  'https://www.microsoft.com/en-us/research/articles/magentic-one-a-generalist-multi-agent-system-for-solving-complex-tasks/',
  'assets/img/covers/real/microsoft-magentic-one-generalist-multi-agent.png',
  'Magentic-One generalist multi-agent system cover',
  'cover',
  'published',
  false
),
(
  'metr-task-standard-portable-evaluation-tasks',
  'Portable Evaluation Tasks via the METR Task Standard',
  'METR publishes a standard for defining agent evaluation tasks as a small Python TaskFamily, with required get_tasks and get_instructions functions plus optional install, permissions, scoring, and auxiliary-VM hooks, already used for over 1,000 tasks spanning AI R&D, cybersecurity, and autonomy and adopted by the UK AI Safety Institute. The standard targets containerized agent-environment tasks; text-only evals fall outside its scope and future versions may not be fully backwards-compatible.',
  'METR',
  'https://www.google.com/s2/favicons?domain=metr.org&sz=128',
  'AI Agents',
  array['Task Standard','Agent Evaluation','Interoperability','Benchmarks'],
  '8 min read',
  '2024-02-29',
  'METR',
  'https://metr.org/blog/2024-02-29-metr-task-standard/',
  'assets/img/covers/real/metr-task-standard-portable-evaluation-tasks.png',
  'METR task standard article cover',
  'cover',
  'published',
  false
),
(
  'metr-expenditure-horizon',
  'Expenditure Horizon: Measuring Optimization Ability',
  'METR proposes the expenditure horizon, the budget at which human effort becomes more cost-effective than an agent on an optimization problem, computed by comparing agent inference-scaling curves against estimated returns to human labor. Applied to the NanoGPT speedrun, marginal 1% improvements cost humans roughly $2,500, and preliminary agentic runs costing over $10K yield expenditure horizons of $0-$3K, indicating agents currently underperform humans on this heavily optimized frontier task.',
  'METR',
  'https://www.google.com/s2/favicons?domain=metr.org&sz=128',
  'AI Agents',
  array['AI R&D Evaluation','Scaling Curves','NanoGPT','Optimization'],
  '14 min read',
  '2026-07-21',
  'METR',
  'https://metr.org/blog/2026-07-21-expenditure-horizon/',
  'assets/img/covers/real/metr-expenditure-horizon.svg',
  'METR expenditure horizon schematic cover',
  'cover',
  'published',
  false
),
(
  'meta-dynabench-rethinking-ai-benchmarking',
  'Dynabench: Rethinking AI Benchmarking',
  'Dynabench introduces dynamic adversarial data collection: human annotators interact with state-of-the-art models in the loop and craft examples that fool them, producing benchmarks that cannot saturate the way static datasets like GLUE did and measuring model error rate under human pressure. It launches with four NLP tasks run in rounds with academic partners, building on the ANLI methodology where even GPT-3 performed near chance on adversarially collected examples.',
  'Douwe Kiela, Adina Williams',
  'https://www.google.com/s2/favicons?domain=ai.meta.com&sz=128',
  'AI Agents',
  array['Benchmarking','Adversarial Data','Human-in-the-Loop','NLP Evaluation'],
  '10 min read',
  '2020-09-24',
  'Meta AI',
  'https://ai.meta.com/blog/dynabench-rethinking-ai-benchmarking/',
  'assets/img/covers/real/meta-dynabench-rethinking-ai-benchmarking.jpg',
  'Dynabench dynamic benchmarking cover',
  'cover',
  'published',
  false
),
(
  'minimax-agent-team-long-running-tasks',
  'MiniMax Agent Team: Built for Long-Running Tasks and Continuous Evolution',
  'MiniMax upgrades its agent product around Agent Teams: a main agent acknowledges the task within seconds, splits it into parallel role-specialized workers with acceptance checks and retained memory, and reports at key checkpoints instead of blocking on every sub-step. The post is candid about why single agents fail on long tasks, citing context anxiety, degradation, and premature stopping, and about the costs of the team design, advising when a single agent remains the better choice.',
  'MiniMax',
  'https://www.google.com/s2/favicons?domain=minimax.io&sz=128',
  'AI Agents',
  array['Multi-Agent Teams','Long-Horizon Tasks','Agent Product Design','Orchestration'],
  '12 min read',
  '2026-05-27',
  'MiniMax',
  'https://www.minimax.io/blog/minimax-agent-team-long-running-1779893953',
  'assets/img/covers/real/minimax-agent-team-long-running-tasks.jpg',
  'MiniMax Agent Team announcement cover',
  'cover',
  'published',
  false
),
(
  'ai2-evaluating-scientific-discovery-agents',
  'Evaluating AI Agents for Scientific Discovery',
  'Ai2 revisits ScienceWorld and DiscoveryWorld as capability checks for science agents: frontier models climbed from under 10% to the low 80s on elementary-level experiment execution, yet complete only about 20% of DiscoveryWorld''s harder open-ended investigations that human scientists with advanced degrees solve around 70% of the time. DiscoveryWorld''s 120 tasks score process and understanding, not just outcomes, in fictional scientific settings that block reliance on memorized knowledge.',
  'Ai2',
  'https://www.google.com/s2/favicons?domain=allenai.org&sz=128',
  'AI Agents',
  array['Science Agents','Agent Benchmarks','DiscoveryWorld','Evaluation'],
  '9 min read',
  '2026-04-13',
  'Ai2 Blog',
  'https://allenai.org/blog/evaluating-scientific-discovery-agents',
  'assets/img/covers/real/ai2-evaluating-scientific-discovery-agents.avif',
  'Evaluating scientific discovery agents cover',
  'cover',
  'published',
  false
),
(
  'minimax-forge-scalable-agent-rl',
  'Forge: Scalable Agent RL Framework and Algorithm',
  'MiniMax details Forge, the RL framework behind M2.5, which decouples agents from training infrastructure through gateway-and-data-pool middleware so both white-box and black-box scaffolds can be trained, uses Windowed FIFO scheduling to limit distribution shift from asynchronous rollouts, and applies prefix-tree merging for a claimed 40x training speedup with mathematical equivalence. Training mixed over 100,000 real agent scaffolds at 200k context using CISPO with dense process and completion-time rewards; results are internal and tied to the MiniMax stack.',
  'MiniMax',
  'https://www.google.com/s2/favicons?domain=minimax.io&sz=128',
  'AI Agents',
  array['Agent RL','Training Infrastructure','CISPO','Reinforcement Learning'],
  '14 min read',
  '2026-02-14',
  'MiniMax Research',
  'https://www.minimax.io/blog/forge-scalable-agent-rl-en-1779896141',
  'assets/img/covers/real/minimax-forge-scalable-agent-rl.jpg',
  'MiniMax Forge agent RL framework cover',
  'cover',
  'published',
  false
),
(
  'microsoft-red-teaming-network-of-agents',
  'Red-Teaming a Network of Agents',
  'Microsoft red-teamed a live internal platform of 100+ always-on LLM agents with forums, direct messages, and a marketplace, demonstrating four network-level failures single-agent benchmarks miss: self-propagating worms that exfiltrate private data across hops, reputation pile-ons seeded through one trusted agent, Sybil-manufactured consensus that captures verification, and proxy chains that erase attacker traceability. A few agents spontaneously developed security norms that spread and reduced attack success, but defenses remain an open problem.',
  'Gagan Bansal, Shujaat Mirza, et al.',
  'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
  'AI Agents',
  array['Multi-Agent Security','Red Teaming','Prompt Injection','Agent Networks'],
  '13 min read',
  '2026-04-30',
  'Microsoft Research Blog',
  'https://www.microsoft.com/en-us/research/blog/red-teaming-a-network-of-agents-understanding-what-breaks-when-ai-agents-interact-at-scale/',
  'assets/img/covers/real/microsoft-red-teaming-network-of-agents.jpg',
  'Red-teaming a network of agents cover',
  'cover',
  'published',
  false
),
(
  'bair-intelligence-is-free-data-systems-for-agents',
  'Intelligence Is Free, Now What? Data Systems for, of, and by Agents',
  'Berkeley''s EPIC Data Lab lays out a research agenda for data systems as agents become the dominant workload: agentic speculation produces thousands of highly redundant SQL probes per request, with 80-90% duplicate sub-plans, motivating shared computation, approximate answers, batched query interfaces, and proactive feedback from the database. The post also covers structured memory and concurrency control for agent swarms plus workload-specific engines synthesized by agents, flagging reward hacking of incomplete specifications as the key verification risk.',
  'Aditya G. Parameswaran, et al.',
  'https://www.google.com/s2/favicons?domain=bair.berkeley.edu&sz=128',
  'AI Agents',
  array['Data Systems','Agent Infrastructure','Structured Memory','Research Agenda'],
  '14 min read',
  '2026-07-07',
  'BAIR Blog',
  'https://bair.berkeley.edu/blog/2026/07/07/intelligence-is-free-now-what/',
  'assets/img/covers/real/bair-intelligence-is-free-data-systems-for-agents.png',
  'Data systems for agents article cover',
  'cover',
  'published',
  false
),
(
  'bair-compound-ai-systems',
  'The Shift from Models to Compound AI Systems',
  'Argues that state-of-the-art AI results increasingly come from compound systems rather than single model calls, citing AlphaCode 2''s generate-and-filter over up to a million samples, AlphaGeometry''s LLM-plus-symbolic solver, Medprompt, and Gemini''s CoT@32, because system design is often a faster lever than more training compute. Surveys the emerging tooling landscape, including DSPy for end-to-end optimization and FrugalGPT for cost routing, and the open design, optimization, and operations questions compound systems raise.',
  'Matei Zaharia, Omar Khattab, et al.',
  'https://www.google.com/s2/favicons?domain=bair.berkeley.edu&sz=128',
  'AI Agents',
  array['Compound AI Systems','System Design','DSPy','LLM Applications'],
  '12 min read',
  '2024-02-18',
  'BAIR Blog',
  'https://bair.berkeley.edu/blog/2024/02/18/compound-ai-systems/',
  'assets/img/covers/real/bair-compound-ai-systems.png',
  'Compound AI systems article cover',
  'cover',
  'published',
  false
),
(
  'hazy-research-minions-to-openjarvis-retrospective',
  'From Minions to OpenJarvis: A Retrospective on Two Years in Local AI',
  'Hazy Research reviews two years of hybrid local-cloud inference: MinionS recovered 97.9% of GPT-4o accuracy at 5.7x lower cost by letting the cloud decompose long-context tasks for parallel local execution, Intelligence per Watt improved 5.3x in two years with 88.7% of single-turn queries answerable locally, and OpenJarvis v1.0 ships a five-primitive local-first personal AI stack. The pattern of cloud at search time and local at inference time still leaves browser-agentic and coding tasks favoring cloud models.',
  'Jon Saad-Falcon, Avanika Narayan',
  'https://www.google.com/s2/favicons?domain=hazyresearch.stanford.edu&sz=128',
  'AI Agents',
  array['Local Inference','Hybrid AI','Personal Agents','Efficiency'],
  '13 min read',
  '2026-05-15',
  'Hazy Research',
  'https://hazyresearch.stanford.edu/blog/2026-05-15-minions-to-openjarvis-retrospective',
  'assets/img/covers/real/hazy-research-minions-to-openjarvis-retrospective.png',
  'Minions to OpenJarvis retrospective cover',
  'cover',
  'published',
  false
),
(
  'google-few-shot-tool-use-doesnt-really-work-yet',
  'Few-shot Tool-use Doesn''t Really Work (Yet)',
  'Across 340+ controlled experiments spanning models, prompts, and strategies such as SelfAsk, Inline, and RARR, few-shot tool-assisted generation showed no improvement over strong no-tool baselines on DROP, GSM8K, MuSiQue, and StrategyQA, including on hard examples with rare entities or difficult calculations where tools were assumed to help. Some strategies cost 2-10x more tokens for no gain, and the post distills five evaluation pitfalls, concluding that training models to use tools is more promising than few-shot prompting.',
  'Alon Jacovi',
  'https://www.google.com/s2/favicons?domain=research.google&sz=128',
  'AI Agents',
  array['Tool Use','Few-Shot Learning','Negative Results','Evaluation Methodology'],
  '9 min read',
  '2024-05-30',
  'Google Research Blog',
  'https://research.google/blog/few-shot-tool-use-doesnt-really-work-yet/',
  'assets/img/covers/real/google-few-shot-tool-use-doesnt-really-work-yet.jpg',
  'Few-shot tool use evaluation cover',
  'cover',
  'published',
  false
),
(
  'microsoft-plugmem-reusable-knowledge-agent-memory',
  'PlugMem: Transforming Raw Agent Interactions into Reusable Knowledge',
  'PlugMem converts raw agent interaction histories into a structured memory graph of propositional facts and prescriptive skills, retrieves compact knowledge units routed by concepts and inferred intent, and distills them into task-ready guidance before they enter the context window. A single task-agnostic module outperformed generic retrieval and task-specific memories on long-conversation QA, multi-hop Wikipedia lookup, and web browsing while consuming fewer memory tokens; code is released on GitHub.',
  'Ke Yang, Michel Galley, et al.',
  'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
  'AI Agents',
  array['Agent Memory','Knowledge Graphs','Retrieval','Context Efficiency'],
  '9 min read',
  '2026-03-10',
  'Microsoft Research Blog',
  'https://www.microsoft.com/en-us/research/blog/from-raw-interaction-to-reusable-knowledge-rethinking-memory-for-ai-agents/',
  'assets/img/covers/real/microsoft-plugmem-reusable-knowledge-agent-memory.jpg',
  'PlugMem agent memory article cover',
  'cover',
  'published',
  false
)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;

select id, title, category, publish_date, status
from public.blogs
where id in (
  'sander-dieleman-noise-schedules-considered-harmful',
  'sander-dieleman-paradox-of-diffusion-distillation',
  'nvidia-autoregressive-video-generation',
  'meta-muse-image-muse-video',
  'nvidia-video-gen-is-an-infra-problem',
  'diffusion-meets-flow-matching',
  'meta-fair-partnr-human-robot-collaboration',
  'ai2-molmospaces-embodied-ai-ecosystem',
  'bair-rl-traffic-smoothing-100-av-deployment',
  'arena-agent-arena-causal-evaluation',
  'github-copilot-agentic-harness-evaluation',
  'letta-context-repositories',
  'hf-braintrust-eval-agentic-setups',
  'hf-is-it-agentic-enough',
  'microsoft-magentic-ui-human-centered-web-agent',
  'microsoft-magentic-one-generalist-multi-agent',
  'metr-task-standard-portable-evaluation-tasks',
  'metr-expenditure-horizon',
  'meta-dynabench-rethinking-ai-benchmarking',
  'minimax-agent-team-long-running-tasks',
  'ai2-evaluating-scientific-discovery-agents',
  'minimax-forge-scalable-agent-rl',
  'microsoft-red-teaming-network-of-agents',
  'bair-intelligence-is-free-data-systems-for-agents',
  'bair-compound-ai-systems',
  'hazy-research-minions-to-openjarvis-retrospective',
  'google-few-shot-tool-use-doesnt-really-work-yet',
  'microsoft-plugmem-reusable-knowledge-agent-memory'
)
order by publish_date desc, id asc;
